<?php
//首页样式定义
$indexpage[0]=array('默认首页','index','经典简介企业网站首页','view.jpg');//array('风格名称,'调用首页文件名','首页简介','预览图片名称')
$indexpage[1]=array('多文章栏目首页','index1','适合以服务和文章信息较多的企业网站','view1.jpg');//array('风格名称,'调用首页文件名','首页简介','预览图片名称')
//CSS样式定义
$cssnum[0]=array('蓝色','metinfo.css');//array('风格名称,'调用css名称')
$cssnum[1]=array('红色','redmetinfo.css');//array('风格名称,'调用css名称')
$cssnum[2]=array('绿色','greenmetinfo.css');////array('风格名称,'调用css名称')
$cssnum[3]=array('黄色','yellowmetinfo.css');////array('风格名称,'调用css名称')
?>