
INSERT INTO met_column VALUES('1','关于我们','about','about','0','1','1','0','0','1','','','<p style=\"padding-top: 5px\">\r\n	<img alt=\"\" src=\"../upload/logoimg.gif\" style=\"margin: 0px 5px 5px 0px; width: 150px; float: left; height: 150px\" />米拓信息（MetInfo.cn）专注于网络信息化及网络营销领域，通过整合团队专业的市场营销理念与网络技术为客户提供优质的网络营销服务。</p>\r\n<p>\r\n	米拓信息的主要业务包括：网站系统开发、网站建设、网站推广、空间域名以及网络营销策划与运行。<br />\r\n	&nbsp;<br />\r\n	米拓信息主打产品&mdash;&mdash;MetInfo企业网站管理系统采用PHP+Mysql架构，全站内置了SEO搜索引擎优化机制，支持用户自定义界面语言，拥有企业网站常用的模块功能（企业简介模块、新闻模块、产品模块、下载模块、图片模块、招聘模块、在线留言、反馈系统、在线交流、友情链接、会员与权限管理）。强大灵活的后台管理功能、静态页面生成功能、个性化模块添加功能、不同栏目自定义FLASH样式功能等可为企业打造出大气漂亮且具有营销力的精品网站。</p>\r\n<p>\r\n	米拓信息秉承&ldquo;为合作伙伴创造价值&rdquo;的核心价值观，并以&ldquo;诚实、宽容、创新、服务&rdquo;为企业精神，通过自主创新和真诚合作为电子商务及信息服务行业创造价值。</p>\r\n<p>\r\n	<strong>关于&ldquo;为合作伙伴创造价值&rdquo;</strong><br />\r\n	米拓信息认为客户、供应商、公司股东、公司员工等一切和自身有合作关系的单位和个人都是自己的合作伙伴，并只有通过努力为合作伙伴创造价值，才能体现自身的价值并获得发展和成功。</p>\r\n<p>\r\n	<strong>关于&ldquo;诚实、宽容、创新、服务&rdquo;</strong><br />\r\n	米拓信息认为诚信是一切合作的基础，宽容是解决问题的前提，创新是发展事业的利器，服务是创造价值的根本。<br />\r\n	&nbsp;</p>\r\n','','0','','1','','2','0','','','1','cn','','0');
INSERT INTO met_column VALUES('2','新闻中心','news','','0','2','2','0','0','1','','','','','1','','1','','0','0','','','1','cn','','0');
INSERT INTO met_column VALUES('3','产品中心','product','','0','3','3','0','0','1','','','','','0','','1','','1','0','','','1','cn','','0');
INSERT INTO met_column VALUES('4','下载中心','download','','0','4','4','0','0','3','','','','','0','','1','','0','0','','','1','cn','','0');
INSERT INTO met_column VALUES('5','成功案例','img','','0','5','5','0','0','1','','','','','0','','1','','6','0','','','1','cn','','0');
INSERT INTO met_column VALUES('6','招聘中心','job','','0','6','6','0','0','1','','','','','0','','1','','5','0','','','1','cn','','0');
INSERT INTO met_column VALUES('7','友情链接','link','','0','9','10','0','0','2','','','','','0','','1','','0','0','','','1','cn','','0');
INSERT INTO met_column VALUES('8','会员中心','member','','0','10','11','0','0','2','','','','','0','','1','','0','0','','','1','cn','','0');
INSERT INTO met_column VALUES('9','站内搜索','search','','0','11','12','0','0','2','','','','','0','','1','','0','0','','','1','cn','','0');
INSERT INTO met_column VALUES('10','网站地图','sitemap','','0','12','13','0','0','2','','','','','0','','1','','0','0','','','1','cn','','0');
INSERT INTO met_column VALUES('11','网站管理','','','0','0','100','0','1','2','','','','','0','','1','admin/','0','0','','','1','cn','','0');
INSERT INTO met_column VALUES('13','在线反馈','feedback','','1','8','0','0','0','2','','','','','0','','2','','0','0','','','1','cn','','1');
INSERT INTO met_column VALUES('14','在线留言','message','','1','7','0','0','0','2','','','','','0','','2','','0','0','','','1','cn','','1');
INSERT INTO met_column VALUES('15','联系我们','about','','1','1','8','0','0','1','','','<p>\r\n	<strong>长沙</strong><strong>米拓信息</strong><strong>技术有限公司</strong><br />\r\n	地&nbsp; 址：长沙市岳麓区西二环一段1618号望兴景园1栋307<br />\r\n	电&nbsp; 话：0731-87133078 88920794<br />\r\n	Q&nbsp;&nbsp;&nbsp; Q：426507856 348468810 1302730113<br />\r\n	邮&nbsp; 编：410205<br />\r\n	email：<a href=\"mailto:sales@metinfo.cn\"><span style=\"color: #ff0000\">sales@metinfo.cn</span></a><br />\r\n	网&nbsp; 址：<a href=\"http://www.MetInfo.cn\"><span style=\"color: #ff0000\">www.MetInfo.cn</span></a></p>\r\n','','0','','2','','0','0','','','1','cn','','0');
INSERT INTO met_column VALUES('16','企业新闻','news','','2','2','0','0','0','0','','','','','1','','2','','3','0','','','1','cn','','0');
INSERT INTO met_column VALUES('17','行业新闻','news','','2','2','0','0','0','0','','','','','1','','2','','4','0','','','1','cn','','0');
INSERT INTO met_column VALUES('18','珠宝首饰','product','','3','3','0','0','0','0','','','','','0','','2','','0','0','','','1','cn','','0');
INSERT INTO met_column VALUES('19','数码家电','product','','3','3','0','0','0','0','','','','','0','','2','','0','0','','','1','cn','','0');
INSERT INTO met_column VALUES('20','家具建材','product','','3','3','0','0','0','0','','','','','0','','2','','0','0','','','1','cn','','0');
INSERT INTO met_column VALUES('21','交通工具','product','','3','3','0','0','0','0','','','','','0','','2','','0','0','','','1','cn','','0');
INSERT INTO met_column VALUES('22','健身器材','product','','3','3','0','0','0','0','','','','','0','','2','','0','0','','','1','cn','','0');
INSERT INTO met_column VALUES('23','日化五金','product','','3','3','0','0','0','0','','','','','0','','2','','0','0','','','1','cn','','0');
INSERT INTO met_column VALUES('24','婚纱摄影','product','','3','3','0','0','0','0','','','','','0','','2','','0','0','','','1','cn','','0');
INSERT INTO met_column VALUES('25','书画艺术','product','','3','3','0','0','0','0','','','','','0','','2','','0','0','','','1','cn','','0');
INSERT INTO met_column VALUES('26','软件下载','download','','4','4','0','0','0','0','','','','','0','','2','','0','0','','','1','cn','','0');
INSERT INTO met_column VALUES('27','文件下载','download','','4','4','0','0','0','0','','','','','0','','2','','0','0','','','1','cn','','0');
INSERT INTO met_column VALUES('28','电视机','product','','19','3','0','0','0','0','','','','','0','','3','','0','0','','','1','cn','','0');
INSERT INTO met_column VALUES('29','笔记本','product','','19','3','0','0','0','0','','','','','0','','3','','0','0','','','1','cn','','0');
INSERT INTO met_column VALUES('30','洗衣机','product','','19','3','0','0','0','0','','','','','0','','3','','0','0','','','1','cn','','0');
INSERT INTO met_column VALUES('31','电冰箱','product','','19','3','0','0','0','0','','','','','0','','3','','0','0','','','1','cn','','0');

INSERT INTO met_download VALUES('1','MetCMS企业网站管理系统V4.0','','MetCMS企业网站管理系统V4.0','<p>\r\n	<strong>支持语言</strong><br />\r\n	1、<font color=\"#ff0000\">支持全球各种语言（包括简体中文、繁体中文、英文、日文等等）</font>，用户可以无限自定义多种语言，并可以在后台根据需要设置相应语言访问域名和自定义默认首页；<br />\r\n	2、独创的语言包编辑功能，用户可以通过网站管理后台轻松的编辑网站语言包,从而控制前台显示语言和语言参数（字体、文字大小、网页背景、显示字数等等）；<br />\r\n	<br />\r\n	<b>界面风格</b><br />\r\n	1、全站文字、系统栏目、信息内容及主要图片支持用户自定义，<font color=\"#ff0000\"><b>所见即可改</b></font>；<br />\r\n	2、<font color=\"#0000ff\">独创的栏目标识显示控制方法，管理员只需要通过设置栏目标识便可以灵活的控制首页显示栏目及相关信息列表等</font>；<br />\r\n	3、前台模板与程序完全分离，独创的各种语言共用一套风格模板技术，也可以为每种语言设置不同的页面风格；<br />\r\n	4、风格模板制作简单灵活，同时支持标签化模板制作及PHP标准语法模板制作方法；<br />\r\n	5、独创的同一套模板支持不同的颜色风格、同时支持多种首页布局，用户可以通过后台轻松切换；<br />\r\n	6、缩略图自动生成、图片文字水印后台自定义、上传图片时水印自动添加功能；<br />\r\n	7、Flash动画（广告）可以根据栏目设置不同样式（包括图片轮播、Flash动画、单张图片），并可以选择多种不同的图片轮播方式；<br />\r\n	8、内置多种在线交流随屏幕滚动样式；<br />\r\n	9、独创的产品图片及图片模块图片多种样式显示模式，支持同一产品添加无限张图片；<br />\r\n	10、翻页样式、每页信息显示数、时间格式、热门信息点击次数、最新信息发布天数等完全实现后台自定义；<br />\r\n	11、DIV+CSS布局，全部兼容IE6、IE7、IE8、火狐、谷歌、TT、360度、遨游等主流浏览器；<br />\r\n	<br />\r\n	<b>网站内容</b><br />\r\n	1、简介、文章、产品、下载、图片模块三级栏目添加功能，栏目显示方式及显示与否完全有管理员通过后台控制；<br />\r\n	2、使用所见即所得文字编辑器fckeditor，可以轻松实现文字、图片、动画的添加与排版，支持内容手动分页；<br />\r\n	3、后台语言内容管理互相独立，不同管理员可以设置不同的语言内容管理权限；<br />\r\n	4、<font color=\"#0000ff\">产品、图片、下载字段自定义功能（包括简短、下拉、文本、多选、单选、图片字段），每个产品可以上传多张产品图片</font>；<br />\r\n	5、后台信息管理支持批量删除、批量转移、批量权限设置操作；<br />\r\n	6、支持多种信息列表排序方式；<br />\r\n	7、支持信息置顶、推荐等设置；<br />\r\n	<br />\r\n	<b>SEO优化</b><br />\r\n	1、<font color=\"#0000ff\">可设置网站SEO参数及所有页面SEO信息，如关键词、页面描述等</font>；<br />\r\n	2、<font color=\"#ff0000\">全站静态页面生成功能，可自动或手动一键生成全站静态页面，并可以个性化静态页面名称及静态页面格式</font>；<br />\r\n	3、页面标题已经按照&ldquo;信息标题-栏目名称-网站Title&rdquo;方式进行全面优化，所有Title内容均由系统自动生成；<br />\r\n	4、内置热门标签功能，可有效增加网站内部链接和关键词链接；<br />\r\n	5、官方模板通过DIV+CSS构架对标题H1、图片ALT、超链接Title、页头页尾关键词、首页信息更新排版、相关信息内链等全方位SEO优化；<br />\r\n	6、内置网站地图模块，可以生成最新新的HTML和xml网站地图；<br />\r\n	7、内置友情链接模块，可以轻松完成与其他网站的相互连接；<br />\r\n	8、支持栏目文件夹自定义和栏目内容页面静态页面名称及格式自定义，可以有效区分竞争对手同质化信息，增强SEO的效果；<br />\r\n	<br />\r\n	<b>互动营销</b><br />\r\n	1、<font color=\"#ff0000\">内置完整的在线交流后台管理功能、可添加QQ、MSN、淘宝旺旺、阿里旺旺、SKYPE、第三方客服交流软件等，并可以设置显示风格和图标</font>；<br />\r\n	2、<font color=\"#0000ff\">内置强大的在线反馈系统，表单字段完全自定义，可以用于产品订购、在线报名、在线调查、意见反馈等，可以自动将反馈信息发送至管理员设置的指定邮箱（可设置多个邮箱），并可以分类导出EXCEL表格形式的反馈信息</font>；<br />\r\n	3、在线留言后台管理功能及邮件发送功能，管理员可以通过后台审核和回复留言内容；<br />\r\n	4、招聘信息发布和应聘者简历在线提交功能，简历自动发送到指定邮箱功能；<br />\r\n	5、后台内置第三方统计代码及其他工具代码接口，可以轻松监控网站浏览及来访者详情；<br />\r\n	<br />\r\n	<b>会员与权限管理</b><br />\r\n	1、系统内置游客、普通会员、代理商、系统管理员四种权限角色，并可以实现普通会员、代理商前台注册与后台管理；<br />\r\n	2、语言内容、全站栏目、信息页面、字段参数均可以进行权限控制，进而可以灵活的设置代理价格、资料下载、最新产品公布等等的权限管理；<br />\r\n	3、可直接根据后台栏目设置管理员权限及操作权限功能，从而可以实现网站栏目及内容多人独立管理，且可以使管理员操作界面简洁明了；<br />\r\n	<br />\r\n	<b>安全与效率</b><br />\r\n	1、内置数据库备份和恢复功能，可一键轻松完成整站数据库备份与恢复，支持配置文件和整站后台压缩打包下载；<br />\r\n	2、后台管理文件夹名称后台更改功能，可以让你轻松的隐藏管理登陆路径，从而提高系统安全性能；<br />\r\n	3、验证码、防刷新机制、SQL危险符号和语句过滤机制等大大增强了系统防恶意攻击的能力；<br />\r\n	4、管理员密码邮箱找回功能、会员密码邮箱找回功能增强了系统的自助安全性能；<br />\r\n	5、安装文件夹、升级文件夹后台自定检查和删除功能；<br />\r\n	6、公共信息读取效率控制参数、模板调用数据库控制文件（由模板制作者控制）大大提高了系统的运行效率；<br />\r\n	7、上传文件夹及文件管理功能，可以轻松管理删除垃圾文件；<br />\r\n	8、PHP+MYSQL构架、全站静态功能、系统文件权限设置等大大增强了系统抗击木马和恶意攻击的能力；</p>\r\n','4','26','0','0','0','0','http://www.metinfo.cn/download/download_13_1.htm','4000','0','4','2011-05-19 13:41:58','2011-04-28 01:58:34','admin','1','0','1','','cn');

INSERT INTO met_flash VALUES('1','10001','MetInfo企业网站管理系统','../upload/201105/1305707368.jpg','http://www.metinfo.cn/','','','0','950','220','cn');
INSERT INTO met_flash VALUES('2','10001','MetInfo企业网站管理系统','../upload/201105/1305707518.jpg','http://www.metinfo.cn/web/metcms.htm','','','1','950','220','cn');
INSERT INTO met_flash VALUES('3','10000','MetInfo企业网站管理系统','../upload/201105/1305789894.jpg','','','','0','950','90','cn');

INSERT INTO met_img VALUES('4','示例案例一','示例案例一','示例案例一','','5','0','0','0','0','0','../upload/201105/1305774008.jpg','../upload/201105/thumb/1305774008.jpg','-../upload/201105/1305774705.jpg,-../upload/201105/1305774766.jpg,-../upload/201105/1305775417.jpg,-../upload/201105/1305774705.jpg,-../upload/201105/1305774766.jpg,-../upload/201105/1305775417.jpg,-../upload/201105/1305774705.jpg,-../upload/201105/1305774766.jpg','1','12','2011-05-19 11:11:09','2011-05-19 10:26:24','admin','0','0','','cn','','','','','','','','','');
INSERT INTO met_img VALUES('5','示例案例二','示例案例一','示例案例一','','5','0','0','0','0','0','../upload/201105/1305774612.jpg','../upload/201105/thumb/1305774612.jpg','','1','4','2011-05-19 11:00:01','2011-05-19 10:26:24','admin','0','0','','cn','','','','','','','','','');
INSERT INTO met_img VALUES('3','示例案例三','示例案例一','示例案例一','','5','0','0','0','0','0','../upload/201105/1305774864.jpg','../upload/201105/thumb/1305774864.jpg','','1','0','2011-05-19 11:02:10','2011-05-19 10:26:24','admin','0','0','','cn','','','','','','','','','');
INSERT INTO met_img VALUES('6','示例案例四','示例案例一','示例案例一','','5','0','0','0','0','0','../upload/201105/1305775850.jpg','../upload/201105/thumb/1305775850.jpg','','1','11','2011-05-19 11:17:39','2011-05-19 10:26:24','admin','0','0','','cn','','','','','','','','','');
INSERT INTO met_img VALUES('9','Example case 1','Example case 1','Example case 1','','36','0','0','0','0','0','../upload/201105/1305774008.jpg','../upload/201105/thumb/1305774008.jpg','-../upload/201105/1305774705.jpg,-../upload/201105/1305774766.jpg,-../upload/201105/1305775417.jpg,-../upload/201105/1305774705.jpg,-../upload/201105/1305774766.jpg,-../upload/201105/1305775417.jpg,-../upload/201105/1305774705.jpg,-../upload/201105/1305774766.jpg','1','16','2011-05-19 17:28:20','2011-05-19 10:26:24','admin','0','0','','en','','','','','','','','','');
INSERT INTO met_img VALUES('7','示例案例五','示例案例一','示例案例一','','5','0','0','0','0','0','../upload/201105/1305775479.jpg','../upload/201105/thumb/1305775479.jpg','','1','4','2011-05-19 11:18:44','2011-05-19 10:26:24','admin','0','0','','cn','','','','','','','','','');
INSERT INTO met_img VALUES('8','示例案例六','示例案例一','示例案例一','','5','0','0','0','0','0','../upload/201105/1305776095.jpg','../upload/201105/thumb/1305776095.jpg','','1','0','2011-05-19 11:18:55','2011-05-19 10:26:24','admin','0','0','','cn','','','','','','','','','');

INSERT INTO met_index VALUES('1','<p style=\"padding-top: 2px\">\r\n	<strong><img alt=\"\" src=\"upload/images/hibuilding2_004.jpg\" style=\"border-bottom: #dedede 1px solid; border-left: #dedede 1px solid; width: 150px; float: left; height: 113px; border-top: #dedede 1px solid; margin-right: 5px; border-right: #dedede 1px solid\" />关于&ldquo;为合作伙伴创造价值&rdquo;</strong><br />\r\n	米拓信息认为客户、供应商、公司股东、公司员工等一切和自身有合作关系的单位和个人都是自己的合作伙伴，并只有通过努力为合作伙伴创造价值，才能体现自身的价值并获得发展和成功。</p>\r\n<p>\r\n	<strong>关于&ldquo;诚实、宽容、创新、服务&rdquo;</strong><br />\r\n	米拓信息认为诚信是一切合作的基础，宽容是解决问题的前提，创新是发展事业的利器，服务是创造价值的根本。<span style=\"display: none\">&nbsp;</span></p>\r\n','cn');

INSERT INTO met_job VALUES('1','网络销售','0','长沙','面议','2011-04-28','0','<p>\r\n	1、大专以上学历，一年以上网络销售经验；<br />\r\n	2、熟悉网络推广，熟悉网站建设基本流程；<br />\r\n	3、有网站制作相关工作经验者优先；<br />\r\n	4、学习能力强，能吃苦耐劳，愿意同公司共同发展。<br />\r\n	5、本岗位招收兼职，投递简历时请说明自己的工作意愿；<br />\r\n	&nbsp;</p>\r\n<p>\r\n	如果你对我们的职位感兴趣，且符合我们的基本要求，请将个人简历投递至<a _fcksavedurl=\"mailto:metinfo@qq.com\" href=\"mailto:metinfo@qq.com\">metinfo@qq.com</a>，或者直接与我们取得联系！<span style=\"display: none\">&nbsp;</span></p>\r\n','0','1','0','0','','','cn');
INSERT INTO met_job VALUES('2','PHP技术支持','0','长沙','面议','2011-04-28','0','<p>\r\n	<strong>主要工作内容：</strong><br />\r\n	<br />\r\n	1. 负责MetInfo企业网站管理系统技术支持；<br />\r\n	2. 为客服人员提供技术支持；<br />\r\n	<br />\r\n	<strong>岗位要求： </strong><br />\r\n	<br />\r\n	1. php能看懂且对PHP感兴趣，理解面向对象基本概念，写过一些小程序；<br />\r\n	2. 懂MySql数据库备份、恢复等基本操作，熟悉PHP环境的搭建和配置；<br />\r\n	3. javascript能看懂，了解jquery等js框架；<br />\r\n	4. html/css会写，懂linux的优先；<br />\r\n	5. 擅长网上查找资料解决问题；<br />\r\n	6. 有PHP作品（留言板，blog等）的优先；<br />\r\n	7. 做事要有耐心，性格谦和，学习能力强，能吃苦耐劳，愿意同公司共同发展。<br />\r\n	<br />\r\n	如果你对我们的职位感兴趣，且符合我们的基本要求，请将个人简历投递至<a _fcksavedurl=\"mailto:metinfo@qq.com\" href=\"mailto:metinfo@qq.com\">metinfo@qq.com</a>，或者直接与我们取得联系！<span style=\"display: none\">&nbsp;</span><br />\r\n	<span style=\"display: none\">&nbsp;</span></p>\r\n','0','2','0','0','','','cn');
INSERT INTO met_job VALUES('3','网页美工','0','长沙','面议','2011-04-28','0','<strong>主要工作内容：</strong>负责网站美工设计、网站风格开发等。<br />\r\n<br />\r\n<strong>岗位要求：</strong><br />\r\n1、计算机、美术、设计或相关专业，大专以上学历。<br />\r\n2、有企业网站设计同等职位工作经验，能提供过往作品。<br />\r\n3、具备美术功底，对网页色彩及主题把握性强。<br />\r\n4、熟悉photoshop、Flash、Firework、DreamWeaver等美工设计软件，熟练DIV+CSS制作网页。<br />\r\n5、学习能力强，能吃苦耐劳，愿意同公司共同发展。<br />\r\n6、熟悉HTML代码，懂PHP基本语言者优先。<br />\r\n7、熟悉网站制作、设计流程，能跟踪最新的网页设计、制作技术。<br />\r\n<span style=\"display: none\">&nbsp;</span><br />\r\n如果你对我们的职位感兴趣，且符合我们的基本要求，请将个人简历投递至<a _fcksavedurl=\"mailto:metinfo@qq.com\" href=\"mailto:metinfo@qq.com\">metinfo@qq.com</a>，或者直接与我们取得联系！<span style=\"display: none\">&nbsp;</span>','0','3','0','0','','','cn');
INSERT INTO met_job VALUES('4','Web前端开发人员','0','长沙','面议','2011-04-28','0','<strong>主要工作内容：</strong>负责MetInfo企业网站管理系统前台模板功能设计、用户体验提升和Web界面技术优化。<br />\r\n<br />\r\n<strong>岗位要求：</strong><br />\r\n1、熟悉JavaScript、Ajax、JQuery等前端开发脚本技能；<br />\r\n2、精通HTML/XHTML、CSS，能够快速手写CSS代码，熟悉页面架构和布局。<br />\r\n3、熟悉Web网站以及Web应用的可用性及用户分析方法，深入理解产品流程、用户体验和用户需求；对提升用户体验有一定经验及造诣。<br />\r\n5、对Web技术发展有强烈兴趣，有良好的学习能力和强烈的进取心，愿意同公司共同发展。<br />\r\n6、能跟踪最新的WEB前端设计、懂PHP基本语言者优先。<br />\r\n<span style=\"display: none\">&nbsp;</span><br />\r\n如果你对我们的职位感兴趣，且符合我们的基本要求，请将个人简历投递至<a _fcksavedurl=\"mailto:metinfo@qq.com\" href=\"mailto:metinfo@qq.com\">metinfo@qq.com</a>，或者直接与我们取得联系！<span style=\"display: none\">&nbsp;</span><br />\r\n','0','3','0','0','','','cn');
INSERT INTO met_job VALUES('5','电子商务专员','0','长沙','面议','2011-04-28','0','<p>\r\n	<strong>主要工作内容：</strong>负责MetInfo企业网站管理系统在线销售工作，向客户提供迅速、准确、周到的服务。<br />\r\n	<br />\r\n	<strong>岗位要求：</strong><br />\r\n	1、熟悉互联网销售与推广；<br />\r\n	2、能熟练操作网站管理系统后台，了解基本的建站知识；<br />\r\n	3、能敏锐把握网站建设行业市场动向，善于把握客户心理；<br />\r\n	4、沟通能力强，勤奋耐劳，办事认真严谨细致；<br />\r\n	5、具有较强的学习能力，愿意同公司共同发展；<br />\r\n	6、有网站建设相关产品工作经验者优先，电子商务、市场营销等相关专业优先。<br />\r\n	<br />\r\n	<span style=\"display: none\">&nbsp;</span>如果你对我们的职位感兴趣，且符合我们的基本要求，请将个人简历投递至<a _fcksavedurl=\"mailto:metinfo@qq.com\" href=\"mailto:metinfo@qq.com\">metinfo@qq.com</a>，或者直接与我们取得联系！<span style=\"display: none\">&nbsp;</span></p>\r\n','0','2','0','0','','','cn');

INSERT INTO met_label VALUES('2','米拓信息','米拓信息','MetInfo企业网站管理系统','http://www.metinfo.cn/','cn');

INSERT INTO met_link VALUES('1','MetInfo企业网站管理系统','http://www.metinfo.cn','../upload/201105/1303897408.gif','1','MetInfo企业网站管理系统','','100','1','1','2011-05-19 13:48:21','cn','');

INSERT INTO met_list VALUES('1','1','索取资料','1','cn');
INSERT INTO met_list VALUES('2','1','产品购买','2','cn');
INSERT INTO met_list VALUES('3','1','商务合作','3','cn');
INSERT INTO met_list VALUES('4','1','其他反馈','4','cn');
INSERT INTO met_list VALUES('5','7','北京','1','cn');
INSERT INTO met_list VALUES('6','7','天津','15','cn');
INSERT INTO met_list VALUES('7','7','河北','14','cn');
INSERT INTO met_list VALUES('8','7','内蒙古','13','cn');
INSERT INTO met_list VALUES('9','7','黑龙江','12','cn');
INSERT INTO met_list VALUES('10','7','辽宁','11','cn');
INSERT INTO met_list VALUES('11','7','吉林','10','cn');
INSERT INTO met_list VALUES('12','7','山西','9','cn');
INSERT INTO met_list VALUES('13','7','陕西','8','cn');
INSERT INTO met_list VALUES('14','7','甘肃','7','cn');
INSERT INTO met_list VALUES('15','7','青海','6','cn');
INSERT INTO met_list VALUES('16','7','宁夏','5','cn');
INSERT INTO met_list VALUES('17','7','新疆','4','cn');
INSERT INTO met_list VALUES('18','7','西藏','3','cn');
INSERT INTO met_list VALUES('19','7','四川','2','cn');
INSERT INTO met_list VALUES('20','7','重庆','16','cn');
INSERT INTO met_list VALUES('21','7','云南','17','cn');
INSERT INTO met_list VALUES('22','7','贵州','18','cn');
INSERT INTO met_list VALUES('23','7','湖南','19','cn');
INSERT INTO met_list VALUES('24','7','湖北','20','cn');
INSERT INTO met_list VALUES('25','7','河南','21','cn');
INSERT INTO met_list VALUES('26','7','山东','22','cn');
INSERT INTO met_list VALUES('27','7','安徽','23','cn');
INSERT INTO met_list VALUES('28','7','江苏','24','cn');
INSERT INTO met_list VALUES('29','7','上海','25','cn');
INSERT INTO met_list VALUES('30','7','浙江','26','cn');
INSERT INTO met_list VALUES('31','7','江西','27','cn');
INSERT INTO met_list VALUES('32','7','福建','28','cn');
INSERT INTO met_list VALUES('33','7','广东','29','cn');
INSERT INTO met_list VALUES('34','7','广西','30','cn');
INSERT INTO met_list VALUES('35','7','海南','31','cn');
INSERT INTO met_list VALUES('36','7','港澳台','32','cn');
INSERT INTO met_list VALUES('37','10','搜索引擎','1','cn');
INSERT INTO met_list VALUES('38','10','网站链接','2','cn');
INSERT INTO met_list VALUES('39','10','朋友介绍','3','cn');
INSERT INTO met_list VALUES('40','10','电视广告','4','cn');
INSERT INTO met_list VALUES('41','10','其他方式','5','cn');
INSERT INTO met_list VALUES('42','12','男','1','cn');
INSERT INTO met_list VALUES('43','12','女','2','cn');
INSERT INTO met_list VALUES('44','27','品牌一','1','cn');
INSERT INTO met_list VALUES('45','27','品牌二','2','cn');
INSERT INTO met_list VALUES('46','27','品牌三','3','cn');
INSERT INTO met_list VALUES('47','0','索取资料','1','en');
INSERT INTO met_list VALUES('48','0','产品购买','2','en');
INSERT INTO met_list VALUES('49','0','商务合作','3','en');
INSERT INTO met_list VALUES('50','0','其他反馈','4','en');
INSERT INTO met_list VALUES('51','0','北京','1','en');
INSERT INTO met_list VALUES('52','0','天津','15','en');
INSERT INTO met_list VALUES('53','0','河北','14','en');
INSERT INTO met_list VALUES('54','0','内蒙古','13','en');
INSERT INTO met_list VALUES('55','0','黑龙江','12','en');
INSERT INTO met_list VALUES('56','0','辽宁','11','en');
INSERT INTO met_list VALUES('57','0','吉林','10','en');
INSERT INTO met_list VALUES('58','0','山西','9','en');
INSERT INTO met_list VALUES('59','0','陕西','8','en');
INSERT INTO met_list VALUES('60','0','甘肃','7','en');
INSERT INTO met_list VALUES('61','0','青海','6','en');
INSERT INTO met_list VALUES('62','0','宁夏','5','en');
INSERT INTO met_list VALUES('63','0','新疆','4','en');
INSERT INTO met_list VALUES('64','0','西藏','3','en');
INSERT INTO met_list VALUES('65','0','四川','2','en');
INSERT INTO met_list VALUES('66','0','重庆','16','en');
INSERT INTO met_list VALUES('67','0','云南','17','en');
INSERT INTO met_list VALUES('68','0','贵州','18','en');
INSERT INTO met_list VALUES('69','0','湖南','19','en');
INSERT INTO met_list VALUES('70','0','湖北','20','en');
INSERT INTO met_list VALUES('71','0','河南','21','en');
INSERT INTO met_list VALUES('72','0','山东','22','en');
INSERT INTO met_list VALUES('73','0','安徽','23','en');
INSERT INTO met_list VALUES('74','0','江苏','24','en');
INSERT INTO met_list VALUES('75','0','上海','25','en');
INSERT INTO met_list VALUES('76','0','浙江','26','en');
INSERT INTO met_list VALUES('77','0','江西','27','en');
INSERT INTO met_list VALUES('78','0','福建','28','en');
INSERT INTO met_list VALUES('79','0','广东','29','en');
INSERT INTO met_list VALUES('80','0','广西','30','en');
INSERT INTO met_list VALUES('81','0','海南','31','en');
INSERT INTO met_list VALUES('82','0','港澳台','32','en');
INSERT INTO met_list VALUES('83','0','搜索引擎','1','en');
INSERT INTO met_list VALUES('84','0','网站链接','2','en');
INSERT INTO met_list VALUES('85','0','朋友介绍','3','en');
INSERT INTO met_list VALUES('86','0','电视广告','4','en');
INSERT INTO met_list VALUES('87','0','其他方式','5','en');


INSERT INTO met_message VALUES('1','张三','','','','你好！请问MetInfo企业网站管理系统怎么安装使用？','127.0.0.1','2011-05-18 17:17:45','1','您好！我们的帮助教材中有安装使用的教程！ http://www.metinfo.cn/help/help.htm','cn','0','admin');
INSERT INTO met_message VALUES('2','李四','','','','为什么首页很多地方都没有内容？','127.0.0.1','2011-05-18 17:19:59','1','如果你是刚刚安装好MetInfo企业网站管理系统发现首页很多地方都没有内容，那很正常。因为你没有添加相应的内容。你可以在后台--内容管理 选择对应的栏目添加内容； 如果在添加了内容之后首页一些地方还是没有显示内容，就请查看后台-界面风格--模板配置导航，那儿会告诉你怎么将首页配置完整，需要花点耐心，看懂了，以后首页想怎么玩都行； 如果修改了、设置正确了都还是不显示，再请查看后台是否开启了静态页面，如果开启了静态页面，在后台出添加信息之外的操作，都是需要重新生成静态页面才能够有效果的；如果以上方法都无法解决你的问题，我们建议你我们的技术论坛发帖提问，注意将网站地址填好，这样有益于针对提出的问题进行测试。 ','cn','0','admin');

INSERT INTO met_news VALUES('1','企业用网站进行网络宣传的优势','企业用网站进行网络宣传的优势','互联网用户70.54%集中在经济较为发达地区，64%家庭人均月收入高于1000元，85.8%年龄在18岁到35岁之间，83%受过大学以上教育。因此，网络宣传的目标群体是目前社会上层次最高、收入最高、消费能力最高的最具活力的消费群体。这一群体的消费总额往往大于其他消费层次之和。','<p>\r\n	<strong>1、网络宣传是多维宣传 </strong><br />\r\n	　　传统媒体是二维的，而网络宣传则是多维的，它能将文字、图像和声音有机的组合在一起，传递多感官的信息，让顾客如身临其境般感受商品或服务。使消费者能亲身体验产品、服务与品牌。这种图、文、声、像相结合的宣传形式，增强了网络宣传的实效。</p>\r\n<p>\r\n	<strong>2、网络宣传拥有最有活力的消费群体</strong><br />\r\n	　　互联网用户70.54%集中在经济较为发达地区，64%家庭人均月收入高于1000元，85.8%年龄在18岁到35岁之间，83%受过大学以上教育。因此，网络宣传的目标群体是目前社会上层次最高、收入最高、消费能力最高的最具活力的消费群体。这一群体的消费总额往往大于其他消费层次之和。</p>\r\n<p>\r\n	<strong>3、网络宣传制作成本低，速度快，更改灵活</strong><br />\r\n	　　网络宣传制作周期短，即使在较短的周期进行投放，也可以根据客户的需求很快完成制作，而传统宣传制作成本高，投放周期固定。另外，在传统媒体上做宣传发布后很难更改即使可以改动往往也须付出很大的经济代价。而在互联网上做宣传能够按照客户需要及时变更宣传内容。这样，经营决策的变化就能及时实施和推广。</p>\r\n<p>\r\n	<strong>4、网络宣传具有交互性和纵深性</strong><br />\r\n	　　交互性强是互联网络媒体的最大的优势，它不同于传统媒体的信息单向传播，而是信息互动传播。通过链接，用户只需简单地点击鼠标，就可以从厂商的相关站点中得到更多、更详尽的信息。另外，用户可以通过网络直接填写并提交在线表单信息，厂商可以随时得到宝贵的用户反馈信息，进一步减少了用户和宣传客户之间的距离。同时，网络宣传可以提供进一步的产品查询需求。</p>\r\n<p>\r\n	<strong>5、网络宣传能进行完善的统计</strong><br />\r\n	　　&quot;无法衡量的东西就无法管理。&quot;网络宣传通过及时和精确的统计机制，使用户能够直接对信息的发布进行在线监控。而传统的信息发布形式只能通过并不精确的收视率、发行量等来统计投放的受众数量。</p>\r\n<p>\r\n	<strong>6、网络宣传可以跟踪和衡量宣传的效果</strong><br />\r\n	　　用户能通过Internet即时衡量宣传的效果。通过监视宣传的浏览量、点击率等指标，用户可以统计出多少人看到了发布的信息，其中有多少人对发布的信息感兴趣进而进一步了解了信息的详细信息。因此，较之其他任何宣传，网络宣传使用户能够更好地跟踪受众的反应，及时了解用户和潜在用户的情况。</p>\r\n<p>\r\n	<strong>7、网络宣传的投放更具有针对性</strong><br />\r\n	　　通过提供众多的免费服务，网站一般都能建立完整的用户数据库，包括用户的地域分布、年龄、性别、收入、职业、婚姻状况、爱好等。这些资料可帮助用户分析市场与受众，根据信息发布目标受众的特点，有针对性地进行信息发布，并根据用户特点作定点投放和跟踪分析，对投放效果作出客观准确的评价。<br />\r\n	另外，网络宣传还可以提供有针对性的内容环境。不同的网站或者是同一网站不同的频道所提供的服务是不同质且具有很强的类分别的，这就为密切迎合用户的兴趣提供了可能。</p>\r\n<p>\r\n	<strong>8、网络宣传的受众关注度高</strong><br />\r\n	　　据资料显示，电视并不能集中人的注意力，电视观众40%的人同时在阅读，21%的人同时在做家务，13%的人在吃喝，12%的人在玩赏它物，10%在烹饪，9%在写作，8%在打电话。而网上用户55%在使用计算机时不做任何它事，只有6%同时在打电话，只有5%在吃喝，只有4%在写作。</p>\r\n<p>\r\n	<strong>9、网络宣传缩短了媒体投放的进程</strong><br />\r\n	　　用户在传统媒体上进行市场推广一般要经过三个阶段：市场开发期、市场巩固期和市场维持期。在这三个阶段中，厂商要首先获取注意力，创立品牌知名度；在消费者获得品牌的初步信息后，推广更为详细的产品信息。然后是建立和消费者之间较为牢固的联系，以建立品牌忠诚。而互联网将这三个阶段合并在一次信息发布中实现：消费者看到网络宣传，点击后获得详细信息，并填写用户资料或直接参与用户的市场活动甚至直接在网上实施购买行为。</p>\r\n<p>\r\n	<strong>10、网络宣传传播范围广、不受时空限制</strong><br />\r\n	　　通过国际互联网络，网络宣传可以将信息24小时不间断地传播到世界的每一个角落。只要具备上网条件，任何人，在任何地点都可以阅读。这是传统媒体无法达到的。</p>\r\n<p>\r\n	<strong>11、网络宣传具有可重复性和可检索性</strong><br />\r\n	　　网络宣传可以将文字、声音、画面完美地结合之后供用户主动检索，重复观看。而与之相比电视宣传却是让用户被动地接受宣传内容。如果错过宣传时间，就不能再得到发布信息。另外，显而易见，较之网络宣传的检索平面宣传的检索要费时、费事的多。</p>\r\n<p>\r\n	<strong>12、网络宣传具有价格优势</strong><br />\r\n	　　从价格方面考虑，与报纸杂志或电视宣传相比，目前网络宣传费用还是较为低廉的。获得同等的宣传效应，网络宣传的有效千人成本远远低于传统宣传媒体。一个宣传主页一年的费用大致为几千元人民币，而且主页内容可以随企业经营决策的变更随时改变，这是传统宣传媒体不可想像的。网络宣传将成为企业市场推广必不可少的高效途径。</p>\r\n<p>\r\n	<span style=\"display: none\">&nbsp;</span></p>\r\n','2','17','0','1','0','0','','','1','admin','1','2011-05-19 09:30:10','2011-05-18 20:57:46','0','0','','cn');
INSERT INTO met_news VALUES('2','MetInfo企业网站管理系统相比于网站建设公司自行开发的优势','MetInfo企业网站管理系统相比于网站建设公司自行开发的优势','MetInfo企业网站管理系统已经经过众多用户、多种运行环境的测试，并在不断完善和升级之中，从而促使系统功能会不断完善，运行更稳定与安全','<ol>\r\n	<li>\r\n		<strong>价格更低</strong>，网站建设公司自行开发系统，一般的开发成本都会在千元以上，就算网站建设公司使用自己已经开发的系统建站，客户的一些个性化需要也需要二次开发，而使用MetInfo企业网站管理系统能满足绝大多数企业网站的功能需求，且成本非常低，甚至为零；</li>\r\n	<li>\r\n		<strong>功能更完善、系统更安全</strong>，MetInfo企业网站管理系统已经经过众多用户、多种运行环境的测试，并在不断完善和升级之中，从而促使系统功能会不断完善，运行更稳定与安全；</li>\r\n	<li>\r\n		<strong>网站更具有营销力</strong>，借助MetInfo企业网站管理系统内置的SEO优化机制及静态页面生成功能等，使网站更容易被推广、更容易被搜索引擎收录、更容易提升关键词排名；</li>\r\n	<li>\r\n		<strong>完善的技术支持服务</strong>，根据用户所选服务等级，米拓官方提供论坛商业用户技术支持、QQ\\MSN、Email、电话等多种技术支持，且不会因为建站公司的转型而导致代码无人维护与升级；</li>\r\n	<li>\r\n		<strong>交流更便捷</strong>，MetInfo企业网站管理系统100%开源，拥有庞大用户群，用户可以在官方技术论坛及通过其他方式进行相互交流；</li>\r\n	<li>\r\n		<strong>更容易更换网站风格</strong>，使用MetInfo企业网站管理系统建站，配合优秀的前台模板，可以让前台所见的内容全部通过后台控制，从而使用户管理网站轻松自如；当企业想更换一种网站风格时，与网站公司自行开发的系统需要重新开发设计不同的是，企业只需要重新设计网站风格，而无须重新添加数据和开发网站后台；</li>\r\n</ol>\r\n','2','16','0','0','0','0','','','1','admin','0','2011-05-19 09:44:34','2011-05-18 21:14:54','0','0','','cn');
INSERT INTO met_news VALUES('3','使用MetInfo企业网站管理系统建站步骤','使用MetInfo企业网站管理系统建站步骤','使用MetInfo企业网站管理系统建站步骤','<p>\r\n	<font size=\"3\"><span style=\"color: rgb(0,0,255)\"><strong><span style=\"font-size: medium\">试用操作步骤</span></strong></span></font><br />\r\n	<br />\r\n	<strong>第一步：注册空间管理账号</strong><br />\r\n	登陆<a href=\"http://idc.metinfo.cn/\">http://idc.metinfo.cn/</a>，注册一个用户账号，并收取验证邮件对账号进行验证，如未收到验证邮件请直接与客服联系；</p>\r\n<p>\r\n	<strong>第二步：开通试用空间</strong><br />\r\n	（在线帮助：<a href=\"http://www.metinfo.cn/faq/shownews64.htm\">http://www.metinfo.cn/faq/shownews64.htm</a>）；</p>\r\n<p>\r\n	<strong>第三步：上传文件</strong><br />\r\n	上传MetInfo企业网站管理系统安装文件（如压缩上传需要在线解压），系统文件可以从官方网站下载（在线帮助：<a href=\"http://www.metinfo.cn/faq/shownews64.htm\">http://www.metinfo.cn/faq/shownews64.htm</a>）；</p>\r\n<p>\r\n	<strong>第四步：开通数据库</strong><br />\r\n	（在线帮助：<a href=\"http://www.metinfo.cn/faq/shownews65.htm\">http://www.metinfo.cn/faq/shownews65.htm</a>）；</p>\r\n<p>\r\n	<strong>第五步：安装网站管理系统</strong><br />\r\n	运行免费三级域名安装系统（在线帮助：<a href=\"http://www.metinfo.cn/faq/shownews66.htm\">http://www.metinfo.cn/faq/shownews66.htm</a>）；</p>\r\n<p>\r\n	<strong>第六步：管理网站</strong><br />\r\n	登陆网站后台，添加、修改网站相关信息及内容</p>\r\n<p>\r\n	<br />\r\n	<br />\r\n	<font size=\"3\"><span style=\"color: rgb(0,0,255)\"><strong><span style=\"font-size: medium\">正式开通操作步骤</span></strong></span></font><br />\r\n	<br />\r\n	<span style=\"color: rgb(255,0,0)\">需要联系米拓信息缴纳费用后方可进行</span></p>\r\n<p>\r\n	<strong>第一步：执行试用操作的所有步骤</strong></p>\r\n<p>\r\n	<strong>第二步：转正空间</strong><br />\r\n	（在线帮助：<a href=\"http://www.metinfo.cn/faq/shownews67.htm\">http://www.metinfo.cn/faq/shownews67.htm</a>）</p>\r\n<p>\r\n	<strong>第三步：注册域名</strong><br />\r\n	（在线帮助：<a href=\"http://www.metinfo.cn/faq/shownews68.htm\">http://www.metinfo.cn/faq/shownews68.htm</a>）</p>\r\n<p>\r\n	<strong>第四步：域名解析</strong><br />\r\n	（在线帮助：<a href=\"http://www.metinfo.cn/faq/shownews69.htm\">http://www.metinfo.cn/faq/shownews69.htm</a>）</p>\r\n<p>\r\n	<strong>第五步：绑定域名</strong><br />\r\n	登陆空间管理后台，添加已解析到空间的域名</p>\r\n<p>\r\n	<strong>第六步：网站备案</strong><br />\r\n	（在线帮助：<a href=\"http://www.metinfo.cn/faq/shownews70.htm\">http://www.metinfo.cn/faq/shownews70.htm</a>）</p>\r\n<p>\r\n	<strong>第七步：开通邮箱</strong><br />\r\n	（在线帮助：<a href=\"http://www.metinfo.cn/faq/shownews71.htm\">http://www.metinfo.cn/faq/shownews71.htm</a>）</p>\r\n','2','16','0','0','0','0','','','1','admin','5','2011-05-19 09:45:56','2011-05-19 09:45:56','0','0','','cn');
INSERT INTO met_news VALUES('4','商业版和免费版在系统功能上有区别吗？','商业版和免费版在系统功能上有区别吗？','商业版和免费版在系统功能上没有任何区别','<p>\r\n	商业版和免费版在系统功能上<span style=\"color: rgb(255,0,0)\">没有任何区别</span>。</p>\r\n<p>\r\n	<strong>商业版和免费版区别：</strong><br />\r\n	1、如您将程序用于商业用途，请自觉购买商业授权，否则我们将保留追究法律责任的权利；<br />\r\n	2、免费版和商业版在网站功能上没有任何区别，商业用户可以获取专业的技术支持服务；<br />\r\n	3、免费版如去除【Powered by MetInfo】版权标识将不能正常运行！米拓官方并将追求相应的法律责任！<br />\r\n	4、查看免费版与商业版的详细功能及服务对比：<a href=\"http://www.metinfo.cn/web/product.htm\" style=\"color: rgb(204,0,0)\" target=\"_blank\">查看详细</a></p>\r\n','2','16','0','0','0','0','','','0','admin','0','2011-05-19 09:56:53','2011-05-19 09:56:53','0','0','','cn');
INSERT INTO met_news VALUES('5','如何获取MetInfo网站管理系统商业授权？','如何获取MetInfo网站管理系统商业授权？','MetInfo企业网站管理系统是一款100%开源的企业网站管理系统，对于个人网站及非赢利网站是可以永久免费使用的，如果您是单位用户且将我们的系统用于商业用途，我们需要收取相应的版权使用费，以维持软件的开发成本和进一步发展，商业用户包括但不仅限于企业、事业单位、政府部门、学校等等；当然您也可以参加我们的促销活动，免费获取商业授权。','<p>\r\n	<span style=\"color: rgb(255,0,0)\"><strong>方法一、参加&ldquo;个性化网站模板换取商业授权活动&rdquo;</strong></span><br />\r\n	提供一套符合《MetInfo用户手册》模板制作规范要求的企业网站模板，便可以申请一个永久商业授权。具体要求如下：<br />\r\n	1）修改官方或已有模板者需要风格和功能与已有模板有明显的区别；<br />\r\n	2）模板文件应符合《MetInfo用户手册》模板制作规范要求，所有文件完整有序；<br />\r\n	3）模板首页栏目、相关联系方式及一切重要信息均可以通过后台配置进行修改；</p>\r\n<p>\r\n	<span style=\"color: rgb(0,0,128)\"><strong>方法二、购买官方虚拟空间免费获取相应时长的商业授权</strong></span><br />\r\n	购买官方虚拟空间，可以免费获取相应时长的商业授权，第二年只需要续费空间便可以继续免费获取商业授权，让MetInfo企业网站管理系统的商业授权费用一直为0；详细情况请参考<a href=\"http://www.metinfo.cn/web/promotion.htm\">http://www.metinfo.cn/web/promotion.htm</a>；</p>\r\n<p>\r\n	<strong>方法三、直接购买永久商业授权</strong><br />\r\n	普通版500元，高级版1000元，详细情况请参考<a href=\"http://www.metinfo.cn/web/product.htm\">http://www.metinfo.cn/web/product.htm</a></p>\r\n<p>\r\n	<strong>商业授权常见问答：</strong><br />\r\n	<span style=\"color: rgb(255,0,0)\">1、已经100%开源为什么还要收取商业授权费用？</span><br />\r\n	官方解答：MetInfo企业网站管理系统是一款100%开源的企业网站管理系统，对于个人网站及非赢利网站是可以永久免费使用的，如果您是单位用户且将我们的系统用于商业用途，我们需要收取相应的版权使用费，以维持软件的开发成本和进一步发展，商业用户包括但不仅限于企业、事业单位、政府部门、学校等等；当然您也可以参加我们的促销活动，免费获取商业授权。</p>\r\n<p>\r\n	<span style=\"color: rgb(255,0,0)\">2、获取商业授权有什么好处？</span><br />\r\n	官方解答：除了得到官方正式商业授权外，可以享受相应等级的官方技术支持服务。</p>\r\n<p>\r\n	<span style=\"color: rgb(255,0,0)\">3、哪些网站不需要购买商业授权？如何区分个人网站和单位网站？</span><br />\r\n	官方解答：所有个人网站（不限制用途）、非盈利性质的单位网站不需要购买商业版权，但未经商业授权许可，不允许去除官方版权信息。个人网站是指网站所有信息均以个人名义（包括无工商登记的个人和个体工商户）呈现的商业和非商业网站，以个人名义注册的域名和备案但用于宣传企业的网站不属于个人网站范畴。</p>\r\n','2','16','0','0','0','0','','','1','admin','81','2011-05-19 09:57:37','2011-05-19 09:57:37','0','0','','cn');
INSERT INTO met_news VALUES('6','为什么企业要建多国语言、多语种企业网站？','为什么企业要建多国语言、多语种企业网站？','互联网在不断发展壮大，已成为企业和个人寻求生意机会，对商品、服务和信息进行了解的首选方式。从站在增强一个企业竞争优势的角度看，建设一个多语言网站是不断增加客户数量的前提和提高销售的高效手段。\r\n','<p>\r\n	互联网在不断发展壮大，已成为企业和个人寻求生意机会，对商品、服务和信息进行了解的首选方式。从站在增强一个企业竞争优势的角度看，建设一个多语言网站是不断增加客户数量的前提和提高销售的高效手段。<br />\r\n	随着国际化进程的不断加快，多语言网站将成为企业和组织必不可少的一部分。<br />\r\n	多语言网站帮助企业面对众多的非英语国家互联网用户<br />\r\n	随着时间变化，非英语国家互联网用户的比例已不断在攀升。相比以前由讲英语的用户控制互联网的局面已产生了根本改变。尼尔森集团(一个美国互联网研究咨询公司)在05年3月谈到：国外互联网市场是&ldquo;将要成熟的果子&rdquo;，只要你愿意付出较少的努力就能够得到巨大的收获。结果显示，互联网的增长在美国、德国、英国和瑞典趋于缓慢，在其他国家例如法国，香港、意大利和日本则增长显着。<br />\r\n	尼尔森的一位高级分析员阐述：&ldquo;最容易得到的机会是在这个国家的互联网使用习惯和用户(或站点)关系被确立之前。在当前成长阶段培养的客户将成为未来忠诚客户的基础。&rdquo;多语言网站是企业有效的营销工具有能力对多数互联网用户用他们自己的语言进行沟通，这不仅仅意味着销售的增加，更可贵的是在当地市场建立起有关您的品牌、服务和产品的知晓。<br />\r\n	建设多语言网站是一个非常伟大的计划，因为它很可能是企业进行市场营销，抓住新的用户，建立与新的客户关系和赋予企业品牌一个国际形象的最有效方式。<br />\r\n	多语言网站能为企业带来新的顾客<br />\r\n	通过把您的多语言网站暴露在各个国家，地区潜在的顾客面前，自然而然地您会获得这些本国语用户的注意。</p>\r\n<p>\r\n	多语言网站能够为企业增加销售<br />\r\n	在网站上每增加一种语言都有可能潜在的提高一倍的销售额。即便只把网站建成只包含有西班牙语，法语，德语和意大利语这四种世界主要语言的网站，其销售额也有可能潜在的提升4倍。这是一种较少见的方式利用如此小的投资获得如此大的效果。<br />\r\n	多语言网站能够传达以顾客为中心的服务意识<br />\r\n	您的多语言网站显示出您为顾客思考。您以顾客为中心的思想及关爱顾客的努力将得到顾客的感激，因为您的这份额外的工作，他们将会更多的倾向于惠顾您的企业。<br />\r\n	&nbsp;</p>\r\n<p>\r\n	多语言网站能够获得更多的信任<br />\r\n	许多通过互联网执行的交易往往由于彼此并不熟悉相互的语言而产生不同文化间的信任问题。提供给顾客多语言的选择帮助他们感到安全，确切地清楚他们在如何交易，与谁交易。<br />\r\n	多语言网站帮助克服文化上的敏感<br />\r\n	一个经过恰当设计的多语言网站，通过使用目标市场的本土语能够克服潜在的文化障碍。因为多语言网站自动为客户创造了&ldquo;文化舒适区&rdquo;，使他们能够自如地导航，了解网站信息，并与您展开互动。<br />\r\n	多语言网站能够有效打击竞争者<br />\r\n	获得竞争优势需要在当今的环境中跳出思维的框架。许多企业试图把自己与竞争者区别出来。观察您的竞争者，如果他们有多语种网站为什么您没有呢？假若他们没有，为什么不在他们之前主导这个市场首先建立你公司的品牌呢？<br />\r\n	&nbsp;</p>\r\n<p>\r\n	多语言网站展示企业的国际性风范<br />\r\n	一个多语种网站展示您的思想，经营及国际性的业务流程。国际性企业形象及行业领导地位由此树立多语言网站帮助面向不同地域国家的查寻引擎<br />\r\n	搜索引擎会带着人们来到您的站点。然而在一些国家和地区有他们自己受欢迎的搜索引擎，主要是这些搜索引擎依据母语的使用习惯来工作，适应了人们的需要，所以获得了成功。这类搜索引擎引擎是开启本地市场的钥匙，除此之外，除非他们能够使用一种特定的语言(比如英语)否则很难找到您。</p>\r\n<p>\r\n	另外，许多关键字搜索引擎，尤其是Google，在多语言开发方面能力优异。拥有多语言页面的网站能够最大限度的保障您的网站能够被众多搜索引擎检索并展示。事务总是在不断地转移和变化。当前多语言网站仍处在早期阶段，许多跨国公司使用多语言网站来巩固其国际地位。然而，接下来的影响将自然地发生，多语言网站将成为互联网存在的主要部分。不管企业是选择现在或将来，这都是网站建设的唯一选择。</p>\r\n','2','16','0','0','0','0','','','1','admin','0','2011-05-19 09:59:58','2011-05-19 09:59:58','0','0','','cn');
INSERT INTO met_news VALUES('7','关于落实对已注册国内域名开展实名制清查的紧急通知','关于落实对已注册国内域名开展实名制清查的紧急通知','关于落实对已注册国内域名开展实名制清查的紧急通知','<p>\r\n	尊敬的用户:<br />\r\n	&nbsp;<br />\r\n	&nbsp;&nbsp;&nbsp; 您好!</p>\r\n<p>\r\n	&nbsp;&nbsp;&nbsp; 为了贯彻执行工业和信息化部发出的《工业和信息化部关于进一步深入整治手机淫秽色情专项行动工作方案》(工信部电管[2009]672号文件)的精神,同时切实落实CNNIC在近日下发的《关于对已注册域名开展实名制清查的通知》,要求严格落实域名注册申请者应提交真实、准确、完整的域名注册信息的规定,从即日起,将对2009年12月14日上午9时前注册成功的国内域名开展全面的清查,以确保域名注册信息的真实性、准确性、完整性。具体清查工作安排如下:</p>\r\n<p>\r\n	请在2010年1月31日前将域名持有人身份证明材料提交到注册局进行审核:</p>\r\n<p>\r\n	A. 域名持有者为法人组织的,应当提交组织机构代码证(扫描件)、注册联系人身份证(扫描件,二代身份证需要同时提交证件的正反面内容,请将正反面扫描在同一张纸上)。</p>\r\n<p>\r\n	B. 域名持有者为个人的,应当提交注册联系人身份证(扫描件),请注意书面身份证明材料必须与域名注册信息一致。</p>\r\n<p>\r\n	为了方便您提供以上材料,现对于所有2009年12月14日前已注册的国内域名,登录到域名所有人核实系统,&gt;请使用您的域名以及域名管理密码(请注意此密码可以在我公司的域名管理里查询为:核实登记管理密码 )登录<a href=\"http://sh.xinnet.com\">http://sh.xinnet.com</a>平台补全,确认并提交您域名的相关材料。</p>\r\n<p>\r\n	域名注册信息真实、准确、完整是打击传播淫秽低俗信息、垃圾邮件或网络欺诈等违法不良应用行为的重要手段。同时,域名注册信息作为域名权益转移、变更的权利信息凭证,也是域名持有者合法权益得到保护的前提和重要依据。我司将严格落实关于域名注册信息真实性、准确性和完整性的审核工作,敬请用户支持配合,谢谢!</p>\r\n<p>\r\n	对于在2010年1月31日前未提交相关书面材料的国内域名,将会暂停域名解析!</p>\r\n<p>\r\n	请广大用户对此工作务必给予重视!感谢您的大力支持与配合!</p>\r\n<p>\r\n	&nbsp;</p>\r\n<p>\r\n	米拓信息<br />\r\n	2010年1月18日</p>\r\n','2','17','0','0','0','0','','','0','admin','0','2011-05-19 10:01:29','2011-05-19 10:01:29','0','0','','cn');
INSERT INTO met_news VALUES('8','怎么添加网站统计代码？','怎么添加网站统计代码？','怎么添加网站统计代码？','<p>\r\n	<strong>百度统计添加方法：</strong><br />\r\n	1. 登录FTP，打开系统根目录下templates/对应模板名称/foot.html文件<br />\r\n	2. 然后在&lt;/body&gt;前将百度统计的代码粘贴。<br />\r\n	3. 然后重新生成静态页面（如开启了静态页面），即可生效。<br />\r\n	<br />\r\n	<strong>站长统计代码添加方法（其它统计代码也可按此方式添加）：</strong><br />\r\n	1.将站长统计代码复制到：后台--系统配置--底部信息--第三方代码 粘贴并提交。<br />\r\n	2.然后重新生成静态页面（如开启了静态页面），即可生效。<br />\r\n	&nbsp;</p>\r\n','2','17','0','0','0','0','','','0','admin','0','2011-05-19 10:02:25','2011-05-19 10:02:25','0','0','','cn');
INSERT INTO met_news VALUES('9','网站标题文字怎么修改？','网站标题文字怎么修改？','网站标题文字怎么修改？','<p>\r\n	MetInfo网站标题文字由三部分组成：<br />\r\n	1、优化推广文字，如&rdquo;MetInfo企业网站管理系统|企业网站建设|企业网站推广&ldquo;，修改路径：优化推广=》SEO参数配置=》网站标题关键词，此部分可以留空，当留空时网站标题将只显示网站名称；<br />\r\n	2、网站名称，如&rdquo;米拓信息&ldquo;，修改路径：系统配置=》基本信息=》网站名称<br />\r\n	3、优化推广设置中可以设置标题构成形式，还可以在编辑对应栏目的时候给栏目设置一个单独的页面标题。</p>\r\n','2','17','0','0','0','0','','','0','admin','0','2011-05-19 10:04:31','2011-05-19 10:04:31','0','0','','cn');
INSERT INTO met_news VALUES('10','反馈留言不能转发到指定邮箱的解决办法','反馈留言不能转发到指定邮箱的解决办法','反馈留言不能转发到指定邮箱的解决办法\r\n','<p>\r\n	<strong>反馈留言不能转发到指定邮箱的解决办法有以下几个：</strong><br />\r\n	1、后台--反馈留言--对应反馈栏目名称--参数配置&nbsp;&nbsp;查看&ldquo;反馈邮件接收邮箱&rdquo;和&ldquo;信息接收方式&rdquo;是否配置正确。<br />\r\n	2、后台--系统配置--基本信息--系统邮箱配置 查看是否配置正确，即便是觉得配置没问题，也请用outlook或foxmail测试是否能够通过这样的设置正常的收发邮件。<strong>99%的邮件不能发送问题就 是因为系统邮箱没配置好</strong>。<br />\r\n	3、上面的系统邮箱配置还需要注意一个情况，如新浪、QQ、126等邮箱使用smtp服务器都需要先开启smtp相关服务，具体可以登录对应的邮箱查看开 启方式。如果没开启，则无法通过outlook或foxmail正常收发邮件。<br />\r\n	4、<a class=\"seolabel\" href=\"http://idc.metinfo.cn/\" target=\"_blank\" title=\"空间\">空间</a>的特殊性，如godaddy<a class=\"seolabel\" href=\"http://idc.metinfo.cn/\" target=\"_blank\" title=\"空间\">空间</a>只能用godaddy<a class=\"seolabel\" href=\"http://idc.metinfo.cn/\" target=\"_blank\" title=\"空间\">空间</a>自己配置的邮箱才能够正常通过smtp收发邮件，而且仅能发送到同一类godaddy的 邮箱里，另如果<a class=\"seolabel\" href=\"http://idc.metinfo.cn/\" target=\"_blank\" title=\"空间\">空间</a>不支持收发邮件（这样的情况很少），建议咨询<a class=\"seolabel\" href=\"http://idc.metinfo.cn/\" target=\"_blank\" title=\"空间\">空间</a>商（米拓<a class=\"seolabel\" href=\"http://idc.metinfo.cn/\" target=\"_blank\" title=\"空间\">空间</a>均支持收发邮件）。<br />\r\n	&nbsp;</p>\r\n','2','17','0','0','0','0','','','1','admin','0','2011-05-19 10:07:17','2011-05-19 10:07:17','0','0','','cn');

INSERT INTO met_online VALUES('1','咨询销售','1','1302730113','metinfo@metinfo.cn','','','','cn');
INSERT INTO met_online VALUES('2','咨询销售','2','348468810','','metinfo','','','cn');
INSERT INTO met_online VALUES('3','空间域名','3','426507856','','metinfo','metinfo','','cn');
INSERT INTO met_online VALUES('4','合作加盟','4','909059761','sales@metinfo.cn','','','','cn');

INSERT INTO met_otherinfo VALUES('2','','','','','','','','','','<p>\r\n	<strong>此段文字请在后台-系统配置-备用字段中修改</strong><br />\r\n	长沙米拓信息技术有限公司<br />\r\n	电&nbsp; 话：0731-87133078 88920794<br />\r\n	手&nbsp; 机：13888888888<br />\r\n	Q&nbsp;&nbsp;&nbsp; Q：426507856 348468810<br />\r\n	邮&nbsp; 编：410205<br />\r\n	Email：sales@metinfo.cn<br />\r\n	网&nbsp;&nbsp;址：<a href=\"http://www.MetInfo.cn\"><span style=\"color: #ff0000\">www.MetInfo.cn</span></a></p>\r\n','','','','','','','','','cn');

INSERT INTO met_parameter VALUES('1','反馈主题','1','2','0','1','13','8','cn');
INSERT INTO met_parameter VALUES('2','姓名','2','1','0','1','13','8','cn');
INSERT INTO met_parameter VALUES('3','职务','3','1','0','0','13','8','cn');
INSERT INTO met_parameter VALUES('4','Email','4','1','0','1','13','8','cn');
INSERT INTO met_parameter VALUES('5','联系电话','5','1','0','0','13','8','cn');
INSERT INTO met_parameter VALUES('6','单位名称','6','1','0','0','13','8','cn');
INSERT INTO met_parameter VALUES('7','省份','7','2','0','0','13','8','cn');
INSERT INTO met_parameter VALUES('8','详细地址','8','1','0','0','13','8','cn');
INSERT INTO met_parameter VALUES('9','信息描述','9','3','0','0','13','8','cn');
INSERT INTO met_parameter VALUES('10','您是怎么找到我们的','10','4','0','0','13','8','cn');
INSERT INTO met_parameter VALUES('11','姓名','1','1','0','1','0','6','cn');
INSERT INTO met_parameter VALUES('12','性别','2','6','0','0','0','6','cn');
INSERT INTO met_parameter VALUES('13','出生年月','3','1','0','0','0','6','cn');
INSERT INTO met_parameter VALUES('14','籍贯','4','1','0','0','0','6','cn');
INSERT INTO met_parameter VALUES('15','联系电话','5','1','0','0','0','6','cn');
INSERT INTO met_parameter VALUES('16','邮编','6','1','0','0','0','6','cn');
INSERT INTO met_parameter VALUES('17','E–mail','7','1','0','1','0','6','cn');
INSERT INTO met_parameter VALUES('18','学历','8','1','0','0','0','6','cn');
INSERT INTO met_parameter VALUES('19','专业','9','1','0','0','0','6','cn');
INSERT INTO met_parameter VALUES('20','学校','10','1','0','0','0','6','cn');
INSERT INTO met_parameter VALUES('21','通讯地址','11','1','0','0','0','6','cn');
INSERT INTO met_parameter VALUES('22','所获奖项','12','3','0','0','0','6','cn');
INSERT INTO met_parameter VALUES('23','工作经历','13','3','0','0','0','6','cn');
INSERT INTO met_parameter VALUES('24','业余爱好','14','3','0','0','0','6','cn');
INSERT INTO met_parameter VALUES('25','照片','16','5','0','0','0','6','cn');
INSERT INTO met_parameter VALUES('26','型号','1','1','0','0','0','3','cn');
INSERT INTO met_parameter VALUES('27','品牌','2','6','0','1','0','3','cn');
INSERT INTO met_parameter VALUES('28','价格','3','1','1','0','0','3','cn');

INSERT INTO met_plist VALUES('1','1','26','示例产品','cn','','3');
INSERT INTO met_plist VALUES('2','1','27','品牌一','cn','','3');
INSERT INTO met_plist VALUES('3','1','28','￥18888','cn','','3');
INSERT INTO met_plist VALUES('4','2','26','示例产品','cn','','3');
INSERT INTO met_plist VALUES('5','2','27','品牌一','cn','','3');
INSERT INTO met_plist VALUES('6','2','28','￥9999','cn','','3');
INSERT INTO met_plist VALUES('7','3','26','示例产品','cn','','3');
INSERT INTO met_plist VALUES('8','3','27','品牌二','cn','','3');
INSERT INTO met_plist VALUES('9','3','28','￥6666','cn','','3');
INSERT INTO met_plist VALUES('10','4','26','示例产品','cn','','3');
INSERT INTO met_plist VALUES('11','4','27','品牌二','cn','','3');
INSERT INTO met_plist VALUES('12','4','28','￥5000000','cn','','3');
INSERT INTO met_plist VALUES('13','5','26','示例产品','cn','','3');
INSERT INTO met_plist VALUES('14','5','27','品牌二','cn','','3');
INSERT INTO met_plist VALUES('15','5','28','￥888888','cn','','3');
INSERT INTO met_plist VALUES('16','6','26','示例产品','cn','','3');
INSERT INTO met_plist VALUES('17','6','27','品牌三','cn','','3');
INSERT INTO met_plist VALUES('18','6','28','￥7654','cn','','3');
INSERT INTO met_plist VALUES('19','7','26','示例产品','cn','','3');
INSERT INTO met_plist VALUES('20','7','27','品牌三','cn','','3');
INSERT INTO met_plist VALUES('21','7','28','￥3666','cn','','3');
INSERT INTO met_plist VALUES('22','8','26','示例产品','cn','','3');
INSERT INTO met_plist VALUES('23','8','27','品牌一','cn','','3');
INSERT INTO met_plist VALUES('24','8','28','￥33333','cn','','3');


INSERT INTO met_product VALUES('1','示例产品一','示例产品一','示例产品一','<p>\r\n	示例产品一</p>\r\n','3','18','0','1','0','0','../upload/201105/1305776593.jpg','../upload/201105/thumb/1305776593.jpg','','0','5','2011-05-19 15:28:31','2011-05-19 11:24:39','admin','0','0','','cn','','','','','','','','','');
INSERT INTO met_product VALUES('2','示例产品二','示例产品一','示例产品一','<p>\r\n	示例产品一</p>\r\n','3','19','28','2','0','0','../upload/201105/1305776868.jpg','../upload/201105/thumb/1305776868.jpg','','1','1','2011-05-19 15:28:41','2011-05-19 11:24:39','admin','0','0','','cn','','','','','','','','','');
INSERT INTO met_product VALUES('3','示例产品三','示例产品三','示例产品三','<p>\r\n	示例产品三<span style=\"display: none\">&nbsp;，这里可，以，的</span></p>\r\n<p>\r\n	这里可以输入文字信息！</p>\r\n','3','20','0','3','0','0','../upload/201105/1305777180.jpg','../upload/201105/thumb/1305777180.jpg','','1','4','2011-05-19 15:29:24','2011-05-19 11:24:39','admin','0','0','','cn','','','','','','','','','');
INSERT INTO met_product VALUES('4','示例产品四','示例产品四','示例产品四','<p>\r\n	示例产品四</p>\r\n','3','21','0','4','0','0','../upload/201105/1305777900.jpg','../upload/201105/thumb/1305777900.jpg','','0','1','2011-05-19 15:29:53','2011-05-19 11:24:39','admin','0','0','','cn','','','','','','','','','');
INSERT INTO met_product VALUES('5','示例产品五','示例产品一','示例产品一','<p>\r\n	示例产品一</p>\r\n','3','22','0','5','0','0','../upload/201105/1305777923.jpg','../upload/201105/thumb/1305777923.jpg','','0','1','2011-05-19 15:30:29','2011-05-19 11:24:39','admin','0','0','','cn','','','','','','','','','');
INSERT INTO met_product VALUES('6','示例产品六','示例产品六','示例产品六','<p>\r\n	示例产品六</p>\r\n','3','23','0','6','0','0','../upload/201105/1305780990.jpg','../upload/201105/thumb/1305780990.jpg','','1','2','2011-05-19 15:31:04','2011-05-19 11:24:39','admin','0','0','','cn','','','','','','','','','');
INSERT INTO met_product VALUES('7','示例产品七','示例产品七','示例产品七','<p>\r\n	示例产品七</p>\r\n','3','24','0','7','0','0','../upload/201105/1305782353.jpg','../upload/201105/thumb/1305782353.jpg','','1','8','2011-05-19 15:31:24','2011-05-19 11:24:39','admin','0','0','','cn','','','','','','','','','');
INSERT INTO met_product VALUES('8','示例产品八','示例产品八','示例产品八','<p>\r\n	示例产品八</p>\r\n','3','25','0','8','0','0','../upload/201105/1305782954.jpg','../upload/201105/thumb/1305782954.jpg','','0','3','2011-05-19 15:31:49','2011-05-19 11:24:39','admin','0','0','','cn','','','','','','','','','');