INSERT INTO met_language VALUES (null, 'system', '系统参数', 0, 1, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'searchall', '整站搜索', 0, 15, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'search', '搜索', 0, 16, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'home', '网站首页', 0, 17, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'error', '读取数据错误', 0, 18, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'success', '操作成功!', 0, 19, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Info1', 'MetInfo企业网站管理系统', 0, 20, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Info2', '企业建站程序', 0, 21, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Info3', '企业网站建设', 0, 22, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Colunm', '栏目名称', 0, 23, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Title', '标题', 0, 24, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Content', '内容', 0, 25, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Hits', '点击次数', 0, 26, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'UpdateTime', '更新时间', 0, 27, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Detail', '查看详细', 0, 28, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Close', '关闭', 0, 29, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Online', '在线交流', 0, 30, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Online_tips', '点击可隐藏', 0, 31, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Noinfo', '没有了', 0, 32, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Buy', '购买反馈', 0, 33, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'ProductTitle', '产品名称', 0, 34, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'ImgTitle', '图片名称', 0, 35, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'BigPicture', '查看大图', 0, 36, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'ProductSearch', '产品搜索', 0, 37, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Nolimit', '不限', 0, 38, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'imgSearch', '图片搜索', 0, 39, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'displayimg', '展示图片', 0, 40, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'defualt', '默认', 0, 41, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'logininformation', '登录信息提示', 0, 2, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'membercode', '验证码错误！', 0, 1, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'membernameno', '会员账号不存在！', 0, 2, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberpassno', '密码错误！', 0, 3, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'access', '您没有阅读该信息的权限！', 0, 4, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'login', '登录', 0, 5, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'register', '注册', 0, 6, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'downloadaccess', '您没有下载此文件的权限！', 0, 7, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'paging', '分页', 0, 3, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'PageTotal', '共', 0, 1, 3, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Page', '页', 0, 2, 3, 0, 'cn');
INSERT INTO met_language VALUES (null, 'PageLocation', '当前第', 0, 3, 3, 0, 'cn');
INSERT INTO met_language VALUES (null, 'PageHome', '首页', 0, 4, 3, 0, 'cn');
INSERT INTO met_language VALUES (null, 'PageEnd', '末页', 0, 5, 3, 0, 'cn');
INSERT INTO met_language VALUES (null, 'PagePre', '上一页', 0, 6, 3, 0, 'cn');
INSERT INTO met_language VALUES (null, 'PageNext', '下一页', 0, 7, 3, 0, 'cn');
INSERT INTO met_language VALUES (null, 'PageGo', '转至第', 0, 8, 3, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Previous', '上一条', 0, 9, 3, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Next', '下一条', 0, 10, 3, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Total', '条记录', 0, 11, 3, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Pagenum', '页次', 0, 12, 3, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Pagenum1', '第', 0, 13, 3, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Pagenum2', '页', 0, 14, 3, 0, 'cn');
INSERT INTO met_language VALUES (null, 'membership', '会员信息', 0, 4, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberclose', '会员功能尚未开启！', 0, 1, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberLogin', '会员登录', 0, 2, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberRegisterName', '请输入用户名', 0, 3, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberPassword', '请输入密码', 0, 4, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberCookie', '请先开启浏览器的COOKIE功能！', 0, 5, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberName', '会员名', 0, 6, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberPs', '密 码', 0, 7, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberImgCode', '验证码', 0, 8, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberTip1', '看不清？点击更换验证码', 0, 9, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberTip2', '记住我的登录信息', 0, 10, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberGo', '登录', 0, 11, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberRegister', '立即注册', 0, 12, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberReset', '重填', 0, 13, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberForget', '忘记密码？', 0, 14, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberIndex1', '用户管理中心', 0, 15, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberIndex2', '欢迎您！', 0, 16, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberIndex3', '会员中心', 0, 17, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberIndex4', '修改基本信息', 0, 18, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberIndex5', '管理反馈信息', 0, 19, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberIndex6', '管理留言信息', 0, 20, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberIndex7', '管理简历信息', 0, 21, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberIndex8', '会员控制面板', 0, 22, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberIndex9', '个人信息', 0, 23, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberIndex10', '退出登录', 0, 24, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberIndex11', '共', 0, 25, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberIndex12', '条信息', 0, 26, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberIndex13', '已读', 0, 27, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberIndex14', '未读', 0, 28, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberIndex15', '简历投递管理', 0, 29, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberIndex16', '会员公告', 0, 30, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicTitle', '查看基本信息', 0, 31, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicUserName', '用户名', 0, 32, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicReadlName', '姓名', 0, 33, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicSex', '性别', 0, 34, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicMan', '男', 0, 35, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicWoman', '女', 0, 36, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicTel', '联系电话', 0, 37, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicCell', '手机', 0, 38, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicTaoBao', '淘宝', 0, 39, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicLoginNum', '登录次数', 0, 40, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicLastLogin', '最后登录时间', 0, 41, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicLastIP', '最后登录IP', 0, 42, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicRegisterTime', '帐号注册时间', 0, 43, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicIntro', '会员简介', 0, 44, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicCompanyName', '公司名称', 0, 45, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicCompanyFax', '公司传真', 0, 46, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicCompanyCode', '公司邮政编码', 0, 47, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicCompanyAddress', '公司联系地址', 0, 48, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicCompanyWebsite', '公司网址', 0, 49, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicType', '会员类型', 0, 50, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicType1', '普通会员', 0, 51, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicType2', '代理商', 0, 52, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicType3', '管理员', 0, 53, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'membereditorPs', '登录密码', 0, 54, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'membereditorPs1', '密码确认', 0, 55, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'membereditorTip', '不修改请留空', 0, 56, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'membereditorTip1', '用于找回密码', 0, 57, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberReg', '会员注册', 0, 58, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberEdit', '编辑', 0, 59, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberDetail', '查看', 0, 60, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberShowAll', '查看全部', 0, 61, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberFeedbackName', '反馈信息标题', 0, 62, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberAddTime', '提交时间', 0, 63, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberOperate', '操作', 0, 64, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberFile', '已上传的附件', 0, 65, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberinfo', '留言内容', 0, 66, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberReply', '是否回复', 0, 67, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberContent', '留言内容', 0, 68, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'messageeditorName', '姓名', 0, 69, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'messageeditorTel', '电话', 0, 70, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'messageeditorContact', '其他联系方式', 0, 71, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'messageeditorContent', '留言内容', 0, 72, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'messageeditorTime', '留言提交时间', 0, 73, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'messageeditorReply', '管理员回复留言', 0, 74, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'cvTip4', '职位已经被删除', 0, 75, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberPosition', '应聘职位', 0, 76, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberModifyCV', '修改简历', 0, 77, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberModifyMS', '修改留言', 0, 78, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberModifyFD', '修改反馈', 0, 79, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberShowFD', '查看反馈', 0, 80, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberShowMS', '查看留言', 0, 81, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberShowCV', '查看简历', 0, 82, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'getNotice', '会员找回密码', 0, 83, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'NewPassJS', '新密码', 0, 84, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'NewPassJS1', '再输入一次', 0, 85, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'NewPassJS2', '两次输入密码不一致', 0, 86, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'NoidJS', '没有此用户', 0, 87, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'NoidJS1', '没有此用户或邮箱地址不正确', 0, 88, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'getTip1', '您的密码重置请求已经得到验证。请点击以下链接输入您的新密码：', 0, 89, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'getTip2', '取回密码的方法已经通过 Email 发送到您的信箱中。请在 3 天之内到网站修改您的密码。', 0, 90, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'getTip3', '您提交的找回密码邮件发送失败！请联系网站管理员！。', 0, 91, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'getTip4', '请输入下面的信息，以帮助您快速找回密码。', 0, 92, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'getTip5', '密码找回', 0, 93, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'getTip6', '无法调用Jmail组件', 0, 94, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'getTip7', '请输入新密码，以后请牢记您的密码。', 0, 95, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'getTip8', '该链接已失效！', 0, 96, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'getOK', '发送成功', 0, 97, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'getFail', '发送失败', 0, 98, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'membernodo', '该用户尚未激活，请即时与管理员联系!', 0, 99, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'hello', '您好！', 0, 100, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'fileupload', '文件上传', 0, 5, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'fileOK', '文件上传成功', 0, 1, 5, 0, 'cn');
INSERT INTO met_language VALUES (null, 'fileError1', '上传的文件超过了 php.ini 中 upload_max_filesize 选项限制的值。', 0, 2, 5, 0, 'cn');
INSERT INTO met_language VALUES (null, 'fileError2', '上传文件的大小超过了 HTML 表单中 MAX_FILE_SIZE 选项指定的值。', 0, 3, 5, 0, 'cn');
INSERT INTO met_language VALUES (null, 'fileError3', '文件只有部分被上传。', 0, 4, 5, 0, 'cn');
INSERT INTO met_language VALUES (null, 'fileError4', '没有文件被上传。', 0, 5, 5, 0, 'cn');
INSERT INTO met_language VALUES (null, 'jstip', 'js提示', 0, 6, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js1', '操作失败！', 0, 1, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js2', '管理员身份登录！', 0, 2, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js3', '抱歉，注册功能暂时关闭！', 0, 3, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js4', '无法激活此用户,请与管理员联系！', 0, 4, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js5', '已成功激活,请登录！', 0, 5, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js6', '用户名输入有误!', 0, 6, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js7', '用户名不能小于3位', 0, 7, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js8', '密码应大于等于6位！', 0, 8, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js9', '请再次输入用户密码！', 0, 9, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js10', '两次密码输入不一致', 0, 10, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js11', '请输入公司名称！', 0, 11, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js12', '请输入您的Email！', 0, 12, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js13', 'Email地址不正确！', 0, 13, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js14', '请输入验证码！', 0, 14, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js15', '此用户名已经被使用', 0, 15, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js16', '会员激活', 0, 16, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js17', '会员激活方式：', 0, 17, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js18', '请您点击', 0, 18, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js19', '完成会员账号激活！', 0, 19, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js20', '激活邮件已发生到您注册的邮箱中，请即时激活您的会员身份!', 0, 20, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js21', '操作成功!', 0, 21, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js22', '指定的路径不可写，或者没有此路径!', 0, 22, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js23', '文件格式不允许上传。', 0, 23, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js24', '管理员已阅读，没有权限修改！', 0, 24, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js25', '注册成功，待管理员审核即可登录控制面板！', 0, 25, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'other', '其他', 0, 7, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'YES', '是', 0, 1, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'NO', '否', 0, 2, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Article', '相关文章', 0, 3, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Printing', '打印此页', 0, 4, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Times', '次', 0, 5, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Feedback', '购买反馈', 0, 6, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'FileSize', '文件大小', 0, 7, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Download', '点击下载', 0, 8, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Position', '招聘职位', 0, 9, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'PersonNumber', '招聘人数', 0, 10, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'WorkPlace', '工作地点', 0, 11, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'AddDate', '发布日期', 0, 12, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Deal', '工资待遇', 0, 13, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Validity', '有效期', 0, 14, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'JobDescription', '职位描述', 0, 15, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Submit', '提交信息', 0, 16, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Reset', '重新填写', 0, 17, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'AdvancedSearch', '高级搜索', 0, 18, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Keywords', '关键字', 0, 19, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'AllBigclass', '所有一级栏目', 0, 20, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'AllSmallclass', '所有二级栏目', 0, 21, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'AllThirdclass', '所有三级栏目', 0, 22, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'And', '和', 0, 23, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'LinkType', '链接类型', 0, 33, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'TextLink', '文字链接', 0, 34, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'PictureLink', '图片链接', 0, 35, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Contact', '联系方式', 0, 36, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'ApplyLink', '申请友情链接', 0, 37, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'ApplyLinkNO', '没有开启友情链接申请', 0, 38, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'SubmitInfo', '提交留言', 0, 39, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Publish', '发表于', 0, 40, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'SubmitContent', '留言内容', 0, 41, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Reply', '管理员回复', 0, 42, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'ReadInfo', '查看留言', 0, 43, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Name', '姓名', 0, 44, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Phone', '电话', 0, 45, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Email', 'Email', 0, 46, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'OtherContact', '其他联系方式', 0, 47, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Info5', '如QQ、MSN等', 0, 48, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Feedback1', '请不要在', 0, 49, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Feedback2', '秒内重复提交信息，谢谢合作！', 0, 50, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Feedback3', '反馈信息中不能包含', 0, 51, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Feedback5', '反馈已经被关闭', 0, 52, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'FeedbackProduct', '反馈产品', 0, 53, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'IP', '来源IP', 0, 54, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'AddTime', '提交时间', 0, 55, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'SourcePage', '来源页面', 0, 56, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Feedback4', '反馈信息已成功提交，谢谢！', 0, 57, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Choice', '请选择', 0, 58, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Empty', '不能为空', 0, 59, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'LinkInfo1', '您的网站已成功提交，谢谢！', 0, 60, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'MessageInfo1', '在线留言', 0, 63, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'MessageInfo2', '您的留言已成功提交，谢谢！', 0, 64, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'MessageInfo3', '姓名不能为空', 0, 65, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'MessageInfo4', '留言信息不能为空', 0, 66, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'MessageInfo5', '浏览器不支持此功能，请手动设置！', 0, 67, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'messageadd', '提交留言', 0, 68, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'messageview', '查看留言', 0, 69, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'SearchInfo', '在线搜索', 0, 70, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'SearchInfo1', '请输入搜索关键词！', 0, 71, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'SearchInfo2', '全站搜索', 0, 72, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'SearchInfo3', '没有含有', 0, 73, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'SearchInfo4', '的信息内容', 0, 74, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Job1', '不限', 0, 75, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Job2', '天', 0, 76, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'several', '若干', 0, 77, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'cvtitle', '在线应聘', 0, 78, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'cv', '查看简历', 0, 79, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'cv2', '申请贵公司', 0, 80, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'feedbackonline', '在线反馈', 0, 81, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'messageonline', '在线留言', 0, 82, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'htmcreate', '生成', 0, 83, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'htmsuccess', '成功!', 0, 84, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'htmpermission', '没有权限！', 0, 85, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'metwapok', '没有开启WAP功能！', 0, 86, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'wap', '手机版', 0, 87, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'smstips66', '余额不足', 0, 88, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'smstips67', '短信内容太长，最多350个字', 0, 89, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'smstips68', '手机号码太多，最多800个号码', 0, 90, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'smstips69', '号码不符合规则', 0, 91, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'smstips70', '发送成功(有延迟)', 0, 92, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'smstips71', '异常操作，余额不足', 0, 93, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'smstips72', '余额不足', 0, 94, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'smstips73', '短信内容和手机号码不能为空', 0, 95, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'smstips74', '发送密码错误', 0, 96, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'smstips75', '网站无法访问', 0, 97, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'smstips76', '服务器无响应', 0, 98, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'detailtxt', '详细描述', 0, 99, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'showdownload1', '更新时间', 0, 100, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'showdownload2', '文件下载', 0, 101, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'showdownload3', '点击下载', 0, 102, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'initext1', '立即搜索', 0, 42, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'saechplaceholder', '请输入关键词', 0, 43, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'drxtop', '顶', 0, 44, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'drxhot', '热', 0, 45, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'drxnew', '新', 0, 46, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'colmnmore', '更多分类', 0, 47, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'fliptext1', '查看更多', 0, 48, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'fliptext2', '加载中...', 0, 49, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'downloadtext1', '下载', 0, 50, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'downloadtext2', '次访问', 0, 51, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'jobtext1', '人', 0, 52, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'foottext1', '电话', 0, 53, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'foottext2', '地图', 0, 54, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'foottext3', '留言', 0, 55, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'foottext4', '首页', 0, 56, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'foottext5', '电脑版', 0, 57, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'foottext6', '触屏版', 0, 58, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'navtext1', '导航栏目', 0, 59, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'nettext2', '文章内容', 0, 60, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'nettext3', '产品详情', 0, 61, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'nettext4', '资料详情', 0, 62, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'nettext5', '图片详情', 0, 63, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'nettext6', '职位详情', 0, 64, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'tagweb', '标签', 0, 66, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'formerror1', '请填写此字段。', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'formerror2', '请从这些选项中选择一个。', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'formerror3', '请输入正确的手机号码。', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'formerror4', '请输入正确的Email地址。', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'formerror5', '两次输入的密码不一致，请重新输入。', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'formerror6', '请输入至少&metinfo&个字符。', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'formerror7', '输入不能超过&metinfo&个字符。', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'formerror8', '输入的字符数必须在&metinfo&之间。', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'read', '阅读', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'switching_category', '切换类目', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js46', '不能重复', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailcheck', '邮箱验证', 0, 102, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailchecktips1', '感谢您的注册！激活链接已经发送到您的邮箱', 0, 103, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailchecktips2', '点击邮件里的链接即可激活账户', 0, 104, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailchecktips3', '还没收到确认邮件？', 0, 105, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailchecktips4', '尝试到广告邮件、垃圾邮件目录里找找看', 0, 106, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailchecktips5', '再次发送确认邮件', 0, 107, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'accsafe', '账号安全', 0, 108, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'resend', '重发', 0, 109, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'getmemberImgCode', '获取验证码', 0, 110, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'teluse', '手机号已被注册', 0, 111, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'telok', '请输入正确的手机号码', 0, 112, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'password', '密码', 0, 113, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'userhave', '用户名已存在', 0, 114, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailhave', '邮箱已被注册', 0, 115, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberemail', '邮箱', 0, 116, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberMoreInfo', '更多资料', 0, 117, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'select', '选择', 0, 118, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'acchave', '已有账号？', 0, 119, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'accpassword', '帐号密码', 0, 120, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'accsaftips1', '用于保护帐号信息和登录安全', 0, 121, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'modify', '修改', 0, 122, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'accemail', '邮箱绑定', 0, 123, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'accsaftips2', '邮箱绑定可以用于登录帐号，重置密码或其他安全验证', 0, 124, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'acctel', '手机绑定', 0, 125, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'accsaftips3', '手机绑定可以用于登录帐号，重置密码或其他安全验证', 0, 126, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'modifypassword', '密码修改', 0, 127, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'oldpassword', '原密码', 0, 128, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'newpassword', '新密码', 0, 129, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'confirm', '确定', 0, 130, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'cancel', '取消', 0, 131, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailaddress', '邮箱地址', 0, 132, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailuse', '邮箱已被绑定', 0, 133, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'telnum', '手机号码', 0, 134, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'teluse', '手机号码已被绑定', 0, 135, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'telok', '请输入正确的手机号码', 0, 136, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'modifyacctel', '修改手机绑定', 0, 137, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'modifyinfo', '保存资料', 0, 138, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailnow', '当前邮箱：', 0, 139, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'newemail', '新邮箱', 0, 140, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'submit', '提交', 0, 141, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'modifyaccemail', '修改绑定邮箱', 0, 142, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'resetpassword', '请重新设置密码', 0, 143, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'renewpassword', '重复密码', 0, 144, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'inputcode', '请输入验证码', 0, 145, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'next', '下一步', 0, 146, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'logintips', '用户名/邮箱/手机', 0, 147, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'otherlogin', '其它方式登录', 0, 148, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'logintips1', '没有账号？现在去注册', 0, 149, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'rehomepage', '返回首页', 0, 150, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'rememberImgCode', '重发验证码', 0, 150, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'relogin', '返回登录', 0, 151, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'getpasswordtips', '邮箱/手机', 0, 152, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'regclose', '注册功能已关闭', 0, 153, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'regfail', '注册失败', 0, 154, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'codetimeout', '验证码已超时', 0, 155, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'telcheckfail', '手机号码与短信验证号码不一致', 0, 156, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'regsuc', '注册成功！', 0, 157, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'activesuc', '激活成功，请登录！', 0, 158, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailvildtips1', '验证信息错误', 0, 159, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailvildtips2', '验证信息错误或已超时', 0, 160, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'telreg', '手机号已被注册', 0, 161, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Sendfrequent', '发送过于频繁，请稍后再试', 0, 162, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailsuc', '邮件发送成功！', 0, 163, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailfail', '邮件发送失败，请确认邮箱是否正确或联系网站管理人员解决。', 0, 164, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'modifysuc', '修改成功', 0, 165, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'binding', '绑定', 0, 166, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'notbound', '未绑定', 0, 167, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'accnotmodify', '帐号无法修改', 0, 168, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailsuclink', '邮件发送成功！请点击邮件里的验证链接完成操作！', 0, 169, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'bindingok', '绑定成功', 0, 170, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'opfail', '操作失败', 0, 171, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'modifypasswordsuc', '密码修改成功！', 0, 172, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'lodpasswordfail', '原密码错误', 0, 173, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'membererror1', '用户名或密码错误', 0, 174, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'membererror2', '请开启session！', 0, 175, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'membererror3', '授权失败', 0, 176, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'membererror4', '未知错误', 0, 177, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'membererror6', '账号未激活，请联系管理员', 0, 174, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailsucpass', '密码找回邮件已经发送至您的邮箱，点击邮件里的链接即可重设密码。', 0, 178, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailvildtips3', '请输入正确的邮箱或手机号码', 0, 179, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'membererror5', '发送失败！错误码：', 0, 180, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'noempty', '此项不能为空', 0, 181, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'usernamecheck', '用户名必须在2-30个字符之间', 0, 182, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'passwordcheck', '密码必须在6-30个字符之间', 0, 183, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'passwordsame', '两次密码输入不一致', 0, 184, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailcheck', '请输入正确的Email地址', 0, 184, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Previous_news', '上一篇', 0, 9, 3, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Next_news', '下一篇', 0, 10, 3, 0, 'cn');
INSERT INTO met_language VALUES (null, 'job_tips1_v6', '工作简历中不能包含', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'close', '关闭', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'error404', '404错误，页面不见了。。。', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'browserupdatetips', '你正在使用一个 <strong>过时</strong> 的浏览器。请 <a href=https://browsehappy.com/ target=_blank>升级您的浏览器</a>，以提高您的体验。', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'newFeedback', '您收到了新的反馈', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'opfailed', '操作失败', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'opsuccess', '操作成功', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'jobPrompt', '收到了新的简历', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'reMessage1', '您网站', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'feedbackPrompt', '收到了新的反馈信息', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'reMessage2', '，请尽快登录网站后台查看', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'messagePrompt', '收到了新的留言', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'formaterror', '格式错误', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'listcom', '推荐', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'listnew', '最新', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'listhot', '热门', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'listsales', '销量', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'weball', '全部', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'accsaftips4', '绑定用户证实身份信息', 0, 9, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'rnvalidate', '实名认证', 0, 9, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'notauthen', '未认证', 0, 9, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'authen', '已认证', 0, 9, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'realname', '真实姓名', 0, 9, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'idcode', '身份证号码', 0, 9, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'idvalidok', '实名认证成功', 0, 9, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'idvalidfailed', '实名认证失败', 0, 9, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'systips1', '您没有权限访问这个内容！请登录后访问！', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'systips2', '您所在用户组没有权限访问这个内容！', 0, 0, 0, 0, 'cn');

INSERT INTO met_language VALUES (null, 'usercheckok', '验证成功！', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'usereadinfo', '阅读权限值必需大于0', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'usersetprice', '请设置金额', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'userselectname', '选项卡', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'userwenxinclose', '微信登录功能已关闭', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'userwenboclose', '微博登录功能已关闭', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'userqqclose', 'QQ登录功能已关闭', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'userbuy', '购买', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'userbuylist', '订单', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'usesendcode', '验证码为', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'usesendcodeinfo', '请及时输入验证', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'feedbackinquiry', '在线询价', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'templatesusererror', '当前语言模板未配置或模板文件不存在', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'phonecode', '获取手机验证码', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'phonecodeerror', '手机验证码错误', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbuytitle', '付费升级会员组', 0, 0, 0, 0, 'cn');


INSERT INTO met_config VALUES (null, 'metconfig_weburl', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_webname', '网站名称', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_logo', '../upload/201801/1515549638.png', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_mobile_logo', '../upload/201807/1532137488.png', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_skin_user', 'metv6', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_big_wate', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_thumb_wate', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_wate_class', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_wate_img', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_wate_bigimg', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_thumb_kind', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_text_wate', 'MetInfo', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_text_size', '10', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_text_bigsize', '35', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_text_fonts', '../include/fonts/arial.ttf', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_text_color', '#000000', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_text_angle', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_watermark', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_img_style', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_img_x', '150', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_img_y', '150', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_newsimg_x', '400', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_newsimg_y', '400', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_productimg_x', '400', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_productimg_y', '400', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_imgs_x', '400', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_imgs_y', '400', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_keywords', '网站关键词', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_description', '网站描述，一般显示在搜索引擎搜索结果中的描述文字，用于介绍网站，吸引浏览者点击。', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_title_type', '2', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_seo', '<p>后台-营销-SEO-头部优化文字处修改</p>', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_tools_ok', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_alt', '图片关键词', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_atitle', '链接关键词', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_linkname', '某某公司网站', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_online_type', '4', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_footright', '我的网站 版权所有 2008-2014 湘ICP备8888888', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_footaddress', '本页面内容为网站演示数据，前台页面内容都可以在后台修改。', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_foottel', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_footother', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_foottext', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_footstat', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_product_list', '8', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_news_list', '8', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_download_list', '8', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_img_list', '8', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_job_list', '3', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_message_list', '10', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_search_list', '10', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_fd_fromname', '米拓信息', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_fd_smtp', '61.152.188.131', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_fd_usename', 'test@mail.metinfo.cn', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_fd_password', 'passwordhidden', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_skin_css', 'metinfo.css', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_autothumb_ok', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_use', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_register', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_idvalidate', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_idvalid_key', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_newsdays', '3', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_hot', '100', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_listtime', 'Y-m-d', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_contenttime', 'Y-m-d H:i:s', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_vecan', '4', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_membercontrol', '欢迎注册为【米拓信息】www.metinfo.cn会员，会员激活后您可以享受更多的专业服务！', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_pseudo', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_online_skin', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_online_color', '#1baadb', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_qq_type', '3', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_msn_type', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_taobao_type', '2', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_alibaba_type', '10', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_skype_type', '11', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_onlinetel', '<p>服务热线：<br/>000-000-0000</p>', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_addlinkopen', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_pageskin', '8', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_indexskin', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_urlblank', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_pnorder', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_hitsok', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_product_page', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_img_page', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_product_detail', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_img_detail', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_productdetail_x', '400', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_productdetail_y', '400', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_imgdetail_x', '900', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_imgdetail_y', '500', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_online_x', '10', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_online_y', '100', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_onlinenameok', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_file_format', 'rar|zip|sql|doc|pdf|jpg|xls|png|gif|mp3|jpeg|bmp|swf|flv|ico', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_file_maxsize', '8', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_memberlogin_code', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_login_code', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_webhtm', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_htmtype', 'html', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_htmpagename', '2', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_listhtmltype', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_htmlistname', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_htmway', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'index_news_no', '10', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'index_product_no', '10', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'index_download_no', '10', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'index_img_no', '2', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'index_job_no', '10', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'index_link_ok', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'index_link_img', '9999', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'index_link_text', '9999', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_pageclick', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_pagetime', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_pageprint', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_pageclose', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_deleteimg', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_columnshow', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_kzqie', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_cv_time', '120', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_cv_word', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_cv_type', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_cv_image', '32', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_cv_emtype', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_cv_to', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_tools_code', '<div class=\"bdsharebuttonbox\"><a href=\"#\" class=\"bds_more\" data-cmd=\"more\"></a><a href=\"#\" class=\"bds_qzone\" data-cmd=\"qzone\" title=\"分享到QQ空间\"></a><a href=\"#\" class=\"bds_tsina\" data-cmd=\"tsina\" title=\"分享到新浪微博\"></a><a href=\"#\" class=\"bds_tqq\" data-cmd=\"tqq\" title=\"分享到腾讯微博\"></a><a href=\"#\" class=\"bds_renren\" data-cmd=\"renren\" title=\"分享到人人网\"></a><a href=\"#\" class=\"bds_weixin\" data-cmd=\"weixin\" title=\"分享到微信\"></a></div><script>window._bd_share_config={\"common\":{\"bdSnsKey\":{},\"bdText\":\"\",\"bdMini\":\"2\",\"bdMiniList\":false,\"bdPic\":\"\",\"bdStyle\":\"1\",\"bdSize\":\"16\"},\"share\":{}};with(document)0[(getElementsByTagName(\"head\")[0]||body).appendChild(createElement(\"script\")).src=\"http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=\"+~(-new Date()/36e5)];</script>', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_cv_back', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_cv_title', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_cv_content', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_cv_email', '24', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'index_hadd_ok', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_hometitle', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_img_rename', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_index_content', '<div><img alt=\"\" src=\"upload/images/20120716_094159.jpg\" style=\"line-height: 2; margin: 8px; width: 196px; float: left; height: 209px;\" /></div><div style=\"padding-top:10px;\"><span style=\"font-size:14px;\"><strong>关于&ldquo;为合作伙伴创造价值&rdquo;</strong></span></div><div>米拓信息认为客户、供应商、公司股东、公司员工等一切和自身有合作关系的单位和个人都是自己的合作伙伴，并只有通过努力为合作伙伴创造价值，才能体现自身的价值并获得发展和成功。</div><div>&nbsp;</div><div><span style=\"font-size:14px;\"><strong>关于&ldquo;诚实、宽容、创新、服务&rdquo;</strong></span></div><div><span style=\"font-size:12px;\">米拓信息认为诚信是一切合作的基础，宽容是解决问题的前提，创新是发展事业的利器，服务是创造价值的根本。</span></div><div>&nbsp;</div>', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_fd_port', '25', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_fd_way', 'tls', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_headstat', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_automatic_upgrade', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_sitemap_auto', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_maplng', '112.947724', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_maplat', '28.147538', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_mapzoom', '15', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_maptitle', '演示公司名称', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_mapcontents', '地址：长沙市岳麓区#<br/>电话：0000-88888888 0000-8888888', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_dimensional_logo', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_menu_ok', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_menu_oks', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_menu_rgb', '#e9280c', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_menu_bg', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_menu_textbg', '#ffffff', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_wapshowtype', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_bannerpagetype', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_theme_preview', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_productTabname', '详细信息', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_productTabname_1', '规格参数', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_productTabname_2', '包装', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_productTabname_3', '选项卡四', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_productTabname_4', '选项卡五', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_productTabok', '3', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_htmlurl', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_defult_lang', '1', '0', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_headstat_mobile', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_footstat_mobile', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_weixin_appid', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_weixin_appsecret', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_weibo_appkey', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_weibo_appsecret', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_qq_appid', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_qq_appsecret', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_weixin_open', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_weibo_open', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_qq_open', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_weixin_gz_appid', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_weixin_gz_appsecret', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_bgcolor', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_bgimage', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_email_reg_title', '{webname} 会员中心 注册验证', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_email_reg_content', '<div style=\"width:500px;margin:20px auto;\"><div class=\"header clearfix\" style=\"font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; background-color: rgb(255, 255, 255);\"><a href=\"{weburl}\"><strong style=\"outline: none; cursor: pointer; color: rgb(30, 84, 148);\">{webname} 会员中心</strong></a></div><p>&nbsp;</p><div class=\"content\" style=\"font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; border: 1px solid rgb(233, 233, 233); margin: 2px 0px 0px; padding: 30px; background: none 0px 0px repeat scroll rgb(255, 255, 255);\"><p style=\"line-height: 23.7999992370605px;\">您好：</p><p style=\"line-height: 23.7999992370605px;\">这是您在 {webname} 会员中心 上的重要邮件, 功能是进行&nbsp;会员中心 注册验证, 请点击下面的连接完成验证</p><p style=\"line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); margin-top: 15px; margin-bottom: 25px; padding: 15px;\">请点击链接继续：{opurl}</p><p style=\"line-height: 23.7999992370605px;\">&nbsp;</p><p class=\"footer\" style=\"line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); padding-top: 6px; margin-top: 25px; color: rgb(131, 131, 131);\">请勿回复本邮件, 此邮箱未受监控, 您不会得到任何回复。<br/><br/><a href=\"{weburl}\"><strong style=\"outline: none; cursor: pointer; color: rgb(30, 84, 148);\">{webname}会员中心</strong></a></p></div></div>', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_email_password_title', '{webname} 会员中心 密码找回', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_email_password_content', '<div style=\"width:500px;margin:20px auto;\"><div class=\"header clearfix\" style=\"font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; background-color: rgb(255, 255, 255);\"><a href=\"{weburl}\"><strong style=\"outline: none; cursor: pointer; color: rgb(30, 84, 148);\">{webname} 会员中心</strong></a></div><p>&nbsp;</p><div class=\"content\" style=\"font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; border: 1px solid rgb(233, 233, 233); margin: 2px 0px 0px; padding: 30px; background: none 0px 0px repeat scroll rgb(255, 255, 255);\"><p style=\"line-height: 23.7999992370605px;\">您好：</p><p style=\"line-height: 23.7999992370605px;\">这是您在 {webname} 会员中心 上的重要邮件, 功能是进行&nbsp;会员中心 密码找回, 请点击下面的连接完成验证</p><p style=\"line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); margin-top: 15px; margin-bottom: 25px; padding: 15px;\">请点击链接继续：{opurl}</p><p style=\"line-height: 23.7999992370605px;\">&nbsp;</p><p class=\"footer\" style=\"line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); padding-top: 6px; margin-top: 25px; color: rgb(131, 131, 131);\">请勿回复本邮件, 此邮箱未受监控, 您不会得到任何回复。<br/><br/><a href=\"{weburl}\"><strong style=\"outline: none; cursor: pointer; color: rgb(30, 84, 148);\">{webname}会员中心</strong></a></p></div></div>', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_email_safety_title', '{webname} 会员中心 修改绑定邮箱', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_email_safety_content', '<div style=\"width:500px;margin:20px auto;\"><div class=\"header clearfix\" style=\"font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; background-color: rgb(255, 255, 255);\"><a href=\"{weburl}\"><strong style=\"outline: none; cursor: pointer; color: rgb(30, 84, 148);\">{webname} 会员中心</strong></a></div><p>&nbsp;</p><div class=\"content\" style=\"font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; border: 1px solid rgb(233, 233, 233); margin: 2px 0px 0px; padding: 30px; background: none 0px 0px repeat scroll rgb(255, 255, 255);\"><p style=\"line-height: 23.7999992370605px;\">您好：</p><p style=\"line-height: 23.7999992370605px;\">这是您在 {webname} 会员中心 上的重要邮件, 功能是进行&nbsp;会员中心 绑定邮箱修改, 请点击下面的连接完成验证</p><p style=\"line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); margin-top: 15px; margin-bottom: 25px; padding: 15px;\">请点击链接继续：{opurl}</p><p style=\"line-height: 23.7999992370605px;\">&nbsp;</p><p class=\"footer\" style=\"line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); padding-top: 6px; margin-top: 25px; color: rgb(131, 131,131);\">请勿回复本邮件,此邮箱未受监控,您不会得到任何回复。<br/><br/><a href=\"{weburl}\"><strong style=\"outline: none; cursor: pointer; color: rgb(30, 84, 148);\">{webname}会员中心</strong></a></p></div></div>', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_wap','0','',0,0,'cn');
INSERT INTO met_config VALUES (null, 'debug','0','',0,0,'cn');
INSERT INTO met_config VALUES(null, 'metconfig_fd_word', '', '', '0', '0', 'cn');
INSERT INTO met_config VALUES(null, 'flash_10000', '3|980|300|1', '', '0', '10000', 'cn');
INSERT INTO met_config VALUES(null, 'flash_10001', '1|980|600|', '', '0', '10001', 'cn');


INSERT INTO met_lang VALUES (null,'简体中文','1','1','cn','cn','cn.gif','','0','0','html','','cn');

INSERT INTO met_admin_array VALUES('1','普通会员','','0','','0','0','1','1','cn','');
INSERT INTO met_admin_array VALUES('2','代理商','','0','','0','0','2','1','cn','');

INSERT INTO `met_user_group` VALUES(1, '普通会员', 1, 'cn');
INSERT INTO `met_user_group` VALUES(2, '代理商', 3, 'cn');