<?php
if(file_exists('../config/install.lock')){
	exit('对不起，该程序已经安装过了。<br/>
	      如您要重新安装，请手动删除config/install.lock文件。');
}
$config_save       = "<?php
/*
met_weburl        = \"$met_weburl\";
met_webname       = \"$met_webname\";
met_logo          = \"$met_logo\";
met_skin_user     = \"$met_skin_user\";
met_big_wate      = \"$met_big_wate\";
met_thumb_wate    = \"$met_thumb_wate\";
met_wate_class    = \"$met_wate_class\";
met_wate_img      = \"$met_wate_img\";
met_wate_bigimg   = \"$met_wate_bigimg\";
met_text_wate     = \"$met_text_wate\";
met_text_size     = \"$met_text_size\";
met_text_bigsize  = \"$met_text_bigsize\";
met_text_fonts    = \"$met_text_fonts\";
met_text_color    = \"$met_text_color\";
met_text_angle    = \"$met_text_angle\";
met_watermark     = \"$met_watermark\";
met_img_x         = \"$met_img_x\";
met_img_y         = \"$met_img_y\";
met_title_keywords= \"$met_title_keywords\";
met_keywords      = \"$met_keywords\";
met_description   = \"$met_description\";
met_seo           = \"$met_seo\";
met_alt           = \"$met_alt\";
met_atitle        = \"$met_atitle\";
met_linkname      = \"$met_linkname\";
met_online_type   = \"$met_online_type\";
met_footright     = \"$met_footright\";
met_footaddress   = \"$met_footaddress\";
met_foottel       = \"$met_foottel\";
met_footother     = \"$met_footother\";
met_foottext      = \"$met_foottext\";
met_footstat      = \"$met_footstat\";
met_product_list  = \"$met_product_list\";
met_news_list     = \"$met_news_list\";
met_download_list = \"$met_download_list\";
met_img_list      = \"$met_img_list\";
met_job_list      = \"$met_job_list\";
met_message_list  = \"$met_message_list\";
met_search_list   = \"$met_search_list\";
met_fd_fromname   = \"$met_fd_fromname\";
met_fd_smtp       = \"$met_fd_smtp\";
met_fd_usename    = \"$met_fd_usename\";
met_fd_password   = \"$met_fd_password\";
met_skin_css      = \"$met_skin_css\";
met_autothumb_ok  = \"$met_autothumb_ok\";
met_member_use    = \"$met_member_use\";
met_member_login  = \"$met_member_login\";
met_newsdays      = \"$met_newsdays\";
met_hot           = \"$met_hot\";
met_listtime      = \"$met_listtime\";
met_contenttime   = \"$met_contenttime\";
met_memberemail   = \"$met_memberemail\";
met_membercontrol = \"$met_membercontrol\";
met_sitemap_html    =\"$met_sitemap_html\";
met_sitemap_xml     =\"$met_sitemap_xml\";
met_sitemap_max     =\"$met_sitemap_max\";
met_online_skin     =\"$met_online_skin\";
met_online_color    =\"$met_online_color\";
met_qq_type         =\"$met_qq_type\";
met_msn_type        =\"$met_msn_type\";
met_taobao_type     =\"$met_taobao_type\";
met_alibaba_type    =\"$met_alibaba_type\";
met_skype_type      =\"$met_skype_type\";
met_onlinetel       =\"$met_onlinetel\";
met_pageskin        =\"$met_pageskin\";
met_indexskin       =\"$met_indexskin\";
met_product_page    =\"$met_product_page\";
met_img_page        =\"$met_img_page\";
met_product_detail  =\"$met_product_detail\";
met_img_detail      =\"$met_img_detail\";
met_productdetail_x =\"$met_productdetail_x\";
met_productdetail_y =\"$met_productdetail_y\";
met_imgdetail_x     =\"$met_imgdetail_x\";
met_imgdetail_y     =\"$met_imgdetail_y\";
met_onlineright_top =\"$met_onlineright_top\";
met_onlineright_right =\"$met_onlineright_right\";
met_onlineleft_top  =\"$met_onlineleft_top\";
met_onlineleft_left =\"$met_onlineleft_left\";
met_file_format   = \"$met_file_format\";
met_file_maxsize  = \"$met_file_maxsize\";
met_memberlogin_code= \"$met_memberlogin_code\";
met_login_code    = \"$met_login_code\";
met_sqlnum        = \"$met_sqlnum\";
met_submit_type   = \"$met_submit_type\";
met_img_type      = \"$met_img_type\";
met_img_maxsize   = \"$met_img_maxsize\";
met_webhtm        = \"$met_webhtm\";
met_htmtype       = \"$met_htmtype\";
met_htmpagename   = \"$met_htmpagename\";
met_htmlistname   = \"$met_htmlistname\";
met_htmway        = \"$met_htmway\";
met_member_use    = \"$met_member_use\";
met_member_login  = \"$met_member_login\";
met_member_force  = \"$met_member_force\";
met_memberforce   = \"$met_memberforce\";
met_sitemap_html  = \"$met_sitemap_html\";
met_sitemap_xml   = \"$met_sitemap_xml\";
met_sitemap_max   = \"$met_sitemap_max\";
index_online_type = \"$index_online_type\";
index_news_no     = \"$index_news_no\";
index_product_no  = \"$index_product_no\";
index_download_no = \"$index_download_no\";
index_img_no      = \"$index_img_no\";
index_job_no      = \"$index_job_no\";
index_link_ok     = \"$index_link_ok\";
index_link_img    = \"$index_link_img\";
index_link_text   = \"$index_link_text\";
*/
?>";
if(!is_writable("../config/config_en.inc.php"))@chmod("../config/config_en.inc.php",0777);
$fp = fopen("../config/config_en.inc.php",w);
    fputs($fp, $config_save);
    fclose($fp);
?>