
INSERT INTO `met_column` VALUES (29,'News','news','',0,2,2,0,1,'',NULL,'',0,'',1,'',0,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (30,'Product','product','',0,3,3,0,1,'',NULL,'',0,'',1,'',3,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (31,'Download','download','',0,4,4,0,3,'',NULL,'',0,'',1,'',0,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (32,'Case','img','',0,5,5,0,1,'',NULL,'',0,'',1,'',4,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (33,'About us','about','about',0,1,1,0,1,'',NULL,'',0,'',1,'',0,0,'','',0,'en','',0);
INSERT INTO `met_column` VALUES (34,'Guestbook','message','',33,7,7,0,2,'',NULL,'',0,'',2,'',0,0,'','',1,'en','',33);
INSERT INTO `met_column` VALUES (35,'Feedback','feedback','',33,8,8,0,2,'',NULL,'',0,'',2,'',0,0,'','',1,'en','',33);
INSERT INTO `met_column` VALUES (36,'Friendly link','link','',0,9,9,0,2,'',NULL,'',0,'',1,'',0,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (37,'Member','member','',0,10,10,0,2,'',NULL,'',0,'',1,'',0,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (38,'Search','search','',0,11,11,0,2,'',NULL,'',0,'',1,'',0,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (39,'Sitemap','sitemap','',0,12,12,0,2,'',NULL,'',0,'',1,'',0,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (40,'Job','job','',0,6,6,0,1,'',NULL,NULL,0,'',1,'',0,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (41,'Company','about','company',33,1,1,0,0,'','<p><img height=\"150\" alt=\"\" hspace=\"2\" width=\"150\" align=\"left\" vspace=\"2\" border=\"0\" src=\"../upload/logoimg.gif\" />MetInfo Inc. focused on network information and network marketing, through the integration team of professional marketing ideas and networking technologies to provide customers with high-quality Internet marketing services.</p>\r\n<p>&nbsp;</p>\r\n<p>MetInfo services include: Web system development, website building, website promotion,&nbsp; and network marketing, planning and operation.</p>\r\n<p>&nbsp;</p>\r\n<p>MetInfo\'s main product - MetCMS Enterprise Content Management System is developed based on PHP+Mysql, search engine optimization(SEO) built-in Whole system and supporting user-defined interface language (the world\'s languages). MetCMS contains general moudle and function of a corporate Website (page module, news module, product modules, download module, image module, job module, message system, feedback system, on-line communication system, friendfly link module, sitemap module, member module). MetCMS focus on building marketing Enterprise website for you with powerful and flexible system management capabilities, static page generation capabilities and so on.</p>\r\n<p>&nbsp;</p>\r\n<p>MetInfo adhering to the &quot;create value for our partners&quot;,&nbsp; the core values and to &quot;honesty, tolerance, innovation, service&quot; as the spirit of enterprise, through self-innovation and sincere cooperation for e-commerce and information services industries create value.</p>\r\n<p>&nbsp;</p>\r\n<p><br />\r\n<strong>About &quot;creating value for our partners&quot;</strong></p>\r\n<p>The customers, suppliers, shareholders, employees and all relations of co-operation and their own units and individuals are our partners, and only through efforts to create value for partners in order to realize their own value and access to development and success.</p>\r\n<p>&nbsp;</p>\r\n<p><br />\r\n<strong>About &quot;honesty, tolerance, innovation, service&quot; </strong></p>\r\n<p>Honesty is the foundation of all co-operation, tolerance is a prerequisite for problem-solving, innovation is the development tool for the cause of the service is to create the fundamental value.&nbsp;<br />\r\n&nbsp;</p>','',0,'',2,'',0,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (42,'Contact','about','contact',33,1,10,0,1,'','<p><strong>MetInfo Information Technology Co., Ltd.</strong><br />\r\n<strong>Address</strong>: Room 1501, E Building until, Rongwangzheng, Yuelu District , Changsha, China.<br />\r\n<strong>Tel </strong>:+86-731-87133078&nbsp;&nbsp; +86-13787183014<br />\r\n<strong>Fax </strong>:+86-731-87133078<br />\r\n<strong>Email</strong>: <a href=\"javascript:location.href=\'mailto:\'+String.fromCharCode(115,97,108,101,115,64,109,101,116,105,110,102,111,46,99,110)+\'?\'\">sales@metinfo.cn</a><br />\r\n<strong>Website</strong>: <a href=\"http://www.metinfo.cn/\">www.MetInfo.cn</a></p>','',0,'',2,'',99,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (43,'Enterprise News','news','',29,2,1,0,2,'',NULL,'',0,'',2,'',1,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (44,'Industry News','news','',29,2,2,0,0,'',NULL,'',0,'',2,'',2,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (45,'Digital Appliances','product','',30,3,1,0,0,'',NULL,'',0,'',2,'',0,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (46,'Furniture','product','',30,3,2,0,0,'',NULL,'',0,'',2,'',0,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (47,'Transport','product','',30,3,3,0,0,'',NULL,'',0,'',2,'',0,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (48,'Fitness','product','',30,3,4,0,0,'',NULL,'',0,'',2,'',0,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (49,'Hardware','product','',30,3,5,0,0,'',NULL,'',0,'',2,'',0,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (50,'TV','product','',45,3,1,0,0,'',NULL,'',0,'',3,'',0,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (51,'Notebook','product','',45,3,2,0,0,'',NULL,'',0,'',3,'',0,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (52,'Washer','product','',45,3,3,0,0,'',NULL,'',0,'',3,'',0,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (53,'Refrigerator','product','',45,3,4,0,0,'',NULL,'',0,'',3,'',0,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (54,'Software','download','',31,4,1,0,0,'',NULL,'',0,'',2,'',0,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (55,'Document','download','',31,4,2,0,0,'',NULL,'',0,'',2,'',0,0,'','',1,'en','',0);
INSERT INTO `met_column` VALUES (56,'Admin','',NULL,0,0,100,1,2,NULL,NULL,NULL,0,'target=\'_blank\'',1,'admin/',0,0,'','',1,'en','',0);


INSERT INTO `met_download` VALUES (2,'MetCMS Enterprise Content Management System 3.0 ','','','<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MetCMS Enterprise Content Management System is developed based on PHP+Mysql, search engine optimization(SEO) built-in Whole system and supporting user-defined interface language (the world\'s languages). MetCMS contains general moudle and function of a corporate Website (page module, news module, product modules, download module, image module, job module, message system, feedback system, on-line communication system, friendfly link module, sitemap module, member module). MetCMS focus on building marketing Enterprise website for you with powerful and flexible system management capabilities, static page generation capabilities and so on.</p>\r\n<p>&nbsp;</p>\r\n<p><strong>Main function :</strong><br />\r\n<strong>Language :<br />\r\n</strong>1, Support all languages(including Chinese,&nbsp; English, Japanese, etc.), the user can customize unlimited languages. You can visit the website with different domain to the default home page of appropriate language.<br />\r\n2, Original language pack editing function, users can easily edit the site Admin website language packs, so as to control foreground display language and language parameters (font, text size, page background, indicating number of words, etc.).</p>\r\n<p>&nbsp;</p>\r\n<p><strong>Interface Style :</strong><br />\r\n1, All text, picture,content and category can be user-defined, you can change information easy. <br />\r\n2, Original category mark control method, the administrator need only set the mark of category to display different information or category on homepage and website.<br />\r\n3, Templates and procedures are entirely separated, all languages share one template, you can also set different template and style for each language page style.<br />\r\n4,Template created simple and flexible, supporting using labeling and standard PHP syntax&nbsp; to create. <br />\r\n5, The same template supporting different color styles, while supporting a variety of page layout, users can easily switch. <br />\r\n6, Automatically generated thumbnails, you can customize pictures and text watermark which will automatically added when upload pictures.<br />\r\n7, Flash(advertising) can be different styles according to category (including the images Carousel, Flash, a single picture), and can be a variety of image carousel method. <br />\r\n8, Built-in a variety of online communication with the screen scrolling style.<br />\r\n9,Product photos and images module image can display in a variety of styles, the same product can be with unlimited pictures.<br />\r\n10, You can set flip style, information display page number, time format, popular hits of information, the latest information release days. <br />\r\n11, DIV + CSS layout, all compatible with IE6, IE7, IE8, Firefox, Google, TT, 360 degrees, traveling, and other mainstream browser.</p>\r\n<p>&nbsp;</p>\r\n<p><strong>SEO Optimization :</strong><br />\r\n1, You can set parameters and all pages SEO information such as keywords, descriptions, etc.; <br />\r\n2, Static page generation function can be automatically or manually generate&nbsp; the whole website static pages, and can personalize the name and page format of HTML. <br />\r\n3, Page title has been in accordance with &quot;Information title - cagegory name - Website Title&quot; , all the title are automatically generated. <br />\r\n4, Built-in hot tag feature, which can effectively increase website internal links and keyword links. <br />\r\n5,The official templates are designed with&nbsp; DIV+CSS,and contain all SEO technology such as H1, image ALT, hyperlink Title, page header and footer keywords.<br />\r\n6, Built-in sitemap module, can generate HTML, and the latest new xml sitemap.<br />\r\n7, Built-in Friendkly link module, you can easily complete the interconnection with other sites. <br />\r\n8, the page name and format,Category and folder of category can be customized,which can effectively distinguish between the homogenization of information on competitors, enhance the effect of SEO.</p>\r\n<p>&nbsp;</p>\r\n<p><strong>Interactive Marketing <br />\r\n</strong>1, Built-in full-line communication background management functions, you can add QQ, MSN, Alibaba, SKYPE, third-party customer communication software, and you can set the display style and icon. <br />\r\n2, Built-in powerful online feedback system, fully customizable form fields can be used for product ordering, online registration, online surveys, feedback, etc., automatically send feedback to the specified email (can be set more emails), and can be categorized in tabular form export EXCEL feedback information. <br />\r\n3, Online message&nbsp; functions, administrators can review and respond to a message through the background content.<br />\r\n4, Recruitment information release and the candidates to submit resumes online functionality.<br />\r\n5, Background built-in third-party statistical code and other tools to code interface, you can easily monitor the website and the visitor details.</p>\r\n<p>&nbsp;</p>\r\n<p><strong>Member and Rights Management :</strong><br />\r\n1, The system containts anonymous, member, agent, system administrator privileges four roles, and enables member, agent to registration.<br />\r\n2, Content, category, information pages and the field parameters can be access control, thus the flexibility to set the proxy prices, data downloads, the latest product release, etc.<br />\r\n3, Administrator rights and operational authority can be controled, which can achieve main administrators management website at the same time, and simple user interface allows administrators to understand.</p>\r\n<p>&nbsp;</p>\r\n<p><br />\r\n<strong>Safety and efficiency :</strong><br />\r\n1, Built-in database backup and restore functions, you can easily complete the entire station database backup and recovery, support configuration files and the entire station back compressed package download.<br />\r\n2, You can change the folder name of admin, and it allows you to easily manage login path of the hidden to enhance system security performance.<br />\r\n3, Validation code, anti-refresh mechanism, SQL danger symbols and statements filtering mechanism of the system greatly enhanced the ability to prevent malicious attacks. <br />\r\n4, Administrator password and member password can get back from E-mail back, that enhances system security self-help. <br />\r\n5, The installation folder, and update folder can be deleted from the background. <br />\r\n6, The efficiency of public information read&nbsp; and&nbsp; the template calls the database are set by control file (from the template creator control) ,it greatly enhanced the operational efficiency of the system.<br />\r\n7, The folder of upload and document management capabilities, you can easily manage to delete junk files.<br />\r\n8, PHP + MYSQL structure, website static functions and the system file permissions settings greatly enhanced the system against Trojan horses and malicious attacks capacity.</p>',31,54,0,0,'http://www.metinfo.cn/download/download_13_1.htm','400',0,2,'2010-03-10 09:39:21','2010-03-10 09:39:21','admin',0,0,0,'','en');


INSERT INTO `met_flash` VALUES (3,10000,'MetInfo','../upload/201003/1268144681.jpg','http://www.MetInfo.cn','','',1,1001,200,'en');
INSERT INTO `met_flash` VALUES (4,10000,'MetInfo templates','../upload/201003/1268144283.jpg','http://www.MetInfo.cn','','',2,1001,200,'en');

INSERT INTO `met_img` VALUES (5,'Case demo 4','','The whole point built-in SEO search engine optimization mechanism','<p>The whole point built-in SEO search engine optimization mechanism, static pages automatically generated features, popular tags set features that make sites more easily extended to more easily indexed by search engines, easier to upgrade keywords rankings and thus easier for enterprises customers, MetInfo always believed that only with the marketing power of a corporate website is the real value of the site; <br />\r\n&nbsp;</p>',32,0,0,0,'../upload/201003/watermark/1268126731.jpg','../upload/201003/thumb/1268126731.jpg',1,1,'2010-03-09 17:23:45','2010-03-09 17:22:12','admin',0,0,'','en',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `met_img` VALUES (6,'Case demo 3','','Background operation simple and convenient','<p>Background operation simple and convenient, MetInfo enterprise website management system for corporate website follows the classic ASP background, any business, webmasters, without technical expertise, they can easily manage web sites; <br />\r\n&nbsp;&nbsp;&nbsp; 3. UTF-8 international standard codes, add the Chinese and English language and home access to automatically switch the default, Traditional Chinese prospects automatically switch to support multi-language template development; <br />\r\n&nbsp;</p>',32,0,0,0,'../upload/201003/watermark/1268127077.jpg','../upload/201003/thumb/1268127077.jpg',1,0,'2010-03-09 17:23:55','2010-03-09 17:23:55','admin',0,0,'','en',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `met_img` VALUES (7,'Case demo 2','','such as real-time chat online to add and background management \r\n','<p>Support QQ \\ MSN \\ SKYPE \\ Taobao\'s Wangwang tools such as real-time chat online to add and background management; <br />\r\n&nbsp;&nbsp;&nbsp; 5. Flexible and powerful online feedback system, you can set the feedback form background field (support for drop-down menus and multiple-choice), while EMAIL automated response to feedback from those set by the administrator\'s mailbox automatic transmittal of the latest feedback information;</p>',32,0,0,0,'../upload/201003/watermark/1268127066.jpg','../upload/201003/thumb/1268127066.jpg',1,1,'2010-03-09 17:25:49','2010-03-09 17:24:49','admin',0,0,'','en',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `met_img` VALUES (8,'Case demo 1','','Spare field to enable and set up features','<p>Spare field to enable and set up features, columns home call identification features, user-friendly and more flexible design templates;</p>',32,0,0,0,'../upload/201003/watermark/1268127624.jpg','../upload/201003/thumb/1268127624.jpg',1,8,'2010-03-09 17:28:02','2010-03-09 17:26:16','admin',0,0,'','en',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO `met_index` VALUES (2,'<p><img height=\"120\" alt=\"\" hspace=\"2\" width=\"150\" align=\"left\" vspace=\"2\" src=\"upload/hibuilding2_004.jpg\" /></p>\r\n<p>&nbsp;MetInfo\'s main product - MetInfo Enterprise Content Management System is developed based on PHP+Mysql, search engine optimization(SEO) built-in Whole system and supporting user-defined interface language (the world\'s languages). MetInfo contains general moudle and function of a corporate Website (page module, news module, product modules, download module, image module, job module, message system, feedback system, on-line communication system, friendfly link module, sitemap module, member module). MetInfo focus on building marketing Enterprise website for you with powerful and flexible system management capabilities, static page generation capabilities and so on.<br />\r\n&nbsp;</p>','en');

INSERT INTO `met_job` VALUES (2,'Sales',10,'China','$3000','2010-03-10',0,'<p>1, undergraduate degree or above</p>\r\n<p>2, marketing professional</p>',0,0,'','en');

INSERT INTO `met_label` VALUES (3,'Enterprise Content Manager System','Enterprise Content Manager System','http://www.metinfo.cn','en');

INSERT INTO `met_link` VALUES (4,'MetInfo','http://www.metinfo.cn','http://www.metinfo.cn/upload/200911/1259148297.gif',1,'MetInfo','',100,1,1,'2010-03-08 17:05:20','en',NULL);
INSERT INTO `met_link` VALUES (5,'MetInfo','http://www.metinfo.cn','http://',0,'MetInfo enterprise content manager system','',100,1,1,'2010-03-08 17:06:06','en',NULL);
INSERT INTO `met_link` VALUES (6,'Google','http://www.google.com','http://',0,'','',99,1,1,'2010-03-08 17:06:23','en',NULL);

INSERT INTO `met_list` VALUES (44,52,'male',1,'en');
INSERT INTO `met_list` VALUES (45,52,'female',2,'en');
INSERT INTO `met_list` VALUES (46,65,'Technical inquiry',1,'en');
INSERT INTO `met_list` VALUES (47,65,'Purchase inquiry',2,'en');
INSERT INTO `met_list` VALUES (48,65,'Business',3,'en');
INSERT INTO `met_list` VALUES (49,65,'Other',4,'en');
INSERT INTO `met_list` VALUES (50,75,'Search Engine',1,'en');
INSERT INTO `met_list` VALUES (51,75,'Web Link',2,'en');
INSERT INTO `met_list` VALUES (52,75,'Friend Introduce',3,'en');
INSERT INTO `met_list` VALUES (53,75,'Other way',4,'en');
INSERT INTO `met_list` VALUES (54,73,'Afghanistan',1,'en');
INSERT INTO `met_list` VALUES (55,73,'Albania',2,'en');
INSERT INTO `met_list` VALUES (56,73,'Algeria',3,'en');
INSERT INTO `met_list` VALUES (57,73,'American Samoa',4,'en');
INSERT INTO `met_list` VALUES (58,73,'Andorra',5,'en');
INSERT INTO `met_list` VALUES (59,73,'Angola',6,'en');
INSERT INTO `met_list` VALUES (60,73,'Anguilla',7,'en');
INSERT INTO `met_list` VALUES (61,73,'Antarctica',8,'en');
INSERT INTO `met_list` VALUES (62,73,'Antigua and Barbuda',9,'en');
INSERT INTO `met_list` VALUES (63,73,'Argentina',10,'en');
INSERT INTO `met_list` VALUES (64,73,'Armenia',11,'en');
INSERT INTO `met_list` VALUES (65,73,'Aruba',12,'en');
INSERT INTO `met_list` VALUES (66,73,'Australia',13,'en');
INSERT INTO `met_list` VALUES (67,73,'Austria',14,'en');
INSERT INTO `met_list` VALUES (68,73,'Azerbaijan',15,'en');
INSERT INTO `met_list` VALUES (69,73,'Bahamas',16,'en');
INSERT INTO `met_list` VALUES (70,73,'Bahrain',17,'en');
INSERT INTO `met_list` VALUES (71,73,'Bangladesh',18,'en');
INSERT INTO `met_list` VALUES (72,73,'Barbados',19,'en');
INSERT INTO `met_list` VALUES (73,73,'Belarus',20,'en');
INSERT INTO `met_list` VALUES (74,73,'Belgium',21,'en');
INSERT INTO `met_list` VALUES (75,73,'Belize',22,'en');
INSERT INTO `met_list` VALUES (76,73,'Benin',23,'en');
INSERT INTO `met_list` VALUES (77,73,'Bermuda',24,'en');
INSERT INTO `met_list` VALUES (78,73,'Bhutan',25,'en');
INSERT INTO `met_list` VALUES (79,73,'Bolivia',26,'en');
INSERT INTO `met_list` VALUES (80,73,'Bosnia and Herzegovina',27,'en');
INSERT INTO `met_list` VALUES (81,73,'Botswana',28,'en');
INSERT INTO `met_list` VALUES (82,73,'Bouvet Island',29,'en');
INSERT INTO `met_list` VALUES (83,73,'Brazil',30,'en');
INSERT INTO `met_list` VALUES (84,73,'British Indian Ocean Territory',31,'en');
INSERT INTO `met_list` VALUES (85,73,'Brunei Darussalam',32,'en');
INSERT INTO `met_list` VALUES (86,73,'Bulgaria',33,'en');
INSERT INTO `met_list` VALUES (87,73,'Burkina Faso',34,'en');
INSERT INTO `met_list` VALUES (88,73,'Burundi',35,'en');
INSERT INTO `met_list` VALUES (89,73,'Cambodia',36,'en');
INSERT INTO `met_list` VALUES (90,73,'Cameroon',37,'en');
INSERT INTO `met_list` VALUES (91,73,'Canada',38,'en');
INSERT INTO `met_list` VALUES (92,73,'Cape Verde',39,'en');
INSERT INTO `met_list` VALUES (93,73,'Cayman Islands',40,'en');
INSERT INTO `met_list` VALUES (94,73,'Central African Republic',41,'en');
INSERT INTO `met_list` VALUES (95,73,'Chad',42,'en');
INSERT INTO `met_list` VALUES (96,73,'Chile',43,'en');
INSERT INTO `met_list` VALUES (97,73,'China (Mainland)',44,'en');
INSERT INTO `met_list` VALUES (98,73,'Christmas Island',45,'en');
INSERT INTO `met_list` VALUES (99,73,'Cocos (Keeling) Islands',46,'en');
INSERT INTO `met_list` VALUES (100,73,'Colombia',47,'en');
INSERT INTO `met_list` VALUES (101,73,'Comoros',48,'en');
INSERT INTO `met_list` VALUES (102,73,'Congo',49,'en');
INSERT INTO `met_list` VALUES (103,73,'Congo, The Democratic Republic Of The',50,'en');
INSERT INTO `met_list` VALUES (104,73,'Cook Islands',51,'en');
INSERT INTO `met_list` VALUES (105,73,'Costa Rica',52,'en');
INSERT INTO `met_list` VALUES (106,73,'Cote D&#39;Ivoire',53,'en');
INSERT INTO `met_list` VALUES (107,73,'Croatia (local name: Hrvatska)',54,'en');
INSERT INTO `met_list` VALUES (108,73,'Cuba',55,'en');
INSERT INTO `met_list` VALUES (109,73,'Cyprus',56,'en');
INSERT INTO `met_list` VALUES (110,73,'Czech Republic',57,'en');
INSERT INTO `met_list` VALUES (111,73,'Denmark',58,'en');
INSERT INTO `met_list` VALUES (112,73,'Djibouti',59,'en');
INSERT INTO `met_list` VALUES (113,73,'Dominica',60,'en');
INSERT INTO `met_list` VALUES (114,73,'Dominican Republic',61,'en');
INSERT INTO `met_list` VALUES (115,73,'East Timor',62,'en');
INSERT INTO `met_list` VALUES (116,73,'Ecuador',63,'en');
INSERT INTO `met_list` VALUES (117,73,'Egypt',64,'en');
INSERT INTO `met_list` VALUES (118,73,'El Salvador',65,'en');
INSERT INTO `met_list` VALUES (119,73,'Equatorial Guinea',66,'en');
INSERT INTO `met_list` VALUES (120,73,'Eritrea',67,'en');
INSERT INTO `met_list` VALUES (121,73,'Estonia',68,'en');
INSERT INTO `met_list` VALUES (122,73,'Ethiopia',69,'en');
INSERT INTO `met_list` VALUES (123,73,'Falkland Islands (Malvinas)',70,'en');
INSERT INTO `met_list` VALUES (124,73,'Faroe Islands',71,'en');
INSERT INTO `met_list` VALUES (125,73,'Fiji',72,'en');
INSERT INTO `met_list` VALUES (126,73,'Finland',73,'en');
INSERT INTO `met_list` VALUES (127,73,'France',74,'en');
INSERT INTO `met_list` VALUES (128,73,'France Metropolitan',75,'en');
INSERT INTO `met_list` VALUES (129,73,'French Guiana',76,'en');
INSERT INTO `met_list` VALUES (130,73,'French Polynesia',77,'en');
INSERT INTO `met_list` VALUES (131,73,'French Southern Territories',78,'en');
INSERT INTO `met_list` VALUES (132,73,'Gabon',79,'en');
INSERT INTO `met_list` VALUES (133,73,'Gambia',80,'en');
INSERT INTO `met_list` VALUES (134,73,'Georgia',81,'en');
INSERT INTO `met_list` VALUES (135,73,'Germany',82,'en');
INSERT INTO `met_list` VALUES (136,73,'Ghana',83,'en');
INSERT INTO `met_list` VALUES (137,73,'Gibraltar',84,'en');
INSERT INTO `met_list` VALUES (138,73,'Greece',85,'en');
INSERT INTO `met_list` VALUES (139,73,'Greenland',86,'en');
INSERT INTO `met_list` VALUES (140,73,'Grenada',87,'en');
INSERT INTO `met_list` VALUES (141,73,'Guadeloupe',88,'en');
INSERT INTO `met_list` VALUES (142,73,'Guam',89,'en');
INSERT INTO `met_list` VALUES (143,73,'Guatemala',90,'en');
INSERT INTO `met_list` VALUES (144,73,'Guinea',91,'en');
INSERT INTO `met_list` VALUES (145,73,'Guinea-Bissau',92,'en');
INSERT INTO `met_list` VALUES (146,73,'Guyana',93,'en');
INSERT INTO `met_list` VALUES (147,73,'Haiti',94,'en');
INSERT INTO `met_list` VALUES (148,73,'Heard and Mc Donald Islands',95,'en');
INSERT INTO `met_list` VALUES (149,73,'Honduras',96,'en');
INSERT INTO `met_list` VALUES (150,73,'Hong Kong',97,'en');
INSERT INTO `met_list` VALUES (151,73,'Hungary',98,'en');
INSERT INTO `met_list` VALUES (152,73,'Iceland',99,'en');
INSERT INTO `met_list` VALUES (153,73,'India',100,'en');
INSERT INTO `met_list` VALUES (154,73,'Indonesia',101,'en');
INSERT INTO `met_list` VALUES (155,73,'Iran (Islamic Republic of)',102,'en');
INSERT INTO `met_list` VALUES (156,73,'Iraq',103,'en');
INSERT INTO `met_list` VALUES (157,73,'Ireland',104,'en');
INSERT INTO `met_list` VALUES (158,73,'Isle of Man',105,'en');
INSERT INTO `met_list` VALUES (159,73,'Israel',106,'en');
INSERT INTO `met_list` VALUES (160,73,'Italy',107,'en');
INSERT INTO `met_list` VALUES (161,73,'Jamaica',108,'en');
INSERT INTO `met_list` VALUES (162,73,'Japan',109,'en');
INSERT INTO `met_list` VALUES (163,73,'Jordan',110,'en');
INSERT INTO `met_list` VALUES (164,73,'Kazakhstan',111,'en');
INSERT INTO `met_list` VALUES (165,73,'Kenya',112,'en');
INSERT INTO `met_list` VALUES (166,73,'Kiribati',113,'en');
INSERT INTO `met_list` VALUES (167,73,'Kosovo',114,'en');
INSERT INTO `met_list` VALUES (168,73,'Kuwait',115,'en');
INSERT INTO `met_list` VALUES (169,73,'Kyrgyzstan',116,'en');
INSERT INTO `met_list` VALUES (170,73,'Lao People&#39;s Democratic Republic',117,'en');
INSERT INTO `met_list` VALUES (171,73,'Latvia',118,'en');
INSERT INTO `met_list` VALUES (172,73,'Lebanon',119,'en');
INSERT INTO `met_list` VALUES (173,73,'Lesotho',120,'en');
INSERT INTO `met_list` VALUES (174,73,'Liberia',121,'en');
INSERT INTO `met_list` VALUES (175,73,'Libyan Arab Jamahiriya',122,'en');
INSERT INTO `met_list` VALUES (176,73,'Liechtenstein',123,'en');
INSERT INTO `met_list` VALUES (177,73,'Lithuania',124,'en');
INSERT INTO `met_list` VALUES (178,73,'Luxembourg',125,'en');
INSERT INTO `met_list` VALUES (179,73,'Macau',126,'en');
INSERT INTO `met_list` VALUES (180,73,'Madagascar',127,'en');
INSERT INTO `met_list` VALUES (181,73,'Malawi',128,'en');
INSERT INTO `met_list` VALUES (182,73,'Malaysia',129,'en');
INSERT INTO `met_list` VALUES (183,73,'Maldives',130,'en');
INSERT INTO `met_list` VALUES (184,73,'Mali',131,'en');
INSERT INTO `met_list` VALUES (185,73,'Malta',132,'en');
INSERT INTO `met_list` VALUES (186,73,'Marshall Islands',133,'en');
INSERT INTO `met_list` VALUES (187,73,'Martinique',134,'en');
INSERT INTO `met_list` VALUES (188,73,'Mauritania',135,'en');
INSERT INTO `met_list` VALUES (189,73,'Mauritius',136,'en');
INSERT INTO `met_list` VALUES (190,73,'Mayotte',137,'en');
INSERT INTO `met_list` VALUES (191,73,'Mexico',138,'en');
INSERT INTO `met_list` VALUES (192,73,'Micronesia',139,'en');
INSERT INTO `met_list` VALUES (193,73,'Moldova',140,'en');
INSERT INTO `met_list` VALUES (194,73,'Monaco',141,'en');
INSERT INTO `met_list` VALUES (195,73,'Mongolia',142,'en');
INSERT INTO `met_list` VALUES (196,73,'Montenegro',143,'en');
INSERT INTO `met_list` VALUES (197,73,'Montserrat',144,'en');
INSERT INTO `met_list` VALUES (198,73,'Morocco',145,'en');
INSERT INTO `met_list` VALUES (199,73,'Mozambique',146,'en');
INSERT INTO `met_list` VALUES (200,73,'Myanmar',147,'en');
INSERT INTO `met_list` VALUES (201,73,'Namibia',148,'en');
INSERT INTO `met_list` VALUES (202,73,'Nauru',149,'en');
INSERT INTO `met_list` VALUES (203,73,'Nepal',150,'en');
INSERT INTO `met_list` VALUES (204,73,'Netherlands',151,'en');
INSERT INTO `met_list` VALUES (205,73,'Netherlands Antilles',152,'en');
INSERT INTO `met_list` VALUES (206,73,'New Caledonia',153,'en');
INSERT INTO `met_list` VALUES (207,73,'New Zealand',154,'en');
INSERT INTO `met_list` VALUES (208,73,'Nicaragua',155,'en');
INSERT INTO `met_list` VALUES (209,73,'Niger',156,'en');
INSERT INTO `met_list` VALUES (210,73,'Nigeria',157,'en');
INSERT INTO `met_list` VALUES (211,73,'Niue',158,'en');
INSERT INTO `met_list` VALUES (212,73,'Norfolk Island',159,'en');
INSERT INTO `met_list` VALUES (213,73,'North Korea',160,'en');
INSERT INTO `met_list` VALUES (214,73,'Northern Mariana Islands',161,'en');
INSERT INTO `met_list` VALUES (215,73,'Norway',162,'en');
INSERT INTO `met_list` VALUES (216,73,'Oman',163,'en');
INSERT INTO `met_list` VALUES (217,73,'Other Country',164,'en');
INSERT INTO `met_list` VALUES (218,73,'Pakistan',165,'en');
INSERT INTO `met_list` VALUES (219,73,'Palau',166,'en');
INSERT INTO `met_list` VALUES (220,73,'Palestine',167,'en');
INSERT INTO `met_list` VALUES (221,73,'Panama',168,'en');
INSERT INTO `met_list` VALUES (222,73,'Papua New Guinea',169,'en');
INSERT INTO `met_list` VALUES (223,73,'Paraguay',170,'en');
INSERT INTO `met_list` VALUES (224,73,'Peru',171,'en');
INSERT INTO `met_list` VALUES (225,73,'Philippines',172,'en');
INSERT INTO `met_list` VALUES (226,73,'Pitcairn',173,'en');
INSERT INTO `met_list` VALUES (227,73,'Poland',174,'en');
INSERT INTO `met_list` VALUES (228,73,'Portugal',175,'en');
INSERT INTO `met_list` VALUES (229,73,'Puerto Rico',176,'en');
INSERT INTO `met_list` VALUES (230,73,'Qatar',177,'en');
INSERT INTO `met_list` VALUES (231,73,'Reunion',178,'en');
INSERT INTO `met_list` VALUES (232,73,'Romania',179,'en');
INSERT INTO `met_list` VALUES (233,73,'Russian Federation',180,'en');
INSERT INTO `met_list` VALUES (234,73,'Rwanda',181,'en');
INSERT INTO `met_list` VALUES (235,73,'Saint Kitts and Nevis',182,'en');
INSERT INTO `met_list` VALUES (236,73,'Saint Lucia',183,'en');
INSERT INTO `met_list` VALUES (237,73,'Saint Vincent and the Grenadines',184,'en');
INSERT INTO `met_list` VALUES (238,73,'Samoa',185,'en');
INSERT INTO `met_list` VALUES (239,73,'San Marino',186,'en');
INSERT INTO `met_list` VALUES (240,73,'Sao Tome and Principe',187,'en');
INSERT INTO `met_list` VALUES (241,73,'Saudi Arabia',188,'en');
INSERT INTO `met_list` VALUES (242,73,'Senegal',189,'en');
INSERT INTO `met_list` VALUES (243,73,'Serbia',190,'en');
INSERT INTO `met_list` VALUES (244,73,'Seychelles',191,'en');
INSERT INTO `met_list` VALUES (245,73,'Sierra Leone',192,'en');
INSERT INTO `met_list` VALUES (246,73,'Singapore',193,'en');
INSERT INTO `met_list` VALUES (247,73,'Slovakia (Slovak Republic)',194,'en');
INSERT INTO `met_list` VALUES (248,73,'Slovenia',195,'en');
INSERT INTO `met_list` VALUES (249,73,'Solomon Islands',196,'en');
INSERT INTO `met_list` VALUES (250,73,'Somalia',197,'en');
INSERT INTO `met_list` VALUES (251,73,'South Africa',198,'en');
INSERT INTO `met_list` VALUES (252,73,'South Korea',199,'en');
INSERT INTO `met_list` VALUES (253,73,'Spain',200,'en');
INSERT INTO `met_list` VALUES (254,73,'Sri Lanka',201,'en');
INSERT INTO `met_list` VALUES (255,73,'St. Helena',202,'en');
INSERT INTO `met_list` VALUES (256,73,'St. Pierre and Miquelon',203,'en');
INSERT INTO `met_list` VALUES (257,73,'Sudan',204,'en');
INSERT INTO `met_list` VALUES (258,73,'Suriname',205,'en');
INSERT INTO `met_list` VALUES (259,73,'Svalbard and Jan Mayen Islands',206,'en');
INSERT INTO `met_list` VALUES (260,73,'Swaziland',207,'en');
INSERT INTO `met_list` VALUES (261,73,'Sweden',208,'en');
INSERT INTO `met_list` VALUES (262,73,'Switzerland',209,'en');
INSERT INTO `met_list` VALUES (263,73,'Syrian Arab Republic',210,'en');
INSERT INTO `met_list` VALUES (264,73,'Taiwan',211,'en');
INSERT INTO `met_list` VALUES (265,73,'Tajikistan',212,'en');
INSERT INTO `met_list` VALUES (266,73,'Tanzania',213,'en');
INSERT INTO `met_list` VALUES (267,73,'Thailand',214,'en');
INSERT INTO `met_list` VALUES (268,73,'The former Yugoslav Republic of Macedonia',215,'en');
INSERT INTO `met_list` VALUES (269,73,'Togo',216,'en');
INSERT INTO `met_list` VALUES (270,73,'Tokelau',217,'en');
INSERT INTO `met_list` VALUES (271,73,'Tonga',218,'en');
INSERT INTO `met_list` VALUES (272,73,'Trinidad and Tobago',219,'en');
INSERT INTO `met_list` VALUES (273,73,'Tunisia',220,'en');
INSERT INTO `met_list` VALUES (274,73,'Turkey',221,'en');
INSERT INTO `met_list` VALUES (275,73,'Turkmenistan',222,'en');
INSERT INTO `met_list` VALUES (276,73,'Turks and Caicos Islands',223,'en');
INSERT INTO `met_list` VALUES (277,73,'Tuvalu',224,'en');
INSERT INTO `met_list` VALUES (278,73,'Uganda',225,'en');
INSERT INTO `met_list` VALUES (279,73,'Ukraine',226,'en');
INSERT INTO `met_list` VALUES (280,73,'United Arab Emirates',227,'en');
INSERT INTO `met_list` VALUES (281,73,'United Kingdom',228,'en');
INSERT INTO `met_list` VALUES (282,73,'United States',229,'en');
INSERT INTO `met_list` VALUES (283,73,'United States Minor Outlying Islands',230,'en');
INSERT INTO `met_list` VALUES (284,73,'Uruguay',231,'en');
INSERT INTO `met_list` VALUES (285,73,'Uzbekistan',232,'en');
INSERT INTO `met_list` VALUES (286,73,'Vanuatu',233,'en');
INSERT INTO `met_list` VALUES (287,73,'Vatican City State (Holy See)',234,'en');
INSERT INTO `met_list` VALUES (288,73,'Venezuela',235,'en');
INSERT INTO `met_list` VALUES (289,73,'Vietnam',236,'en');
INSERT INTO `met_list` VALUES (290,73,'Virgin Islands (British)',237,'en');
INSERT INTO `met_list` VALUES (291,73,'Virgin Islands (U.S.)',238,'en');
INSERT INTO `met_list` VALUES (292,73,'Wallis And Futuna Islands',239,'en');
INSERT INTO `met_list` VALUES (293,73,'Western Sahara',240,'en');
INSERT INTO `met_list` VALUES (294,73,'Yemen',241,'en');
INSERT INTO `met_list` VALUES (295,73,'Yugoslavia',242,'en');
INSERT INTO `met_list` VALUES (296,73,'Zambia',243,'en');
INSERT INTO `met_list` VALUES (297,73,'Zimbabwe',244,'en');
INSERT INTO `met_list` VALUES (302,41,'Sony',1,'en');
INSERT INTO `met_list` VALUES (303,41,'Haier',2,'en');
INSERT INTO `met_list` VALUES (304,41,'Toyota',3,'en');
INSERT INTO `met_list` VALUES (305,41,'TCL',4,'en');

INSERT INTO `met_message` VALUES (2,'MetInfo','','sales@metinfo.cn','','How can I get the license of MetInfo?','127.0.0.1','2010-03-10 09:09:38',1,'1, Trial satisfied or endorsed by the understanding of MetCMS enterprise content management system and related products.\r\n\r\n2, Learn more about license and service on the \"Price and services \" page , and confirm the license type to purchase.\r\n\r\n3, Contact customer service to payment.\r\n\r\n4, after payment please go to Download Center \"MetCMS commercial license customer information card\" completed and submitted to m Billiton official authorization\r\n\r\n5, the official authorization code, the program authorization documents and signature confirmation to replace the \"MetCMS commercial license for Customer Data Card\"\r\n\r\n6, the customer authorized to operate in accordance with the instructions authorized certification operation\r\n\r\n7 m extension information provided under the service level corresponding technical services\r\n','en',0,'admin');

INSERT INTO `met_news` VALUES (9,'MetCMS Enterprise Content Management System 3.0 released','','MetCMS Enterprise Content Management System 3.0 released','<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MetInfo Enterprise Content Management System is developed based on PHP+Mysql, search engine optimization(SEO) built-in Whole system and supporting user-defined interface language (the world\'s languages). MetInfo contains general moudle and function of a corporate Website (page module, news module, product modules, download module, image module, job module, message system, feedback system, on-line communication system, friendfly link module, sitemap module, member module). MetInfo focus on building marketing Enterprise website for you with powerful and flexible system management capabilities, static page generation capabilities and so on.</p>\r\n<p>&nbsp;</p>\r\n<p><strong>Main function :</strong><br />\r\n<strong>Language :<br />\r\n</strong>1, Support all languages(including Chinese,&nbsp; English, Japanese, etc.), the user can customize unlimited languages. You can visit the website with different domain to the default home page of appropriate language.<br />\r\n2, Original language pack editing function, users can easily edit the site Admin website language packs, so as to control foreground display language and language parameters (font, text size, page background, indicating number of words, etc.).</p>\r\n<p>&nbsp;</p>\r\n<p><strong>Interface Style :</strong><br />\r\n1, All text, picture,content and category can be user-defined, you can change information easy. <br />\r\n2, Original category mark control method, the administrator need only set the mark of category to display different information or category on homepage and website.<br />\r\n3, Templates and procedures are entirely separated, all languages share one template, you can also set different template and style for each language page style.<br />\r\n4,Template created simple and flexible, supporting using labeling and standard PHP syntax&nbsp; to create. <br />\r\n5, The same template supporting different color styles, while supporting a variety of page layout, users can easily switch. <br />\r\n6, Automatically generated thumbnails, you can customize pictures and text watermark which will automatically added when upload pictures.<br />\r\n7, Flash(advertising) can be different styles according to category (including the images Carousel, Flash, a single picture), and can be a variety of image carousel method. <br />\r\n8, Built-in a variety of online communication with the screen scrolling style.<br />\r\n9,Product photos and images module image can display in a variety of styles, the same product can be with unlimited pictures.<br />\r\n10, You can set flip style, information display page number, time format, popular hits of information, the latest information release days. <br />\r\n11, DIV + CSS layout, all compatible with IE6, IE7, IE8, Firefox, Google, TT, 360 degrees, traveling, and other mainstream browser.</p>\r\n<p>&nbsp;</p>\r\n<p><strong>SEO Optimization :</strong><br />\r\n1, You can set parameters and all pages SEO information such as keywords, descriptions, etc.; <br />\r\n2, Static page generation function can be automatically or manually generate&nbsp; the whole website static pages, and can personalize the name and page format of HTML. <br />\r\n3, Page title has been in accordance with &quot;Information title - cagegory name - Website Title&quot; , all the title are automatically generated. <br />\r\n4, Built-in hot tag feature, which can effectively increase website internal links and keyword links. <br />\r\n5,The official templates are designed with&nbsp; DIV+CSS,and contain all SEO technology such as H1, image ALT, hyperlink Title, page header and footer keywords.<br />\r\n6, Built-in sitemap module, can generate HTML, and the latest new xml sitemap.<br />\r\n7, Built-in Friendkly link module, you can easily complete the interconnection with other sites. <br />\r\n8, the page name and format,Category and folder of category can be customized,which can effectively distinguish between the homogenization of information on competitors, enhance the effect of SEO.</p>\r\n<p>&nbsp;</p>\r\n<p><strong>Interactive Marketing <br />\r\n</strong>1, Built-in full-line communication background management functions, you can add QQ, MSN, Alibaba, SKYPE, third-party customer communication software, and you can set the display style and icon. <br />\r\n2, Built-in powerful online feedback system, fully customizable form fields can be used for product ordering, online registration, online surveys, feedback, etc., automatically send feedback to the specified email (can be set more emails), and can be categorized in tabular form export EXCEL feedback information. <br />\r\n3, Online message&nbsp; functions, administrators can review and respond to a message through the background content.<br />\r\n4, Recruitment information release and the candidates to submit resumes online functionality.<br />\r\n5, Background built-in third-party statistical code and other tools to code interface, you can easily monitor the website and the visitor details.</p>\r\n<p>&nbsp;</p>\r\n<p><strong>Member and Rights Management :</strong><br />\r\n1, The system containts anonymous, member, agent, system administrator privileges four roles, and enables member, agent to registration.<br />\r\n2, Content, category, information pages and the field parameters can be access control, thus the flexibility to set the proxy prices, data downloads, the latest product release, etc.<br />\r\n3, Administrator rights and operational authority can be controled, which can achieve main administrators management website at the same time, and simple user interface allows administrators to understand.</p>\r\n<p>&nbsp;</p>\r\n<p><br />\r\n<strong>Safety and efficiency :</strong><br />\r\n1, Built-in database backup and restore functions, you can easily complete the entire station database backup and recovery, support configuration files and the entire station back compressed package download.<br />\r\n2, You can change the folder name of admin, and it allows you to easily manage login path of the hidden to enhance system security performance.<br />\r\n3, Validation code, anti-refresh mechanism, SQL danger symbols and statements filtering mechanism of the system greatly enhanced the ability to prevent malicious attacks. <br />\r\n4, Administrator password and member password can get back from E-mail back, that enhances system security self-help. <br />\r\n5, The installation folder, and update folder can be deleted from the background. <br />\r\n6, The efficiency of public information read&nbsp; and&nbsp; the template calls the database are set by control file (from the template creator control) ,it greatly enhanced the operational efficiency of the system.<br />\r\n7, The folder of upload and document management capabilities, you can easily manage to delete junk files.<br />\r\n8, PHP + MYSQL structure, website static functions and the system file permissions settings greatly enhanced the system against Trojan horses and malicious attacks capacity.</p>',29,43,0,0,'','',0,'admin',1,'2010-03-09 15:43:39','2010-03-09 15:43:39',0,0,'','en');
INSERT INTO `met_news` VALUES (10,'MetInfo advantage of enterprise website management system','','MetInfo advantage of enterprise website management system','<p>Compared to other enterprise website management system <br />\r\n<br />\r\n&nbsp;&nbsp;&nbsp; 1. The whole point built-in SEO search engine optimization mechanism, static pages automatically generated features, popular tags set features that make sites more easily extended to more easily indexed by search engines, easier to upgrade keywords rankings and thus easier for enterprises customers, MetInfo always believed that only with the marketing power of a corporate website is the real value of the site; <br />\r\n&nbsp;&nbsp;&nbsp; 2. Background operation simple and convenient, MetInfo enterprise website management system for corporate website follows the classic ASP background, any business, webmasters, without technical expertise, they can easily manage web sites; <br />\r\n&nbsp;&nbsp;&nbsp; 3. UTF-8 international standard codes, add the Chinese and English language and home access to automatically switch the default, Traditional Chinese prospects automatically switch to support multi-language template development; <br />\r\n&nbsp;&nbsp;&nbsp; 4. Support QQ \\ MSN \\ SKYPE \\ Taobao\'s Wangwang tools such as real-time chat online to add and background management; <br />\r\n&nbsp;&nbsp;&nbsp; 5. Flexible and powerful online feedback system, you can set the feedback form background field (support for drop-down menus and multiple-choice), while EMAIL automated response to feedback from those set by the administrator\'s mailbox automatic transmittal of the latest feedback information; <br />\r\n&nbsp;&nbsp;&nbsp; 6. Unique management system administrator privileges, you can set up an administrator sections and flexible management of permissions, <a title=\"Web\" href=\"http://www.metinfo.cn/\" target=\"_blank\" site=\"\">Web site</a> information to add, modify, delete permissions, etc.; <br />\r\n&nbsp;&nbsp;&nbsp; 7. Powerful templates to add style and switching functions, procedures and templates completely separated, the user can easily switch site in the background, foreground template; <br />\r\n&nbsp;&nbsp;&nbsp; 8. Database-backed one-button backup and restore function, external to submit anti-injection features, make the site safe and stable and easy to transfer; <br />\r\n&nbsp;&nbsp;&nbsp; 9. PHP + MYSQL framework to support multi-platform, secure and efficient; <br />\r\n&nbsp;&nbsp; 10. 100% open source code, structure, clear, simple and easy to read, secondary development and templates to create simple and convenient; <br />\r\n&nbsp;&nbsp; 11. Thumbnails automatically generated, text or image watermark automatically add function; <br />\r\n&nbsp;&nbsp; 12. Flash graphics and animation background setting function; <br />\r\n&nbsp;&nbsp; 13. 3 sections to add any features, you can control the display status section, set up a folder columns, columns order, columns sort of information, etc.; <br />\r\n&nbsp;&nbsp; 14. Supports profiles, articles, products, downloads, pictures, recruiting, message and other modules, and can be an unlimited number of calls; <br />\r\n&nbsp;&nbsp; 15. Support product, download, pictures, field settings module is called at random; <br />\r\n&nbsp;&nbsp; 16. Spare field to enable and set up features, columns home call identification features, user-friendly and more flexible design templates; <br />\r\n&nbsp;&nbsp; 17. Link On-line application and background management functions;</p>',29,43,0,0,'','',0,'admin',0,'2010-03-09 15:55:37','2010-03-09 15:55:37',0,0,'','en');
INSERT INTO `met_news` VALUES (11,'Why should we join MetInfo agent platform?','','','<p>Reason for a lower cost, the professional division of labor, increase efficiency <br />\r\n&nbsp;&nbsp;&nbsp; MetInfo range of products and services, pricing idea is &quot;low-priced products and services at reasonable charges,&quot; m extension information management system for enterprise website launched MetInfo main purpose is to rely on products to integrate a development platform, agents can use the zero-cost enterprise website MetInfo management systems for its customers Jian Zhan (such as participating in an official &quot;personalized template for a permanent business license,&quot; &quot;business authorization to acquire the space to send&quot; activities, etc.), even the direct purchase of an official permanent commercial license cost is very low. <br />\r\n&nbsp;&nbsp; Site construction industry can be specialized division of labor: the background development, style, design, maintenance services, website promotion, and the corporate <font color=\"#4b4b4b\">Web site</font> can rely on a set of functional sites mature management system to achieve the site Construction (design) companies should be more energy and inputs used to meet the customer\'s individual style, needs and service demands, m extension information in the proxy policy, virtually 100% of the personalized needs of profit and service margins give the agents, and to MetInfo enterprise website management system for platform, the joint around the agents, and ultimately achieving the professional division of labor, to improve efficiency.</p>',29,43,0,0,'','',0,'admin',0,'2010-03-09 15:57:00','2010-03-09 15:57:00',0,0,'','en');
INSERT INTO `met_news` VALUES (12,'Website Construction Industry Analysis','','','<p>1, do not pay attention to the real value of the site is too beautiful to pursue the site level: <br />\r\n<br />\r\nMost of the customer\'s point of view is the enterprise <font color=\"#4b4b4b\">Web site</font> as long as the atmosphere, beauty, line, and ignore the real value of the site - to bring customers and revenue for the enterprise, resulting in many enterprises the site is just a decoration, there are on the Internet, but few visits; <br />\r\n<br />\r\n2, the customer demands more and more Jianzhan getting lower and lower prices: <br />\r\n<br />\r\nMost of the clients always want according to their own ideas to design web site development system, but the truth is that they do not understand the web design process and to achieve the degree of difficulty, due to market competition and incentives, many sites have low-cost construction company orders and to meet the customer\'s &quot;unreasonable demands&quot;, resulting in meeting customer requirements for a construction company website at virtually no cost repeatedly modified or directly let the matter rest; <br />\r\n<br />\r\n<br />\r\n3, a large part of the corporate <font color=\"#4b4b4b\">Web site</font>s are already imitation websites, and even requirements, and have been doing exactly the same web site: <br />\r\n<br />\r\n<br />\r\n4, enterprise website management system for a wide range of: <br />\r\n<br />\r\nAnd most corporate systems are <font color=\"#4b4b4b\">Web site</font>-building company has developed or modified over, and is really suitable forand very few full-featured web site system; <br />\r\n<br />\r\n&nbsp; <br />\r\n5, Jian Zhan fee varies: <br />\r\n<br />\r\nAs the information is not blocked, Jian Zhan technology and cost, as well as the different customer requirements and build a business web site also takes costs vary widely, ranging from a few hundred to as many as tens of thousands;</p>\r\n<p>&nbsp;</p>',29,44,0,0,'','',0,'admin',0,'2010-03-09 16:03:00','2010-03-09 16:03:00',0,0,'','en');
INSERT INTO `met_news` VALUES (13,'Microsoft uses law to cripple hacker spam network','','','<p><!--{12681218680780}--></p>\r\n<p>SAN FRANCISCO (AFP) &ndash; Microsoft on Thursday said it combined technology with an &quot;extraordinary&quot; legal maneuver to cripple a massive network of hacked computers that had been flooding the Internet with spam.</p>\r\n<p>The software titan\'s Digital Crime Unit got clearance from a US judge to virtually sever the cyber criminals\' command computers from hundreds of thousands of machines worldwide infected with a Waledac virus.</p>\r\n<p>&quot;We decided the best tactic would be to literally build a wall between the bot-herder, the command computer, and all of the other computers -- effectively cutting the umbilical cord,&quot; said Microsoft attorney Richard Boscovich.</p>\r\n<p>Microsoft got a US judge to grant an ex parte temporary restraining order that let the firm erect the cyber blockade without warning bot-herders, masters of the &quot;botnet.&quot;</p>\r\n<p>&quot;It was of crucial importance that when we went out to sever the connection between the bot herder and the bots, that severing had to be done without him knowing,&quot; said Boscovich, who works in the digital crime unit.</p>\r\n<p>Microsoft drafted a complaint that made a case to the court that the damage to computer owners worldwide, and to the software firm, was major enough to warrant &quot;this rather extraordinary order,&quot; Boscovich said.</p>\r\n<p>The mission to take down one of the ten largest botnets in the United States was referred to internally at Microsoft as &quot;Operation b49.&quot;</p>\r\n<p>Waledac is estimated to have infected hundreds of thousands of computers worldwide, letting its masters mine machines for information or secretly use them to fire off spam email.</p>\r\n<p>Hackers typically infect computers with malicious codes by tricking owners into clicking on booby-trapped email messages or Internet links that plant viruses.</p>\r\n<p>Bot-herders are then free to hire out botnets for nefarious tasks such as spewing spam or overwhelming legitimate websites with myriad simultaneously requests in what are known as distributed-denial-of-service attacks.</p>\r\n<p>The Waledac botnet was believed to be capable of sending more than 1.5 billion spam email messages daily.</p>\r\n<p>During a three week period in December, Waledac-infected machines sent approximately 651 million spam email messages to users of Microsoft\'s free Hotmail service, according to the software firm.</p>\r\n<p>The spam included messages pitching online pharmacies, knock-off goods, and penny stocks.</p>\r\n<p>&quot;Three days into the effort, Operation b49 has effectively shut down connections to the vast majority of Waledac-infected computers, and our goal is to make that disruption permanent,&quot; a Microsoft lawyer said in a release.</p>\r\n<p>&quot;But the operation hasn\'t cleaned the infected computers and is not a silver bullet for undoing all the damage we believe Waledac has caused.&quot;</p>\r\n<p>Computer users are advised to purge their machines of viruses and make sure their programs and security software are up to date.</p>\r\n<p>US courts allow for hearings to decide whether temporary restraining orders should be made permanent, setting up an unlikely scenario in which bot-herders would argue for their right to reconnect with their machine minions.</p>\r\n<!--{12681218680781}--><!--{12681218680782}-->\r\n<p>Waledac is estimated to have infected hundreds of thousands of computers worldwide, letting its masters mine machines for information or secretly use them to fire off spam email.</p>\r\n<p>Hackers typically infect computers with malicious codes by tricking owners into clicking on booby-trapped email messages or Internet links that plant viruses.</p>\r\n<p>Bot-herders are then free to hire out botnets for nefarious tasks such as spewing spam or overwhelming legitimate websites with myriad simultaneously requests in what are known as distributed-denial-of-service attacks.</p>\r\n<p>The Waledac botnet was believed to be capable of sending more than 1.5 billion spam email messages daily.</p>\r\n<p>During a three week period in December, Waledac-infected machines sent approximately 651 million spam email messages to users of Microsoft\'s free Hotmail service, according to the software firm.</p>\r\n<p>The spam included messages pitching online pharmacies, knock-off goods, and penny stocks.</p>\r\n<p>&quot;Three days into the effort, Operation b49 has effectively shut down connections to the vast majority of Waledac-infected computers, and our goal is to make that disruption permanent,&quot; a Microsoft lawyer said in a release.</p>\r\n<p>&quot;But the operation hasn\'t cleaned the infected computers and is not a silver bullet for undoing all the damage we believe Waledac has caused.&quot;</p>\r\n<p>Computer users are advised to purge their machines of viruses and make sure their programs and security software are up to date.</p>\r\n<p>US courts allow for hearings to decide whether temporary restraining orders should be made permanent, setting up an unlikely scenario in which bot-herders would argue for their right to reconnect with their machine minions.</p>\r\n<!--{12681218680783}-->',29,44,0,0,'','',0,'admin',0,'2010-03-09 16:03:51','2010-03-09 16:03:51',0,0,'','en');
INSERT INTO `met_news` VALUES (14,'Why do enterprises to build multi-language, multi-lingual corporate website?','','','<p><span class=\"long_text\" id=\"result_box\"><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"互联网在不断发展壮大，已成为企业和个人寻求生意机会，对商品、服务和信息进行了解的首选方式。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\" style=\"background-color: #fff\">The Internet has continuously grown and has become the businesses and individuals to seek business opportunities for goods, services, and information about the preferred method. </span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"从站在增强一个企业竞争优势的角度看，建设一个多语言网站是不断增加客户数量的前提和提高销售的高效手段。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\" style=\"background-color: #fff\">From the stand to enhance a competitive advantage point of view, the construction of a multi-language website is the premise of ever-increasing number of customers and improve sales efficiency tools. <br />\r\n</span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"随着国际化进程的不断加快，多语言网站将成为企业和组织必不可少的一部分。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\" style=\"background-color: #fff\">With the accelerating process of internationalization, multilingual website will become an integral part of businesses and organizations. <br />\r\n</span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"多语言网站帮助企业面对众多的非英语国家互联网用户\" onmouseout=\"this.style.backgroundColor=\'#fff\'\" style=\"background-color: #fff\">Multi-language Web site to help companies face a number of Internet users of non-English-speaking countries <br />\r\n</span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"随着时间变化，非英语国家互联网用户的比例已不断在攀升。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\" style=\"background-color: #fff\">With the time-varying, non-English-speaking countries the proportion of Internet users has been on the rise. </span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"相比以前由讲英语的用户控制互联网的局面已产生了根本改变。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\" style=\"background-color: #fff\">Compared with previously performed by the English-speaking users to control the Internet has produced a fundamental change in the situation. </span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"尼尔森集团(一个美国互联网研究咨询公司)在05年3月谈到：国外互联网市场是&ldquo;将要成熟的果子&rdquo;，只要你愿意付出较少的努力就能够得到巨大的收获。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">Nelson Group (a U.S. Internet research and consulting firm) in March 2005 about: foreign Internet market is &quot;the fruit will be ripe,&quot; as long as you are willing to pay less effort can be a huge harvest. </span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"结果显示，互联网的增长在美国、德国、英国和瑞典趋于缓慢，在其他国家例如法国，香港、意大利和日本则增长显着。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">The results showed that the growth of the Internet in the United States, Germany, Britain and Sweden tend to slow, and in other countries such as France, Hong Kong, Italy and Japan increased significantly. <br />\r\n</span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"尼尔森的一位高级分析员阐述：&ldquo;最容易得到的机会是在这个国家的互联网使用习惯和用户(或站点)关系被确立之前。在当前成长阶段培养的客户将成为未来忠诚客户的基础\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">Nelson, a senior analyst explained: &quot;The most readily available opportunities are in the country\'s Internet usage and the user (or site) relationship has been firmly established. In the current culture of customer growth stage will be the basis for the future loyal customers </span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"。&rdquo;多语言网站是企业有效的营销工具有能力对多数互联网用户用他们自己的语言进行沟通，这不仅仅意味着销售的增加，更可贵的是在当地市场建立起有关您的品牌、服务和\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">. &quot;multi-language Web site is an effective marketing tool businesses have the ability for the majority of Internet users in their own language to communicate, which means more than the increase in sales, even more valuable is that in the local market to build on your brand, services, and </span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"产品的知晓。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">knowledge of the product. <br />\r\n</span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"建设多语言网站是一个非常伟大的计划，因为它很可能是企业进行市场营销，抓住新的用户，建立与新的客户关系和赋予企业品牌一个国际形象的最有效方式。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">Construction of multi-language website is a very great program, because it is likely to be business marketing, capturing new users, establish new customer relationships and to give an international image of the brand the most effective way. <br />\r\n</span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"多语言网站能为企业带来新的顾客\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">Multi-language website can bring new customers for the enterprise <br />\r\n</span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"通过把您的多语言网站暴露在各个国家，地区潜在的顾客面前，自然而然地您会获得这些本国语用户的注意。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">By exposing your multi-language Web site in various countries and regions in front of potential customers, naturally you will access to these native language the user\'s attention. <br />\r\n<br />\r\n</span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"多语言网站能够为企业增加销售\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">Multi-language Web site to increase sales for businesses <br />\r\n</span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"在网站上每增加一种语言都有可能潜在的提高一倍的销售额。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">On the website each additional language could potentially double sales. </span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"即便只把网站建成只包含有西班牙语，法语，德语和意大利语这四种世界主要语言的网站，其销售额也有可能潜在的提升4倍。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">Even if only the site contains only into Spanish, French, German and Italian, the four sites the world\'s major languages, its sales could also potentially increase four-fold. </span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"这是一种较少见的方式利用如此小的投资获得如此大的效果。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">This is a rare use of such a small investment to obtain such a large effect. <br />\r\n</span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"多语言网站能够传达以顾客为中心的服务意识\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">Multi-language Web site to convey the customer-centric service awareness <br />\r\n</span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"您的多语言网站显示出您为顾客思考。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">Your multi-language Web site shows that you are thinking for the customer. </span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"您以顾客为中心的思想及关爱顾客的努力将得到顾客的感激，因为您的这份额外的工作，他们将会更多的倾向于惠顾您的企业。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">Your customer-centric thinking and customer care efforts will be grateful to the customers, because your this extra work, they will be more inclined to patronize your business. <br />\r\n&nbsp; <br />\r\n<br />\r\n</span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"多语言网站能够获得更多的信任\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">Multi-language Web site to obtain more trust <br />\r\n</span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"许多通过互联网执行的交易往往由于彼此并不熟悉相互的语言而产生不同文化间的信任问题。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">A number of transactions executed through the Internet are often not familiar with each other due to the language of each other resulting problems of trust between different cultures. </span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"提供给顾客多语言的选择帮助他们感到安全，确切地清楚他们在如何交易，与谁交易。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">Available to the customer the choice of multiple languages to help them feel safe, they are exactly clear on how to deal with whom transactions. <br />\r\n</span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"多语言网站帮助克服文化上的敏感\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">Multi-language Web site to help overcome the cultural sensitivity <br />\r\n</span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"一个经过恰当设计的多语言网站，通过使用目标市场的本土语能够克服潜在的文化障碍。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">Through proper design of a multi-language Web site through the use of the target market\'s local language to overcome potential cultural barriers. </span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"因为多语言网站自动为客户创造了&ldquo;文化舒适区&rdquo;，使他们能够自如地导航，了解网站信息，并与您展开互动。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">Because the multi-language Web site to automatically for the customer to create a &quot;cultural comfort zone&quot; so that they can freely navigate, learn about your site information, and interact with you. <br />\r\n</span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"多语言网站能够有效打击竞争者\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">Multi-language Web site to fight efficiently against competitors <br />\r\n</span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"获得竞争优势需要在当今的环境中跳出思维的框架。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">Need to gain a competitive advantage in today\'s environment of thinking out of the framework. </span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"许多企业试图把自己与竞争者区别出来。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">Many companies try to distinguish themselves from competitors. </span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"观察您的竞争者，如果他们有多语种网站为什么您没有呢？\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">Observation of your competitors, if they are multilingual web site Why do you not? </span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"假若他们没有，为什么不在他们之前主导这个市场首先建立你公司的品牌呢？\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">If they do not, why should not they dominated this market prior to first establish your company\'s branding? <br />\r\n&nbsp; <br />\r\n<br />\r\n</span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"多语言网站展示企业的国际性风范\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">Multi-language Web site of the international style of show business <br />\r\n</span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"一个多语种网站展示您的思想，经营及国际性的业务流程。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">A multilingual Web site to display your ideas, business and international business processes. </span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"国际性企业形象及行业领导地位由此树立多语言网站帮助面向不同地域国家的查寻引擎\" onmouseout=\"this.style.backgroundColor=\'#fff\'\" style=\"background-color: #fff\">International corporate image and establish industry leadership in this multi-language Web site to help search for the different regional countries, engines <br />\r\n</span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"搜索引擎会带着人们来到您的站点。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\" style=\"background-color: #fff\">Search engine will bring a people to come to your site. </span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"然而在一些国家和地区有他们自己受欢迎的搜索引擎，主要是这些搜索引擎依据母语的使用习惯来工作，适应了人们的需要，所以获得了成功。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\" style=\"background-color: #fff\">However, in some countries and regions have their own popular search engines, these search engines are mainly based on the use of mother tongue to work habits to adapt to people\'s needs, it is a success. </span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"这类搜索引擎引擎是开启本地市场的钥匙，除此之外，除非他们能够使用一种特定的语言(比如英语)否则很难找到您。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\" style=\"background-color: #fff\">Such search engines engine is the key to open the local market, in addition, unless they be able to use a particular language (eg English) would be difficult to find you. <br />\r\n<br />\r\n</span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"另外，许多关键字搜索引擎，尤其是Google，在多语言开发方面能力优异。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\" style=\"background-color: #fff\">In addition, many keyword search engines, particularly Google, in a multi-language development capacity excellent. </span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"拥有多语言页面的网站能够最大限度的保障您的网站能够被众多搜索引擎检索并展示。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\" style=\"background-color: #fff\">Has a multi-language page of the site to maximize the protection of your website many search engines that can be retrieved and displayed. </span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"事务总是在不断地转移和变化。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\" style=\"background-color: #fff\">Service is always constantly shift and change. </span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"当前多语言网站仍处在早期阶段，许多跨国公司使用多语言网站来巩固其国际地位。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\" style=\"background-color: #fff\">The current multi-language Web site is still in its early stages, many multinational companies use multi-language Web site to consolidate its international status. </span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"然而，接下来的影响将自然地发生，多语言网站将成为互联网存在的主要部分。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\">However, the next impact will occur naturally, multi-language site will be a major part of the Internet presence. </span><span onmouseover=\"this.style.backgroundColor=\'#ebeff9\'\" title=\"不管企业是选择现在或将来，这都是网站建设的唯一选择。\" onmouseout=\"this.style.backgroundColor=\'#fff\'\" style=\"background-color: #fff\">Whether an organization is to choose now or in the future, this is the only choice for web site construction. <br />\r\n</span></span></p>',29,44,0,0,'','',0,'admin',1,'2010-03-09 16:05:33','2010-03-09 16:05:33',0,0,'','en');

INSERT INTO `met_online` VALUES (3,'Sales',1,'','metinfo@metinfo.cn','','','','en');
INSERT INTO `met_online` VALUES (4,'Business ',2,'','navyok@hotmail.com','','','metinfo','en');

INSERT INTO `met_otherinfo` VALUES (3,' <font color=#708090>PHP+MYSQL / DIV+CSS / SEO / Multilingual / Easy / Powerful / Security / stability </font>  |  <font color=#003366>   <b>MetInfo</b></font> -  Build High-quality corporate website for you!  ','sales@metinfo.cn','','','','','','','','<p><strong>MetInfo Co.,Ltd</strong><br />\r\n<strong>Add</strong>：No 416,Furong Road, Tianxin area, Changsha City <br />\r\n<strong>Tel</strong>：0731-87133078<br />\r\n<strong>Mobile</strong>：13888888888<br />\r\n<strong>Fax</strong>：0731-84476708<br />\r\n<strong>QQ</strong>：348468810 426507856<br />\r\n<strong>Code</strong>：410015<br />\r\n<strong>Email</strong>：sales@metinfo.cn<br />\r\n<strong>Web</strong>：www.MetInfo.cn</p>','','',NULL,NULL,NULL,NULL,NULL,NULL,'en');

INSERT INTO `met_parameter` VALUES (40,'Model',1,1,0,0,0,3,'en');
INSERT INTO `met_parameter` VALUES (41,'Brand',2,2,0,0,0,3,'en');
INSERT INTO `met_parameter` VALUES (42,'Price',3,1,1,0,0,3,'en');
INSERT INTO `met_parameter` VALUES (43,'Image1',4,5,0,0,0,3,'en');
INSERT INTO `met_parameter` VALUES (44,'Image2',5,5,0,0,0,3,'en');
INSERT INTO `met_parameter` VALUES (45,'Image3',6,5,0,0,0,3,'en');
INSERT INTO `met_parameter` VALUES (46,'File Version',1,1,0,0,0,4,'en');
INSERT INTO `met_parameter` VALUES (47,'File Type',2,1,0,0,0,4,'en');
INSERT INTO `met_parameter` VALUES (48,'Case Picture 1',1,5,0,0,0,5,'en');
INSERT INTO `met_parameter` VALUES (49,'Case Picture 2',2,5,0,0,0,5,'en');
INSERT INTO `met_parameter` VALUES (50,'Case Picture 3',3,5,0,0,0,5,'en');
INSERT INTO `met_parameter` VALUES (51,'Name',1,1,0,1,0,6,'en');
INSERT INTO `met_parameter` VALUES (52,'Sex',2,6,0,0,0,6,'en');
INSERT INTO `met_parameter` VALUES (53,'Birth day',3,1,0,0,0,6,'en');
INSERT INTO `met_parameter` VALUES (54,'National',4,1,0,0,0,6,'en');
INSERT INTO `met_parameter` VALUES (55,'Tel',5,1,0,0,0,6,'en');
INSERT INTO `met_parameter` VALUES (56,'Mobile',6,1,0,0,0,6,'en');
INSERT INTO `met_parameter` VALUES (57,'Email',7,1,0,1,0,6,'en');
INSERT INTO `met_parameter` VALUES (58,'Education',8,1,0,0,0,6,'en');
INSERT INTO `met_parameter` VALUES (59,'Professional',9,1,0,0,0,6,'en');
INSERT INTO `met_parameter` VALUES (60,'Graduate school',10,1,0,0,0,6,'en');
INSERT INTO `met_parameter` VALUES (61,'Address',11,1,0,0,0,6,'en');
INSERT INTO `met_parameter` VALUES (62,'Technical qualifications and special skills',12,3,0,0,0,6,'en');
INSERT INTO `met_parameter` VALUES (63,'Work experience ',13,3,0,0,0,6,'en');
INSERT INTO `met_parameter` VALUES (64,'Hobbies/interests',14,3,0,0,0,6,'en');
INSERT INTO `met_parameter` VALUES (65,'Type ',1,2,0,1,NULL,8,'en');
INSERT INTO `met_parameter` VALUES (66,'Subject',2,1,0,1,NULL,8,'en');
INSERT INTO `met_parameter` VALUES (67,'Name',3,1,0,0,NULL,8,'en');
INSERT INTO `met_parameter` VALUES (68,'Email',4,1,0,1,NULL,8,'en');
INSERT INTO `met_parameter` VALUES (69,'Tel',5,1,0,0,NULL,8,'en');
INSERT INTO `met_parameter` VALUES (70,'MSN',6,1,0,0,NULL,8,'en');
INSERT INTO `met_parameter` VALUES (71,'Skype',7,1,0,0,NULL,8,'en');
INSERT INTO `met_parameter` VALUES (72,'Company Name',8,1,0,0,NULL,8,'en');
INSERT INTO `met_parameter` VALUES (73,'Country',9,2,0,0,NULL,8,'en');
INSERT INTO `met_parameter` VALUES (74,'Detail',10,3,0,0,NULL,8,'en');
INSERT INTO `met_parameter` VALUES (75,'How did you find us',11,4,0,0,NULL,8,'en');

INSERT INTO `met_plist` VALUES (39,5,40,'x-9090','en','',3);
INSERT INTO `met_plist` VALUES (40,5,41,'Sony','en','',3);
INSERT INTO `met_plist` VALUES (41,5,42,'$120','en','',3);
INSERT INTO `met_plist` VALUES (42,5,43,'','en','',3);
INSERT INTO `met_plist` VALUES (43,5,44,'','en','',3);
INSERT INTO `met_plist` VALUES (44,5,45,'','en','',3);
INSERT INTO `met_plist` VALUES (45,6,40,'X800-4','en','',3);
INSERT INTO `met_plist` VALUES (46,6,41,'Haier','en','',3);
INSERT INTO `met_plist` VALUES (47,6,42,'$200','en','',3);
INSERT INTO `met_plist` VALUES (48,6,43,'','en','',3);
INSERT INTO `met_plist` VALUES (49,6,44,'','en','',3);
INSERT INTO `met_plist` VALUES (50,6,45,'','en','',3);
INSERT INTO `met_plist` VALUES (51,7,40,'k-500','en','',3);
INSERT INTO `met_plist` VALUES (52,7,41,'Haier','en','',3);
INSERT INTO `met_plist` VALUES (53,7,42,'$500','en','',3);
INSERT INTO `met_plist` VALUES (54,7,43,'','en','',3);
INSERT INTO `met_plist` VALUES (55,7,44,'','en','',3);
INSERT INTO `met_plist` VALUES (56,7,45,'','en','',3);
INSERT INTO `met_plist` VALUES (57,8,40,'D-s808','en','',3);
INSERT INTO `met_plist` VALUES (58,8,41,'Toyota','en','',3);
INSERT INTO `met_plist` VALUES (59,8,42,'$3000','en','',3);
INSERT INTO `met_plist` VALUES (60,8,43,'../upload/201003/watermark/1268127446.jpg','en','Demo picture 1',3);
INSERT INTO `met_plist` VALUES (61,8,44,'../upload/201003/watermark/1268127045.jpg','en','Demo picture 2',3);
INSERT INTO `met_plist` VALUES (62,8,45,'../upload/201003/watermark/1268127303.jpg','en','Demo picture 3',3);
INSERT INTO `met_plist` VALUES (63,5,48,'','en','',5);
INSERT INTO `met_plist` VALUES (64,5,49,'','en','',5);
INSERT INTO `met_plist` VALUES (65,5,50,'','en','',5);
INSERT INTO `met_plist` VALUES (66,6,48,'','en','',5);
INSERT INTO `met_plist` VALUES (67,6,49,'','en','',5);
INSERT INTO `met_plist` VALUES (68,6,50,'','en','',5);
INSERT INTO `met_plist` VALUES (69,7,48,'','en','',5);
INSERT INTO `met_plist` VALUES (70,7,49,'','en','',5);
INSERT INTO `met_plist` VALUES (71,7,50,'','en','',5);
INSERT INTO `met_plist` VALUES (72,8,48,'../upload/201003/watermark/1268127446.jpg','en','Picture 1',5);
INSERT INTO `met_plist` VALUES (73,8,49,'../upload/201003/watermark/1268127045.jpg','en','Picture 2',5);
INSERT INTO `met_plist` VALUES (74,8,50,'../upload/201003/watermark/1268127303.jpg','en','Picture 3',5);
INSERT INTO `met_plist` VALUES (75,2,46,'V3.0','en','',4);
INSERT INTO `met_plist` VALUES (76,2,47,'Software','en','',4);

INSERT INTO `met_product` VALUES (5,'Handheld Camera','','','<p>Support all languages(including Chinese,&nbsp; English, Japanese, etc.), the user can customize unlimited languages. You can visit the website with different domain to the default home page of appropriate language.<br />\r\n&nbsp;</p>',30,45,0,0,'../upload/201003/watermark/1268122961.jpg','../upload/201003/thumb/1268122961.jpg',1,3,'2010-03-09 16:44:33','2010-03-09 16:06:37','admin',0,0,'','en',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `met_product` VALUES (6,'X800-4 Notebook','','','<p>Most of the clients always want according to their own ideas to design web site development system, but the truth is that they do not understand the web design process and to achieve the degree of difficulty, due to market competition and incentives, many sites have low-cost construction company orders and to meet the customer\'s &quot;unreasonable demands&quot;, resulting in meeting customer requirements for a construction company website at virtually no cost repeatedly modified or directly let the matter rest;</p>',30,45,51,0,'../upload/201003/watermark/1268124560.jpg','../upload/201003/thumb/1268124560.jpg',1,3,'2010-03-09 16:44:47','2010-03-09 16:36:48','admin',0,0,'','en',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `met_product` VALUES (7,'Furniture, building materials product demo','','','<p>And most corporate systems are <font color=\"#4b4b4b\">Web site</font>-building company has developed or modified over, and is really suitable forand very few full-featured web site system; <br />\r\n&nbsp;</p>',30,46,0,0,'../upload/201003/watermark/1268124790.jpg','../upload/201003/thumb/1268124790.jpg',1,3,'2010-03-09 16:44:59','2010-03-09 16:40:14','admin',0,0,'','en',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `met_product` VALUES (8,'Auto Demo Products','','','<p>As the information is not blocked, Jian Zhan technology and cost, as well as the different customer requirements and build a business web site also takes costs vary widely, ranging from a few hundred to as many as tens of thousands;</p>',30,47,0,0,'../upload/201003/watermark/1268124633.jpg','../upload/201003/thumb/1268124633.jpg',1,7,'2010-03-09 16:45:27','2010-03-09 16:45:27','admin',0,0,'','en',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);


