INSERT INTO met_lang VALUES('4','English','1','2','en','en','en.gif','','0','0','html','http://192.168.1.181/metv52/','en');
INSERT INTO met_config VALUES('205','metconfig_cv_time','120','','0','0','en');
INSERT INTO met_config VALUES('206','metconfig_cv_word','','','0','0','en');
INSERT INTO met_config VALUES('207','metconfig_cv_type','1','','0','0','en');
INSERT INTO met_config VALUES('208','metconfig_cv_image','0','','0','0','en');
INSERT INTO met_config VALUES('209','metconfig_cv_emtype','1','','0','0','en');
INSERT INTO met_config VALUES('210','metconfig_cv_to','','','0','0','en');
INSERT INTO met_config VALUES('211','metconfig_wap','1','','0','0','en');
INSERT INTO met_config VALUES('212','metconfig_waplink','1','','0','0','en');
INSERT INTO met_config VALUES('213','metconfig_wap_ok','0','','0','0','en');
INSERT INTO met_config VALUES('214','metconfig_wap_tpa','1','','0','0','en');
INSERT INTO met_config VALUES('215','metconfig_wap_tpb','0','','0','0','en');
INSERT INTO met_config VALUES('216','metconfig_wap_url','','','0','0','en');
INSERT INTO met_config VALUES('217','metconfig_wap_logo','../upload/201207/1342516579.png','','0','0','en');
INSERT INTO met_config VALUES('218','metconfig_wap_img','../upload/201207/1342516476.jpg','','0','0','en');
INSERT INTO met_config VALUES('219','wap_news_list','5','','0','0','en');
INSERT INTO met_config VALUES('220','wap_product_list','5','','0','0','en');
INSERT INTO met_config VALUES('221','wap_download_list','5','','0','0','en');
INSERT INTO met_config VALUES('222','wap_img_list','5','','0','0','en');
INSERT INTO met_config VALUES('223','wap_job_list','5','','0','0','en');
INSERT INTO met_config VALUES('224','wap_product_imgx','200','','0','0','en');
INSERT INTO met_config VALUES('225','wap_product_imgy','200','','0','0','en');
INSERT INTO met_config VALUES('226','wap_img_imgx','240','','0','0','en');
INSERT INTO met_config VALUES('227','wap_img_imgy','200','','0','0','en');
INSERT INTO met_config VALUES('228','wap_title','Mobile Website','','0','0','en');
INSERT INTO met_config VALUES('229','wap_description','','','0','0','en');
INSERT INTO met_config VALUES('230','wap_footertext','','','0','0','en');
INSERT INTO met_config VALUES('231','metconfig_weburl','http://192.168.1.181/metv52/','','0','0','en');
INSERT INTO met_config VALUES('232','metconfig_webname','Website Name','','0','0','en');
INSERT INTO met_config VALUES('233','metconfig_logo','../upload/201207/1342516529.png','','0','0','en');
INSERT INTO met_config VALUES('234','metconfig_skin_user','metx5','','0','0','en');
INSERT INTO met_config VALUES('235','metconfig_big_wate','0','','0','0','en');
INSERT INTO met_config VALUES('236','metconfig_thumb_wate','0','','0','0','en');
INSERT INTO met_config VALUES('237','metconfig_wate_class','1','','0','0','en');
INSERT INTO met_config VALUES('238','metconfig_wate_img','','','0','0','en');
INSERT INTO met_config VALUES('239','metconfig_wate_bigimg','','','0','0','en');
INSERT INTO met_config VALUES('240','metconfig_thumb_kind','2','','0','0','en');
INSERT INTO met_config VALUES('241','metconfig_text_wate','www.MetInfo.cn','','0','0','en');
INSERT INTO met_config VALUES('242','metconfig_text_size','10','','0','0','en');
INSERT INTO met_config VALUES('243','metconfig_text_bigsize','15','','0','0','en');
INSERT INTO met_config VALUES('244','metconfig_text_fonts','../include/fonts/arial.ttf','','0','0','en');
INSERT INTO met_config VALUES('245','metconfig_text_color','#808080','','0','0','en');
INSERT INTO met_config VALUES('246','metconfig_text_angle','0','','0','0','en');
INSERT INTO met_config VALUES('247','metconfig_watermark','0','','0','0','en');
INSERT INTO met_config VALUES('248','metconfig_img_style','1','','0','0','en');
INSERT INTO met_config VALUES('249','metconfig_img_x','150','','0','0','en');
INSERT INTO met_config VALUES('250','metconfig_img_y','150','','0','0','en');
INSERT INTO met_config VALUES('251','metconfig_newsimg_x','90','','0','0','en');
INSERT INTO met_config VALUES('252','metconfig_newsimg_y','90','','0','0','en');
INSERT INTO met_config VALUES('253','metconfig_productimg_x','213','','0','0','en');
INSERT INTO met_config VALUES('254','metconfig_productimg_y','160','','0','0','en');
INSERT INTO met_config VALUES('255','metconfig_imgs_x','210','','0','0','en');
INSERT INTO met_config VALUES('256','metconfig_imgs_y','210','','0','0','en');
INSERT INTO met_config VALUES('257','metconfig_keywords','Website Keywords','','0','0','en');
INSERT INTO met_config VALUES('258','metconfig_description','MetInfo enterprise content manager system','','0','0','en');
INSERT INTO met_config VALUES('259','metconfig_title_type','2','','0','0','en');
INSERT INTO met_config VALUES('260','metconfig_tools_ok','0','','0','0','en');
INSERT INTO met_config VALUES('261','metconfig_tools_code','','','0','0','en');
INSERT INTO met_config VALUES('262','metconfig_alt','MetInfo enterprise content manager system | MetInfo CMS','','0','0','en');
INSERT INTO met_config VALUES('263','metconfig_atitle','MetInfo CMS','','0','0','en');
INSERT INTO met_config VALUES('264','metconfig_linkname','MetInfo CMS','','0','0','en');
INSERT INTO met_config VALUES('265','metconfig_online_type','3','','0','0','en');
INSERT INTO met_config VALUES('266','metconfig_footaddress','','','0','0','en');
INSERT INTO met_config VALUES('267','metconfig_foottel','','','0','0','en');
INSERT INTO met_config VALUES('268','metconfig_footother','','','0','0','en');
INSERT INTO met_config VALUES('269','metconfig_foottext','','','0','0','en');
INSERT INTO met_config VALUES('270','metconfig_product_list','6','','0','0','en');
INSERT INTO met_config VALUES('271','metconfig_news_list','8','','0','0','en');
INSERT INTO met_config VALUES('272','metconfig_download_list','10','','0','0','en');
INSERT INTO met_config VALUES('273','metconfig_img_list','12','','0','0','en');
INSERT INTO met_config VALUES('274','metconfig_job_list','2','','0','0','en');
INSERT INTO met_config VALUES('275','metconfig_message_list','10','','0','0','en');
INSERT INTO met_config VALUES('276','metconfig_search_list','10','','0','0','en');
INSERT INTO met_config VALUES('277','metconfig_fd_fromname','MetInfo Co.,Ltd','','0','0','en');
INSERT INTO met_config VALUES('278','metconfig_fd_smtp','61.152.188.131','','0','0','en');
INSERT INTO met_config VALUES('279','metconfig_fd_usename','test@mail.metinfo.cn','','0','0','en');
INSERT INTO met_config VALUES('280','metconfig_fd_password','123456','','0','0','en');
INSERT INTO met_config VALUES('281','metconfig_skin_css','metinfo.css','','0','0','en');
INSERT INTO met_config VALUES('282','metconfig_autothumb_ok','1','','0','0','en');
INSERT INTO met_config VALUES('283','metconfig_member_use','1','','0','0','en');
INSERT INTO met_config VALUES('284','metconfig_member_register','1','','0','0','en');
INSERT INTO met_config VALUES('285','metconfig_newsdays','3','','0','0','en');
INSERT INTO met_config VALUES('286','metconfig_hot','100','','0','0','en');
INSERT INTO met_config VALUES('287','metconfig_listtime','Y/m/d','','0','0','en');
INSERT INTO met_config VALUES('288','metconfig_contenttime','Y-m-d H:i:s','','0','0','en');
INSERT INTO met_config VALUES('289','metconfig_member_vecan','4','','0','0','en');
INSERT INTO met_config VALUES('290','metconfig_membercontrol','Welcome to register the member of【MetInfo】www.metinfo.cn, after activated you can enjoy more professional service!','','0','0','en');
INSERT INTO met_config VALUES('291','metconfig_pseudo','0','','0','0','en');
INSERT INTO met_config VALUES('292','metconfig_online_skin','3','','0','0','en');
INSERT INTO met_config VALUES('293','metconfig_online_color','1','','0','0','en');
INSERT INTO met_config VALUES('294','metconfig_qq_type','4','','0','0','en');
INSERT INTO met_config VALUES('295','metconfig_msn_type','1','','0','0','en');
INSERT INTO met_config VALUES('296','metconfig_taobao_type','2','','0','0','en');
INSERT INTO met_config VALUES('297','metconfig_alibaba_type','10','','0','0','en');
INSERT INTO met_config VALUES('298','metconfig_skype_type','13','','0','0','en');
INSERT INTO met_config VALUES('299','metconfig_addlinkopen','1','','0','0','en');
INSERT INTO met_config VALUES('300','metconfig_pageskin','8','','0','0','en');
INSERT INTO met_config VALUES('301','metconfig_indexskin','index','','0','0','en');
INSERT INTO met_config VALUES('302','metconfig_urlblank','0','','0','0','en');
INSERT INTO met_config VALUES('303','metconfig_pnorder','0','','0','0','en');
INSERT INTO met_config VALUES('304','metconfig_hitsok','1','','0','0','en');
INSERT INTO met_config VALUES('305','metconfig_product_page','0','','0','0','en');
INSERT INTO met_config VALUES('306','metconfig_img_page','0','','0','0','en');
INSERT INTO met_config VALUES('307','metconfig_product_detail','1','','0','0','en');
INSERT INTO met_config VALUES('308','metconfig_img_detail','1','','0','0','en');
INSERT INTO met_config VALUES('309','metconfig_productdetail_x','400','','0','0','en');
INSERT INTO met_config VALUES('310','metconfig_productdetail_y','300','','0','0','en');
INSERT INTO met_config VALUES('311','metconfig_imgdetail_x','900','','0','0','en');
INSERT INTO met_config VALUES('312','metconfig_imgdetail_y','500','','0','0','en');
INSERT INTO met_config VALUES('313','metconfig_onlineright_top','118','','0','0','en');
INSERT INTO met_config VALUES('314','metconfig_onlineright_right','0','','0','0','en');
INSERT INTO met_config VALUES('315','metconfig_onlineleft_top','118','','0','0','en');
INSERT INTO met_config VALUES('316','metconfig_onlineleft_left','0','','0','0','en');
INSERT INTO met_config VALUES('317','metconfig_onlinenameok','','','0','0','en');
INSERT INTO met_config VALUES('318','metconfig_file_format','rar|zip|sql|doc|pdf|jpg|jpeg|xls|png|gif|mp3|ico|swf','','0','0','en');
INSERT INTO met_config VALUES('319','metconfig_file_maxsize','5','','0','0','en');
INSERT INTO met_config VALUES('320','metconfig_memberlogin_code','1','','0','0','en');
INSERT INTO met_config VALUES('321','metconfig_login_code','0','','0','0','en');
INSERT INTO met_config VALUES('322','metconfig_webhtm','0','','0','0','en');
INSERT INTO met_config VALUES('323','metconfig_htmtype','html','','0','0','en');
INSERT INTO met_config VALUES('324','metconfig_htmpagename','2','','0','0','en');
INSERT INTO met_config VALUES('325','metconfig_listhtmltype','1','','0','0','en');
INSERT INTO met_config VALUES('326','metconfig_htmlistname','1','','0','0','en');
INSERT INTO met_config VALUES('327','metconfig_htmway','0','','0','0','en');
INSERT INTO met_config VALUES('328','index_news_no','2','','0','0','en');
INSERT INTO met_config VALUES('329','index_product_no','10','','0','0','en');
INSERT INTO met_config VALUES('330','index_download_no','10','','0','0','en');
INSERT INTO met_config VALUES('331','index_img_no','10','','0','0','en');
INSERT INTO met_config VALUES('332','index_job_no','10','','0','0','en');
INSERT INTO met_config VALUES('333','index_link_ok','1','','0','0','en');
INSERT INTO met_config VALUES('334','index_link_img','9999','','0','0','en');
INSERT INTO met_config VALUES('335','index_link_text','9999','','0','0','en');
INSERT INTO met_config VALUES('336','metconfig_pageclick','0','','0','0','en');
INSERT INTO met_config VALUES('337','metconfig_pagetime','0','','0','0','en');
INSERT INTO met_config VALUES('338','metconfig_pageprint','0','','0','0','en');
INSERT INTO met_config VALUES('339','metconfig_pageclose','0','','0','0','en');
INSERT INTO met_config VALUES('340','metconfig_deleteimg','0','','0','0','en');
INSERT INTO met_config VALUES('341','metconfig_columnshow','0','','0','0','en');
INSERT INTO met_config VALUES('342','metconfig_onlinetel','','','0','0','en');
INSERT INTO met_config VALUES('343','metconfig_kzqie','1','','0','0','en');
INSERT INTO met_config VALUES('344','metconfig_seo','<p><a href=\"http://www.metinfo.cn/\" target=\"_blank\">MetInfo CMS</a> | <a href=\"http://www.metinfo.cn/idc\" target=\"_blank\">Foreign Host</a> | <a href=\"http://ok.metinfo.cn/\" target=\"_blank\">Domain Registration</a></p>','','0','0','en');
INSERT INTO met_config VALUES('345','metconfig_footright','MSN:0000@000.com Email:sales@metinfo.cn','','0','0','en');
INSERT INTO met_config VALUES('346','metconfig_footstat','','','0','0','en');
INSERT INTO met_config VALUES('528','metconfig_cv_back','0','','0','0','en');
INSERT INTO met_config VALUES('529','metconfig_cv_title','','','0','0','en');
INSERT INTO met_config VALUES('530','metconfig_cv_content','','','0','0','en');
INSERT INTO met_config VALUES('531','metconfig_cv_email','49','','0','0','en');
INSERT INTO met_config VALUES('532','index_hadd_ok','1','','0','0','en');
INSERT INTO met_config VALUES('536','metconfig_hometitle','','','0','0','en');
INSERT INTO met_config VALUES('538','metconfig_img_rename','1','','0','0','en');
INSERT INTO met_config VALUES('560','metconfig_index_content','<p><span style=\"color: rgb(102, 102, 102); -webkit-text-size-adjust: none; \">MetInfo Co., Ltd. (</span><a href=\"http://www.metinfo.cn/\" style=\"color: rgb(28, 87, 196); -webkit-text-size-adjust: none; \" target=\"_blank\">MetInfo.cn</a><span style=\"color: rgb(102, 102, 102); -webkit-text-size-adjust: none; \">) focused on the field of network information and network marketing, integrated team of professional marketing ideas and networking technologies to provide customers with high quality online marketing services.</span></p>','','0','0','en');
INSERT INTO met_config VALUES('582','wap_skin_user','metx5_mobile','','0','0','en');
INSERT INTO met_config VALUES('583','wap_search_list','5','','0','0','en');
INSERT INTO met_config VALUES('584','wap_message_list','5','','0','0','en');
INSERT INTO met_config VALUES('585','wap_index_content','<img alt=\"\" src=\"web_metinfo_urlupload/images/20131228_183101.jpg\" style=\"width: 150px; height: 100px; float: left; margin-left: 8px; margin-right: 8px;\" />MetInfo believe all our customers, suppliers, shareholders, employees and other cooperative relations and their own units and individuals are their partners, and only through efforts to create value for partners in order to realize their own value and access to development and success.','','0','0','en');
INSERT INTO met_config VALUES('586','wap_skin_css','black.css','','0','0','en');
INSERT INTO met_config VALUES('587','metconfig_fd_port','25','','0','0','en');
INSERT INTO met_config VALUES('588','metconfig_fd_way','tls','','0','0','en');
INSERT INTO met_config VALUES('589','metconfig_headstat','','','0','0','en');
INSERT INTO met_config VALUES('590','metconfig_automatic_upgrade','1','','0','0','en');
INSERT INTO met_config VALUES('591','metconfig_sitemap_auto','1','','0','0','en');
INSERT INTO met_config VALUES('592','metconfig_maplng','116.404','','0','0','en');
INSERT INTO met_config VALUES('593','metconfig_maplat','39.915','','0','0','en');
INSERT INTO met_config VALUES('594','metconfig_mapzoom','15','','0','0','en');
INSERT INTO met_config VALUES('595','metconfig_maptitle','Demonstration Company Name','','0','0','en');
INSERT INTO met_config VALUES('596','metconfig_mapcontents','Address: Yuelu District, some 518 South Second Ring Road Metro 3-17 Sunshine 100 International Building 803 # <br/> Tel :0000-88888888 0000-8888888','','0','0','en');
INSERT INTO met_config VALUES('598','wap_dimensional_size','200','0','0','0','en');
INSERT INTO met_config VALUES('600','metconfig_dimensional_logo','','','0','0','en');
INSERT INTO met_config VALUES('870','metconfig_menu_ok','1','','0','0','en');
INSERT INTO met_config VALUES('871','metconfig_menu_oks','1','','0','0','en');
INSERT INTO met_config VALUES('872','metconfig_menu_rgb','#e9280c','','0','0','en');
INSERT INTO met_config VALUES('873','metconfig_menu_bg','','','0','0','en');
INSERT INTO met_config VALUES('874','metconfig_menu_textbg','#ffffff','','0','0','en');
INSERT INTO met_config VALUES('882','metconfig_wapshowtype','0','','0','0','en');
INSERT INTO met_config VALUES('885','metconfig_bannerpagetype','0','','0','0','en');
INSERT INTO met_config VALUES('886','metconfig_theme_preview','','','0','0','en');
INSERT INTO met_config VALUES('895', 'metconfig_productTabname', 'Detailed information', '', '0', '0', 'en');
INSERT INTO met_config VALUES('896', 'metconfig_productTabname_1', 'Tab two', '', '0', '0', 'en');
INSERT INTO met_config VALUES('897', 'metconfig_productTabname_2', 'Tab three', '', '0', '0', 'en');
INSERT INTO met_config VALUES('898', 'metconfig_productTabname_3', 'Tab four', '', '0', '0', 'en');
INSERT INTO met_config VALUES('899', 'metconfig_productTabname_4', 'Tab five', '', '0', '0', 'en');
INSERT INTO met_config VALUES('900', 'metconfig_productTabok', '1', '', '0', '0', 'en');
INSERT INTO met_config VALUES('916', 'metconfig_htmlurl', '0', '', '0', '0', 'en');
INSERT INTO met_language VALUES('4016','system','system parameter','0','1','0','0','en');
INSERT INTO met_language VALUES('4017','sunday','Sunday','0','1','1','0','en');
INSERT INTO met_language VALUES('4018','monday','Monday','0','2','1','0','en');
INSERT INTO met_language VALUES('4019','tuesday','Tuesday','0','3','1','0','en');
INSERT INTO met_language VALUES('4020','wednesday','Wednesday','0','4','1','0','en');
INSERT INTO met_language VALUES('4021','thursday','Thursday','0','5','1','0','en');
INSERT INTO met_language VALUES('4022','friday','Friday','0','6','1','0','en');
INSERT INTO met_language VALUES('4023','saturday','Saturday','0','7','1','0','en');
INSERT INTO met_language VALUES('4024','now','','0','8','1','0','en');
INSERT INTO met_language VALUES('4025','year','-','0','9','1','0','en');
INSERT INTO met_language VALUES('4026','month','-','0','10','1','0','en');
INSERT INTO met_language VALUES('4027','day','','0','11','1','0','en');
INSERT INTO met_language VALUES('4028','sethomepage','HomePage','0','12','1','0','en');
INSERT INTO met_language VALUES('4029','bookmark','BookMark','0','13','1','0','en');
INSERT INTO met_language VALUES('4030','chchinese','繁体中文','0','14','1','0','en');
INSERT INTO met_language VALUES('4031','searchall','All Web','0','15','1','0','en');
INSERT INTO met_language VALUES('4032','search','search','0','16','1','0','en');
INSERT INTO met_language VALUES('4033','home','Home','0','17','1','0','en');
INSERT INTO met_language VALUES('4034','error','Error','0','18','1','0','en');
INSERT INTO met_language VALUES('4035','success','Success!','0','19','1','0','en');
INSERT INTO met_language VALUES('4036','Info1','enterprise website manager system','0','20','1','0','en');
INSERT INTO met_language VALUES('4037','Info2','CMS','0','21','1','0','en');
INSERT INTO met_language VALUES('4038','Info3','CMS','0','22','1','0','en');
INSERT INTO met_language VALUES('4039','Colunm','Colunm Name','0','23','1','0','en');
INSERT INTO met_language VALUES('4040','Title','Title','0','24','1','0','en');
INSERT INTO met_language VALUES('4041','Content','Content','0','25','1','0','en');
INSERT INTO met_language VALUES('4042','Hits','Hits','0','26','1','0','en');
INSERT INTO met_language VALUES('4043','UpdateTime','UpdateTime','0','27','1','0','en');
INSERT INTO met_language VALUES('4044','Detail','Detail','0','28','1','0','en');
INSERT INTO met_language VALUES('4045','Close','Close','0','29','1','0','en');
INSERT INTO met_language VALUES('4046','Online','Service','0','30','1','0','en');
INSERT INTO met_language VALUES('4047','Online_tips','Click to hide','0','31','1','0','en');
INSERT INTO met_language VALUES('4048','Noinfo','No Information','0','32','1','0','en');
INSERT INTO met_language VALUES('4049','Buy','Feedback','0','33','1','0','en');
INSERT INTO met_language VALUES('4050','ProductTitle','Product Name','0','34','1','0','en');
INSERT INTO met_language VALUES('4051','BigPicture','Big Picture','0','35','1','0','en');
INSERT INTO met_language VALUES('4052','ImgTitle','Images Name','0','36','1','0','en');
INSERT INTO met_language VALUES('4053','ProductSearch','Product Search','0','37','1','0','en');
INSERT INTO met_language VALUES('4054','Nolimit','No limit','0','38','1','0','en');
INSERT INTO met_language VALUES('4055','imgSearch','Images Search','0','39','1','0','en');
INSERT INTO met_language VALUES('4056','displayimg','Display pictures','0','40','1','0','en');
INSERT INTO met_language VALUES('4057','defualt','defualt','0','41','1','0','en');
INSERT INTO met_language VALUES('4058','logininformation','login information clew','0','2','0','0','en');
INSERT INTO met_language VALUES('4059','membercode','Code Error!','0','1','2','0','en');
INSERT INTO met_language VALUES('4060','membernameno','ID Error!','0','2','2','0','en');
INSERT INTO met_language VALUES('4061','memberpassno','Password Error!','0','3','2','0','en');
INSERT INTO met_language VALUES('4062','access','You do not have permission to read the information!','0','4','2','0','en');
INSERT INTO met_language VALUES('4063','login','Login','0','5','2','0','en');
INSERT INTO met_language VALUES('4064','register','Register','0','6','2','0','en');
INSERT INTO met_language VALUES('4065','downloadaccess','You do not have permission to download this file!','0','7','2','0','en');
INSERT INTO met_language VALUES('4066','paging','paging','0','3','0','0','en');
INSERT INTO met_language VALUES('4067','PageTotal','Total','0','1','3','0','en');
INSERT INTO met_language VALUES('4068','Page','Page','0','2','3','0','en');
INSERT INTO met_language VALUES('4069','PageLocation','Now in','0','3','3','0','en');
INSERT INTO met_language VALUES('4070','PageHome','Home','0','4','3','0','en');
INSERT INTO met_language VALUES('4071','PageEnd','End','0','5','3','0','en');
INSERT INTO met_language VALUES('4072','PagePre','PgUp','0','6','3','0','en');
INSERT INTO met_language VALUES('4073','PageNext','PgDn','0','7','3','0','en');
INSERT INTO met_language VALUES('4074','PageGo','Go to','0','8','3','0','en');
INSERT INTO met_language VALUES('4075','Previous','Previous','0','9','3','0','en');
INSERT INTO met_language VALUES('4076','Next','Next','0','10','3','0','en');
INSERT INTO met_language VALUES('4077','Total','Records','0','11','3','0','en');
INSERT INTO met_language VALUES('4078','Pagenum','Page','0','12','3','0','en');
INSERT INTO met_language VALUES('4079','Pagenum1','page','0','13','3','0','en');
INSERT INTO met_language VALUES('4080','Pagenum2','','0','14','3','0','en');
INSERT INTO met_language VALUES('4081','membership','Membership information','0','4','0','0','en');
INSERT INTO met_language VALUES('4082','memberclose','Member Module has been close!','0','1','4','0','en');
INSERT INTO met_language VALUES('4083','memberLogin','User Login','0','2','4','0','en');
INSERT INTO met_language VALUES('4084','memberRegisterName','Please input user name','0','3','4','0','en');
INSERT INTO met_language VALUES('4085','memberPassword','Please input password','0','4','4','0','en');
INSERT INTO met_language VALUES('4086','memberCookie','Please enable Your browser COOKIE!','0','5','4','0','en');
INSERT INTO met_language VALUES('4087','memberName','User Name','0','6','4','0','en');
INSERT INTO met_language VALUES('4088','memberPs','Password','0','7','4','0','en');
INSERT INTO met_language VALUES('4089','memberImgCode','Code','0','8','4','0','en');
INSERT INTO met_language VALUES('4090','memberTip1','Changer Code','0','9','4','0','en');
INSERT INTO met_language VALUES('4091','memberTip2','Remember my login information','0','10','4','0','en');
INSERT INTO met_language VALUES('4092','memberGo','Login','0','11','4','0','en');
INSERT INTO met_language VALUES('4093','memberRegister','Register now','0','12','4','0','en');
INSERT INTO met_language VALUES('4094','memberReset','Reset','0','13','4','0','en');
INSERT INTO met_language VALUES('4095','memberForget','Forget Password?','0','14','4','0','en');
INSERT INTO met_language VALUES('4096','memberIndex1','User Management Center','0','15','4','0','en');
INSERT INTO met_language VALUES('4097','memberIndex2','Welcome!','0','16','4','0','en');
INSERT INTO met_language VALUES('4098','memberIndex3','User Home','0','17','4','0','en');
INSERT INTO met_language VALUES('4099','memberIndex4','Basic information','0','18','4','0','en');
INSERT INTO met_language VALUES('4100','memberIndex5','Manage Feedback','0','19','4','0','en');
INSERT INTO met_language VALUES('4101','memberIndex6','Manage Messages','0','20','4','0','en');
INSERT INTO met_language VALUES('4102','memberIndex7','Manage Resume','0','21','4','0','en');
INSERT INTO met_language VALUES('4103','memberIndex8','Member Control Panel','0','22','4','0','en');
INSERT INTO met_language VALUES('4104','memberIndex9','Member information','0','23','4','0','en');
INSERT INTO met_language VALUES('4105','memberIndex10','Safety Exit','0','24','4','0','en');
INSERT INTO met_language VALUES('4106','memberIndex11','Total','0','25','4','0','en');
INSERT INTO met_language VALUES('4107','memberIndex12','Records','0','26','4','0','en');
INSERT INTO met_language VALUES('4108','memberIndex13','Read','0','27','4','0','en');
INSERT INTO met_language VALUES('4109','memberIndex14','Unread','0','28','4','0','en');
INSERT INTO met_language VALUES('4110','memberIndex15','Manage Resume','0','29','4','0','en');
INSERT INTO met_language VALUES('4111','memberIndex16','Member Notice','0','30','4','0','en');
INSERT INTO met_language VALUES('4112','memberbasicTitle','View basic information','0','31','4','0','en');
INSERT INTO met_language VALUES('4113','memberbasicUserName','User name','0','32','4','0','en');
INSERT INTO met_language VALUES('4114','memberbasicReadlName','Name','0','33','4','0','en');
INSERT INTO met_language VALUES('4115','memberbasicSex','Sex','0','34','4','0','en');
INSERT INTO met_language VALUES('4116','memberbasicMan','Man','0','35','4','0','en');
INSERT INTO met_language VALUES('4117','memberbasicWoman','Woman','0','36','4','0','en');
INSERT INTO met_language VALUES('4118','memberbasicTel','Tel','0','37','4','0','en');
INSERT INTO met_language VALUES('4119','memberbasicCell','Mobile','0','38','4','0','en');
INSERT INTO met_language VALUES('4120','memberbasicTaoBao','Taobao','0','39','4','0','en');
INSERT INTO met_language VALUES('4121','memberbasicLoginNum','Login times','0','40','4','0','en');
INSERT INTO met_language VALUES('4122','memberbasicLastLogin','Last login time','0','41','4','0','en');
INSERT INTO met_language VALUES('4123','memberbasicLastIP','Last login IP','0','42','4','0','en');
INSERT INTO met_language VALUES('4124','memberbasicRegisterTime','Register Time','0','43','4','0','en');
INSERT INTO met_language VALUES('4125','memberbasicIntro','Member Profile','0','44','4','0','en');
INSERT INTO met_language VALUES('4126','memberbasicCompanyName','Company','0','45','4','0','en');
INSERT INTO met_language VALUES('4127','memberbasicCompanyFax','Fax','0','46','4','0','en');
INSERT INTO met_language VALUES('4128','memberbasicCompanyCode','Postcode','0','47','4','0','en');
INSERT INTO met_language VALUES('4129','memberbasicCompanyAddress','Address','0','48','4','0','en');
INSERT INTO met_language VALUES('4130','memberbasicCompanyWebsite','Web','0','49','4','0','en');
INSERT INTO met_language VALUES('4131','memberbasicType','Member Type','0','50','4','0','en');
INSERT INTO met_language VALUES('4132','memberbasicType1','Common Member','0','51','4','0','en');
INSERT INTO met_language VALUES('4133','memberbasicType2','Agent','0','52','4','0','en');
INSERT INTO met_language VALUES('4134','memberbasicType3','Administrators','0','53','4','0','en');
INSERT INTO met_language VALUES('4135','membereditorPs','Password','0','54','4','0','en');
INSERT INTO met_language VALUES('4136','membereditorPs1','Password Affirm','0','55','4','0','en');
INSERT INTO met_language VALUES('4137','membereditorTip','Keep old please write nothing','0','56','4','0','en');
INSERT INTO met_language VALUES('4138','membereditorTip1','Used to retrieve your password','0','57','4','0','en');
INSERT INTO met_language VALUES('4139','memberReg','Register','0','58','4','0','en');
INSERT INTO met_language VALUES('4140','memberEdit','Editer','0','59','4','0','en');
INSERT INTO met_language VALUES('4141','memberDetail','Read','0','60','4','0','en');
INSERT INTO met_language VALUES('4142','memberShowAll','Read all','0','61','4','0','en');
INSERT INTO met_language VALUES('4143','memberFeedbackName','Feedback Title','0','62','4','0','en');
INSERT INTO met_language VALUES('4144','memberAddTime','Add Time','0','63','4','0','en');
INSERT INTO met_language VALUES('4145','memberOperate','Operate','0','64','4','0','en');
INSERT INTO met_language VALUES('4146','memberFile','Attachments have been uploaded','0','65','4','0','en');
INSERT INTO met_language VALUES('4147','memberinfo','Messager Content','0','66','4','0','en');
INSERT INTO met_language VALUES('4148','memberReply','Reply','0','67','4','0','en');
INSERT INTO met_language VALUES('4149','memberContent','Messager Content','0','68','4','0','en');
INSERT INTO met_language VALUES('4150','messageeditorName','Name','0','69','4','0','en');
INSERT INTO met_language VALUES('4151','messageeditorTel','Tel','0','70','4','0','en');
INSERT INTO met_language VALUES('4152','messageeditorContact','Other contact way','0','71','4','0','en');
INSERT INTO met_language VALUES('4153','messageeditorContent','Information','0','72','4','0','en');
INSERT INTO met_language VALUES('4154','messageeditorTime','Add Time','0','73','4','0','en');
INSERT INTO met_language VALUES('4155','messageeditorReply','Administrators reply','0','74','4','0','en');
INSERT INTO met_language VALUES('4156','cvTip4','Position has been deleted','0','75','4','0','en');
INSERT INTO met_language VALUES('4157','memberPosition','Position','0','76','4','0','en');
INSERT INTO met_language VALUES('4158','memberModifyCV','Modify Resume','0','77','4','0','en');
INSERT INTO met_language VALUES('4159','memberModifyMS','Modify Messager','0','78','4','0','en');
INSERT INTO met_language VALUES('4160','memberModifyFD','Modify Feedback','0','79','4','0','en');
INSERT INTO met_language VALUES('4161','memberShowFD','Read Feedback','0','80','4','0','en');
INSERT INTO met_language VALUES('4162','memberShowMS','Read Messager','0','81','4','0','en');
INSERT INTO met_language VALUES('4163','memberShowCV','Read Resume','0','82','4','0','en');
INSERT INTO met_language VALUES('4164','getNotice','Member Password notification','0','83','4','0','en');
INSERT INTO met_language VALUES('4165','NewPassJS','Please login E-mail receive the latest password','0','84','4','0','en');
INSERT INTO met_language VALUES('4166','NewPassJS1','enter it again Inconsistent','0','85','4','0','en');
INSERT INTO met_language VALUES('4167','NewPassJS2','enter the password twice','0','86','4','0','en');
INSERT INTO met_language VALUES('4168','NoidJS','No ID','0','87','4','0','en');
INSERT INTO met_language VALUES('4169','NoidJS1','no user or an incorrect e-mail address','0','88','4','0','en');
INSERT INTO met_language VALUES('4170','getTip1','Your password of','0','89','4','0','en');
INSERT INTO met_language VALUES('4171','getTip2','has been random change:','0','90','4','0','en');
INSERT INTO met_language VALUES('4172','getTip3','<br>Please log in time and change the password member Admin!','0','91','4','0','en');
INSERT INTO met_language VALUES('4173','getTip4','Please input login id','0','92','4','0','en');
INSERT INTO met_language VALUES('4174','getTip5','Get back password','0','93','4','0','en');
INSERT INTO met_language VALUES('4175','getTip6','Can not be called Jmail','0','94','4','0','en');
INSERT INTO met_language VALUES('4176','getTip7','Please enter a new password, to later remember your password.','0','95','4','0','en');
INSERT INTO met_language VALUES('4177','getTip8','The link has expired!','0','96','4','0','en');
INSERT INTO met_language VALUES('4178','getOK','Send successe','0','97','4','0','en');
INSERT INTO met_language VALUES('4179','getFail','Send Error','0','98','4','0','en');
INSERT INTO met_language VALUES('4180','membernodo','This user has not been activated, please immediately contact your administrator!','0','99','4','0','en');
INSERT INTO met_language VALUES('4181','hello','hello！','0','100','4','0','en');
INSERT INTO met_language VALUES('4182','fileupload','File upload','0','5','0','0','en');
INSERT INTO met_language VALUES('4183','fileOK','File Upload successful','0','1','5','0','en');
INSERT INTO met_language VALUES('4184','fileError1','The uploaded file exceeds the max size','0','2','5','0','en');
INSERT INTO met_language VALUES('4185','fileError2','The uploaded file exceeds the max size','0','3','5','0','en');
INSERT INTO met_language VALUES('4186','fileError3','File was only partially uploaded','0','4','5','0','en');
INSERT INTO met_language VALUES('4187','fileError4','No file was uploaded','0','5','5','0','en');
INSERT INTO met_language VALUES('4188','jstip','js Tip','0','6','0','0','en');
INSERT INTO met_language VALUES('4189','js1','Error!','0','1','6','0','en');
INSERT INTO met_language VALUES('4190','js2','Admin Login now!','0','2','6','0','en');
INSERT INTO met_language VALUES('4191','js3','SorryìRegistration is temporarily closed!','0','3','6','0','en');
INSERT INTO met_language VALUES('4192','js4','Unable to activate this user, please contact the administrator!','0','4','6','0','en');
INSERT INTO met_language VALUES('4193','js5','Has been successfully activated, please go to!','0','5','6','0','en');
INSERT INTO met_language VALUES('4194','js6','User input is wrong!','0','6','6','0','en');
INSERT INTO met_language VALUES('4195','js7','User name can not be less than 3!','0','7','6','0','en');
INSERT INTO met_language VALUES('4196','js8','Password should be more than equal to 6!','0','8','6','0','en');
INSERT INTO met_language VALUES('4197','js9','Please re-enter the user password!!','0','9','6','0','en');
INSERT INTO met_language VALUES('4198','js10','Two password the importation is inconsistent!','0','10','6','0','en');
INSERT INTO met_language VALUES('4199','js11','Please enter company name!','0','11','6','0','en');
INSERT INTO met_language VALUES('4200','js12','Please enter Email!','0','12','6','0','en');
INSERT INTO met_language VALUES('4201','js13','Email is error!','0','13','6','0','en');
INSERT INTO met_language VALUES('4202','js14','Please enter Code!','0','14','6','0','en');
INSERT INTO met_language VALUES('4203','js15','User name exist!','0','15','6','0','en');
INSERT INTO met_language VALUES('4204','js16','Member activation','0','16','6','0','en');
INSERT INTO met_language VALUES('4205','js17','Member activation:','0','17','6','0','en');
INSERT INTO met_language VALUES('4206','js18','Please click','0','18','6','0','en');
INSERT INTO met_language VALUES('4207','js19','Complete the membership account activation!','0','19','6','0','en');
INSERT INTO met_language VALUES('4208','js20','Activation e-mail has happened to your registered e-mail, please activate your membership immediately!','0','20','6','0','en');
INSERT INTO met_language VALUES('4209','js21','Success!','0','21','6','0','en');
INSERT INTO met_language VALUES('4210','js22','The specified path can not write, or do not have this path!','0','22','6','0','en');
INSERT INTO met_language VALUES('4211','js23','File format does not allow upload','0','23','6','0','en');
INSERT INTO met_language VALUES('4212','js24','Administrators have read, there is no permission to modify the!','0','24','6','0','en');
INSERT INTO met_language VALUES('4213','js25','Successful registration, pending management audit control panel you can log on!','0','25','6','0','en');
INSERT INTO met_language VALUES('4214','other','Other','0','7','0','0','en');
INSERT INTO met_language VALUES('4215','YES','Yes','0','1','7','0','en');
INSERT INTO met_language VALUES('4216','NO','No','0','2','7','0','en');
INSERT INTO met_language VALUES('4217','Article','Other Article','0','3','7','0','en');
INSERT INTO met_language VALUES('4218','Printing','Printing','0','4','7','0','en');
INSERT INTO met_language VALUES('4219','Times','Hits','0','5','7','0','en');
INSERT INTO met_language VALUES('4220','Feedback','Feedback','0','6','7','0','en');
INSERT INTO met_language VALUES('4221','FileSize','File Size','0','7','7','0','en');
INSERT INTO met_language VALUES('4222','Download','Download','0','8','7','0','en');
INSERT INTO met_language VALUES('4223','Position','Position','0','9','7','0','en');
INSERT INTO met_language VALUES('4224','PersonNumber','Number','0','10','7','0','en');
INSERT INTO met_language VALUES('4225','WorkPlace','Workplace','0','11','7','0','en');
INSERT INTO met_language VALUES('4226','AddDate','Release Date','0','12','7','0','en');
INSERT INTO met_language VALUES('4227','Deal','Deal','0','13','7','0','en');
INSERT INTO met_language VALUES('4228','Validity','Validity','0','14','7','0','en');
INSERT INTO met_language VALUES('4229','JobDescription','Description','0','15','7','0','en');
INSERT INTO met_language VALUES('4230','Submit','Submit','0','16','7','0','en');
INSERT INTO met_language VALUES('4231','Reset','Reset','0','17','7','0','en');
INSERT INTO met_language VALUES('4232','AdvancedSearch','Advanced Search','0','18','7','0','en');
INSERT INTO met_language VALUES('4233','Keywords','Keywords','0','19','7','0','en');
INSERT INTO met_language VALUES('4234','AllBigclass','All Bigclass','0','20','7','0','en');
INSERT INTO met_language VALUES('4235','AllSmallclass','All Smallclass','0','21','7','0','en');
INSERT INTO met_language VALUES('4236','AllThirdclass','All Thirdclass','0','22','7','0','en');
INSERT INTO met_language VALUES('4237','And','And','0','23','7','0','en');
INSERT INTO met_language VALUES('4238','Info4','Please make site link to re-apply, thank you!','0','24','7','0','en');
INSERT INTO met_language VALUES('4239','OurWebName','Our name','0','25','7','0','en');
INSERT INTO met_language VALUES('4240','OurWebUrl','Our url','0','26','7','0','en');
INSERT INTO met_language VALUES('4241','OurWebLOGO','Our LOGO','0','27','7','0','en');
INSERT INTO met_language VALUES('4242','OurWebKeywords','Our Keywords','0','28','7','0','en');
INSERT INTO met_language VALUES('4243','YourWebName','Your WebName','0','29','7','0','en');
INSERT INTO met_language VALUES('4244','YourWebUrl','Your WebUrl','0','30','7','0','en');
INSERT INTO met_language VALUES('4245','YourWebLOGO','Your LOGO','0','31','7','0','en');
INSERT INTO met_language VALUES('4246','YourWebKeywords','Your Keywords','0','32','7','0','en');
INSERT INTO met_language VALUES('4247','LinkType','LinkType','0','33','7','0','en');
INSERT INTO met_language VALUES('4248','TextLink','Text','0','34','7','0','en');
INSERT INTO met_language VALUES('4249','PictureLink','Images','0','35','7','0','en');
INSERT INTO met_language VALUES('4250','Contact','Contact','0','36','7','0','en');
INSERT INTO met_language VALUES('4251','ApplyLink','Apply Link','0','37','7','0','en');
INSERT INTO met_language VALUES('4252','ApplyLinkNO','No open links application','0','38','7','0','en');
INSERT INTO met_language VALUES('4253','SubmitInfo','Submit','0','39','7','0','en');
INSERT INTO met_language VALUES('4254','Publish','Add on','0','40','7','0','en');
INSERT INTO met_language VALUES('4255','SubmitContent','Content','0','41','7','0','en');
INSERT INTO met_language VALUES('4256','Reply','Admin Reply','0','42','7','0','en');
INSERT INTO met_language VALUES('4257','ReadInfo','Read','0','43','7','0','en');
INSERT INTO met_language VALUES('4258','Name','Name','0','44','7','0','en');
INSERT INTO met_language VALUES('4259','Phone','Tel','0','45','7','0','en');
INSERT INTO met_language VALUES('4260','Email','Email','0','46','7','0','en');
INSERT INTO met_language VALUES('4261','OtherContact','Other Contact Way','0','47','7','0','en');
INSERT INTO met_language VALUES('4262','Info5','Such as QQbMSN','0','48','7','0','en');
INSERT INTO met_language VALUES('4263','Feedback1','Please do not send information again in','0','49','7','0','en');
INSERT INTO met_language VALUES('4264','Feedback2','second!','0','50','7','0','en');
INSERT INTO met_language VALUES('4265','Feedback3','is not permited to send!','0','51','7','0','en');
INSERT INTO met_language VALUES('4266','Feedback5','The feedback has been closed','0','52','7','0','en');
INSERT INTO met_language VALUES('4267','FeedbackProduct','Feedback Product','0','53','7','0','en');
INSERT INTO met_language VALUES('4268','IP','IP','0','54','7','0','en');
INSERT INTO met_language VALUES('4269','AddTime','Add Time','0','55','7','0','en');
INSERT INTO met_language VALUES('4270','SourcePage','The source of the page','0','56','7','0','en');
INSERT INTO met_language VALUES('4271','Feedback4','Successfully,Thanks!','0','57','7','0','en');
INSERT INTO met_language VALUES('4272','Choice','Select','0','58','7','0','en');
INSERT INTO met_language VALUES('4273','Empty','is Empty','0','59','7','0','en');
INSERT INTO met_language VALUES('4274','LinkInfo1','Successfully,Thanks!','0','60','7','0','en');
INSERT INTO met_language VALUES('4275','LinkInfo2','WebName is Empty','0','61','7','0','en');
INSERT INTO met_language VALUES('4276','LinkInfo3','Web Url is Emtpy','0','62','7','0','en');
INSERT INTO met_language VALUES('4277','MessageInfo1','Guestbook','0','63','7','0','en');
INSERT INTO met_language VALUES('4278','MessageInfo2','Successfully,Thanks!','0','64','7','0','en');
INSERT INTO met_language VALUES('4279','MessageInfo3','Name is Empty','0','65','7','0','en');
INSERT INTO met_language VALUES('4280','MessageInfo4','Infomation is Empty','0','66','7','0','en');
INSERT INTO met_language VALUES('4281','MessageInfo5','Browser does not support this feature, please manually set!','0','67','7','0','en');
INSERT INTO met_language VALUES('4282','messageadd','Submit message','0','68','7','0','en');
INSERT INTO met_language VALUES('4283','messageview','View message','0','69','7','0','en');
INSERT INTO met_language VALUES('4284','SearchInfo','Online search','0','70','7','0','en');
INSERT INTO met_language VALUES('4285','SearchInfo1','Please input keywords!','0','71','7','0','en');
INSERT INTO met_language VALUES('4286','SearchInfo2','All Information','0','72','7','0','en');
INSERT INTO met_language VALUES('4287','SearchInfo3','No information that contains','0','73','7','0','en');
INSERT INTO met_language VALUES('4288','SearchInfo4','','0','74','7','0','en');
INSERT INTO met_language VALUES('4289','Job1','No Limit','0','75','7','0','en');
INSERT INTO met_language VALUES('4290','Job2','Day','0','76','7','0','en');
INSERT INTO met_language VALUES('4291','several','Several','0','77','7','0','en');
INSERT INTO met_language VALUES('4292','cvtitle','Online apply for','0','78','7','0','en');
INSERT INTO met_language VALUES('4293','cv','View resume','0','79','7','0','en');
INSERT INTO met_language VALUES('4294','cv2','Apply for your company','0','80','7','0','en');
INSERT INTO met_language VALUES('4295','feedbackonline','Feedback Online','0','81','7','0','en');
INSERT INTO met_language VALUES('4296','messageonline','Guestbook','0','82','7','0','en');
INSERT INTO met_language VALUES('4297','htmcreate','generation','0','83','7','0','en');
INSERT INTO met_language VALUES('4298','htmsuccess','Success!','0','84','7','0','en');
INSERT INTO met_language VALUES('4299','htmpermission','No power!','0','85','7','0','en');
INSERT INTO met_language VALUES('4300','metwapok','No open WAP function!','0','86','7','0','en');
INSERT INTO met_language VALUES('4301','wap','Mobile','0','87','7','0','en');
INSERT INTO met_language VALUES('4302','smstips66','insufficient balance','0','88','7','0','en');
INSERT INTO met_language VALUES('4303','smstips67','content of the message is too long, up to 350 words','0','89','7','0','en');
INSERT INTO met_language VALUES('4304','smstips68','too many phone numbers, up to 800 numbers','0','90','7','0','en');
INSERT INTO met_language VALUES('4305','smstips69','Number does not comply with the rules','0','91','7','0','en');
INSERT INTO met_language VALUES('4306','smstips70','sent successfully (with delay)','0','92','7','0','en');
INSERT INTO met_language VALUES('4307','smstips71','abnormal operation, the balance is less than','0','93','7','0','en');
INSERT INTO met_language VALUES('4308','smstips72','insufficient balance','0','94','7','0','en');
INSERT INTO met_language VALUES('4309','smstips73','SMS content and mobile number can not be empty','0','95','7','0','en');
INSERT INTO met_language VALUES('4310','smstips74','send the wrong password','0','96','7','0','en');
INSERT INTO met_language VALUES('4311','smstips75','not access the site','0','97','7','0','en');
INSERT INTO met_language VALUES('4312','smstips76','server did not respond','0','98','7','0','en');
INSERT INTO met_language VALUES('4313','detailtxt','Detailed','0','99','7','0','en');
INSERT INTO met_language VALUES('4314','showdownload1','Updated','0','100','7','0','en');
INSERT INTO met_language VALUES('4315','showdownload2','File Download','0','101','7','0','en');
INSERT INTO met_language VALUES('4316','showdownload3','Click to download','0','102','7','0','en');
INSERT INTO met_language VALUES('4341','initext1','Search Now','0','42','1','0','en');
INSERT INTO met_language VALUES('4342','saechplaceholder','Please enter a keyword','0','43','1','0','en');
INSERT INTO met_language VALUES('4343','drxtop','Top','0','44','1','0','en');
INSERT INTO met_language VALUES('4344','drxhot','Hot','0','45','1','0','en');
INSERT INTO met_language VALUES('4345','drxnew','New','0','46','1','0','en');
INSERT INTO met_language VALUES('4346','colmnmore','More Categories','0','47','1','0','en');
INSERT INTO met_language VALUES('4347','fliptext1','See More','0','48','1','0','en');
INSERT INTO met_language VALUES('4348','fliptext2','Loading ...','0','49','1','0','en');
INSERT INTO met_language VALUES('4349','downloadtext1','Download','0','50','1','0','en');
INSERT INTO met_language VALUES('4350','downloadtext2','Visit','0','51','1','0','en');
INSERT INTO met_language VALUES('4351','jobtext1','People','0','52','1','0','en');
INSERT INTO met_language VALUES('4352','foottext1','Phone','0','53','1','0','en');
INSERT INTO met_language VALUES('4353','foottext2','Map','0','54','1','0','en');
INSERT INTO met_language VALUES('4354','foottext3','Leave a message','0','55','1','0','en');
INSERT INTO met_language VALUES('4355','foottext4','Home','0','56','1','0','en');
INSERT INTO met_language VALUES('4356','foottext5','PC Edition','0','57','1','0','en');
INSERT INTO met_language VALUES('4357','foottext6','Touch Edition','0','58','1','0','en');
INSERT INTO met_language VALUES('4358','navtext1','Navigation section','0','59','1','0','en');
INSERT INTO met_language VALUES('4359','nettext2','Article','0','60','1','0','en');
INSERT INTO met_language VALUES('4360','nettext3','Product Details','0','61','1','0','en');
INSERT INTO met_language VALUES('4361','nettext4','Details of','0','62','1','0','en');
INSERT INTO met_language VALUES('4362','nettext5','Photo Details','0','63','1','0','en');
INSERT INTO met_language VALUES('4363','nettext6','Job Details','0','64','1','0','en');
INSERT INTO met_language VALUES('4364','nettext9','Application Links','0','65','1','0','en');
INSERT INTO met_language VALUES('4366','tagweb','TAG','0','66','1','0','en');
INSERT INTO met_config VALUES('4368','wap_footertext_tel','0000-88888','0','0','0','en');
INSERT INTO met_admin_array VALUES('4','Member','','0','','0','0','1','1','en','');
INSERT INTO met_admin_array VALUES('5','Agents','','0','','0','0','2','1','en','');
INSERT INTO met_config VALUES('638','metconfig_message_fd_class','120','','49','0','en');
INSERT INTO met_config VALUES('640','metconfig_message_fd_email','122','','49','0','en');
INSERT INTO met_config VALUES('642','metconfig_message_fd_sms','121','','49','0','en');
INSERT INTO met_config VALUES('644','metconfig_message_fd_content','124','','49','0','en');


INSERT INTO met_language VALUES('35826','read','Read','0','0','1','0','en');
INSERT INTO met_language VALUES('35827','switching_category','Switching category','0','0','1','0','en');
INSERT INTO met_language VALUES('35727','formerror1','Please fill in this field.','0','0','1','0','en');
INSERT INTO met_language VALUES('35728','formerror2','Please choose one of these options.','0','0','1','0','en');
INSERT INTO met_language VALUES('35729','formerror3','Please enter the correct phone number.','0','0','1','0','en');
INSERT INTO met_language VALUES('35730','formerror4','Please enter the correct Email address.','0','0','1','0','en');
INSERT INTO met_language VALUES('35731','formerror5','Two input password, please enter again.','0','0','1','0','en');
INSERT INTO met_language VALUES('35732','formerror6','Please enter at least &metinfo& characters.','0','0','1','0','en');
INSERT INTO met_language VALUES('35733','formerror7','Enter no more than &metinfo& characters.','0','0','1','0','en');
INSERT INTO met_language VALUES('35734','formerror8','Enter the number of characters must be between &metinfo&.','0','0','1','0','en');
INSERT INTO met_language VALUES('35725','js46','can not repeat','0','0','1','0','en');

INSERT INTO met_config VALUES('4381','metconfig_weixin_appid','','','0','0','en');
INSERT INTO met_config VALUES('4382','metconfig_weixin_appsecret','','','0','0','en');
INSERT INTO met_config VALUES('4383','metconfig_weibo_appkey','','','0','0','en');
INSERT INTO met_config VALUES('4384','metconfig_weibo_appsecret','','','0','0','en');
INSERT INTO met_config VALUES('4385','metconfig_qq_appid','','','0','0','en');
INSERT INTO met_config VALUES('4386','metconfig_qq_appsecret','','','0','0','en');
INSERT INTO met_config VALUES('4387','metconfig_weixin_open','0','','0','0','en');
INSERT INTO met_config VALUES('4388','metconfig_weibo_open','0','','0','0','en');
INSERT INTO met_config VALUES('4389','metconfig_qq_open','0','','0','0','en');

INSERT INTO met_config VALUES('4403','metconfig_weixin_gz_appid','','','0','0','en');
INSERT INTO met_config VALUES('4404','metconfig_weixin_gz_appsecret','','','0','0','en');
INSERT INTO met_config VALUES('4405','metconfig_member_bgcolor','','','0','0','en');
INSERT INTO met_config VALUES('4406','metconfig_member_bgimage','','','0','0','en');

INSERT INTO met_config VALUES('4417','metconfig_member_email_reg_title','{webname} Member center registration verification','','0','0','en');
INSERT INTO met_config VALUES('4418','metconfig_member_email_reg_content','<div style="width:500px;margin:20px auto;"><div class="header clearfix" style="font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; background-color: rgb(255, 255, 255);"><a href="{weburl}"><strong style="outline: none; cursor: pointer; color: rgb(30, 84, 148);">{webname} Member center</strong></a></div><p>&nbsp;</p><div class="content" style="font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; border: 1px solid rgb(233, 233, 233); margin: 2px 0px 0px; padding: 30px; background: none 0px 0px repeat scroll rgb(255, 255, 255);"><p style="line-height: 23.7999992370605px;">hello:</p><p style="line-height: 23.7999992370605px;">This is your key message on the {webname} member center, Function is to carry out&nbsp;Member center registration verification, please click on the link below to complete the verification</p><p style="line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); margin-top: 15px; margin-bottom: 25px; padding: 15px;">Please click on the link to continue:{opurl}</p><p style="line-height: 23.7999992370605px;">&nbsp;</p><p class="footer" style="line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); padding-top: 6px; margin-top: 25px; color: rgb(131, 131, 131);">Please do not reply to this message, this mailbox is not monitored, you will not get any reply.<br/><br/><a href="{weburl}"><strong style="outline: none; cursor: pointer; color: rgb(30, 84, 148);">{webname}Member Center</strong></a></p></div></div>','','0','0','en');
INSERT INTO met_config VALUES('4419','metconfig_member_email_password_title','{webname} Member center password back','','0','0','en');
INSERT INTO met_config VALUES('4420','metconfig_member_email_password_content','<div style="width:500px;margin:20px auto;"><div class="header clearfix" style="font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; background-color: rgb(255, 255, 255);"><a href="{weburl}"><strong style="outline: none; cursor: pointer; color: rgb(30, 84, 148);">{webname} Member Center</strong></a></div><p>&nbsp;</p><div class="content" style="font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; border: 1px solid rgb(233, 233, 233); margin: 2px 0px 0px; padding: 30px; background: none 0px 0px repeat scroll rgb(255, 255, 255);"><p style="line-height: 23.7999992370605px;">hello:</p><p style="line-height: 23.7999992370605px;">This is your key message on the {webname} Important message on the member center, Function is to carry out&nbsp;Member center password back, please click on the link below to complete the verification</p><p style="line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); margin-top: 15px; margin-bottom: 25px; padding: 15px;">Please click on the link to continue:{opurl}</p><p style="line-height: 23.7999992370605px;">&nbsp;</p><p class="footer" style="line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); padding-top: 6px; margin-top: 25px; color: rgb(131, 131, 131);">Please do not reply to this message, this mailbox is not monitored, you will not get any reply.<br/><br/><a href="{weburl}"><strong style="outline: none; cursor: pointer; color: rgb(30, 84, 148);">{webname}Member Center</strong></a></p></div></div>','','0','0','en');
INSERT INTO met_config VALUES('4421','metconfig_member_email_safety_title','{webname} Member center to modify the binding mailbox','','0','0','en');
INSERT INTO met_config VALUES('4422','metconfig_member_email_safety_content','<div style="width:500px;margin:20px auto;"><div class="header clearfix" style="font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; background-color: rgb(255, 255, 255);"><a href="{weburl}"><strong style="outline: none; cursor: pointer; color: rgb(30, 84, 148);">{webname} Member Center</strong></a></div><p>&nbsp;</p><div class="content" style="font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; border: 1px solid rgb(233, 233, 233); margin: 2px 0px 0px; padding: 30px; background: none 0px 0px repeat scroll rgb(255, 255, 255);"><p style="line-height: 23.7999992370605px;">hello:</p><p style="line-height: 23.7999992370605px;">This is your key message on the {webname} Important message on the member center, Function is to carry out&nbsp;Member center bound mailbox modification, please click on the link below to complete the verification</p><p style="line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); margin-top: 15px; margin-bottom: 25px; padding: 15px;">Please click on the link to continue:{opurl}</p><p style="line-height: 23.7999992370605px;">&nbsp;</p><p class="footer" style="line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); padding-top: 6px; margin-top: 25px; color: rgb(131, 131,131);">Please do not reply to this message, this mailbox is not monitored, you will not get any reply.<br/><br/><a href="{weburl}"><strong style="outline: none; cursor: pointer; color: rgb(30, 84, 148);">{webname}Member Center</strong></a></p></div></div>','','0','0','en');

INSERT INTO met_language VALUES(36196,'emailcheck','mailbox validation', 0, 102, 0, 4,'en');
INSERT INTO met_language VALUES(36197,'emailchecktips1', 'thank you for your registration! Activation link has been sent to your mailbox', 0, 103, 4, 0,'en');
INSERT INTO met_language VALUES(36198,'emailchecktips2','click the link in the email to activate the account', 0, 104, 4, 0,'en');
INSERT INTO met_language VALUES(36199,'emailchecktips3','has not received confirmation email?', 0, 105, 0, 4,'en');
INSERT INTO met_language VALUES(36200,'emailchecktips4','Try to look at the ads, spam, and junk mail.', 0, 106, 4, 0,'en');
INSERT INTO met_language VALUES(36201,'emailchecktips5','re send confirmation email', 0, 107, 4, 0,'en');
INSERT INTO met_language VALUES(36202,'accsafe','account security', 0, 108, 4, 0,'en');
INSERT INTO met_language VALUES(36203,'resend','repeat', 0, 109, 4, 0,'en');
INSERT INTO met_language VALUES(36204,'getmemberImgCode','get code', 0, 110, 0, 4,'en');
INSERT INTO met_language VALUES(36205,'teluse','phone number has been registered', 0, 111, 0, 4,'en');
INSERT INTO met_language VALUES(36206,'telok','please enter the correct phone number', 0, 112, 0, 4,'en');
INSERT INTO met_language VALUES(36207,'password','password', 0, 113, 0, 4,'en');
INSERT INTO met_language VALUES(36208,'userhave','user name already exists', 0, 114, 4, 0,'en');
INSERT INTO met_language VALUES(36209,'emailhave','mailbox has been registered', 0, 115, 0, 4,'en');
INSERT INTO met_language VALUES(36210,'memberemail','mailbox', 0, 116, 0, 4,'en');
INSERT INTO met_language VALUES(36211,'memberMoreInfo','more information', 0, 117, 4, 0,'en');
INSERT INTO met_language VALUES(36212,'select','choice', 0, 118, 0, 4,'en');
INSERT INTO met_language VALUES(36213,'acchave','has an account number?', 0, 119, 0, 4,'en');
INSERT INTO met_language VALUES(36214,'accpassword','account password', 0, 120, 0, 4,'en');
INSERT INTO met_language VALUES(36215,'accsaftips1','is used to protect the account information and login security', 0, 121, 0, 4,'en');
INSERT INTO met_language VALUES(36216,'modify','modified', 0, 122, 0, 4,'en');
INSERT INTO met_language VALUES(36217,'accemail','mailbox bound', 0, 123, 4, 0,'en');
INSERT INTO met_language VALUES(36218,'accsaftips2','mailbox binding can be used for login account, reset password or other security verification', 0, 124, 0, 4,'en');
INSERT INTO met_language VALUES(36219,'acctel','mobile phone binding', 0, 125, 0, 4,'en');
INSERT INTO met_language VALUES(36220,'accsaftips3','mobile binding can be used to log in to account, reset password or other security verification', 0, 126, 0, 4,'en');
INSERT INTO met_language VALUES(36221,'modifypassword','password change', 0, 127, 0, 4,'en');
INSERT INTO met_language VALUES(36222,'oldpassword','original password', 0, 128, 0, 4,'en');
INSERT INTO met_language VALUES(36223,'newpassword','new password', 0, 129, 4, 0,'en');
INSERT INTO met_language VALUES(36224,'confirm','OK', 0, 130, 0, 4,'en');
INSERT INTO met_language VALUES(36225,'cancel','Cancel', 0, 131, 4, 0,'en');
INSERT INTO met_language VALUES(36226,'emailaddress','email address', 0, 132, 0, 4,'en');
INSERT INTO met_language VALUES(36227,'emailuse','mailbox has been bound', 0, 133, 0, 4,'en');
INSERT INTO met_language VALUES(36228,'telnum','mobile phone number', 0, 134, 0, 4,'en');
INSERT INTO met_language VALUES(36229,'teluse','phone number has been bound', 0, 135, 0, 4,'en');
INSERT INTO met_language VALUES(36230,'telok','please enter the correct phone number', 0, 136, 0, 4,'en');
INSERT INTO met_language VALUES(36231,'modifyacctel','modified cell phone binding', 0, 137, 0, 4,'en');
INSERT INTO met_language VALUES(36232,'modifyinfo','save information', 0, 138, 4, 0,'en');
INSERT INTO met_language VALUES(36233,'emailnow','current mailbox:', 0, 139, 4, 0,'en');
INSERT INTO met_language VALUES(36234,'newemail','new mailbox', 0, 140, 4, 0,'en');
INSERT INTO met_language VALUES(36235,'submit','submit', 0, 141, 4, 0,'en');
INSERT INTO met_language VALUES(36236,'modifyaccemail','modify the binding mailbox', 0, 142, 0, 4,'en');
INSERT INTO met_language VALUES(36237,'resetpassword','please reset your password', 0, 143, 4, 0,'en');
INSERT INTO met_language VALUES(36238,'renewpassword','repeat password', 0, 144, 4, 0,'en');
INSERT INTO met_language VALUES(36239,'inputcode','please enter the verification code', 0, 145, 4, 0,'en');
INSERT INTO met_language VALUES(36240,'next','next', 0, 146, 4, 0,'en');
INSERT INTO met_language VALUES(36241,'logintips','user name / email / cell phone', 0, 147, 0, 4,'en');
INSERT INTO met_language VALUES(36242,'otherlogin','other means', 0, 148, 4, 0,'en');
INSERT INTO met_language VALUES(36243,'logintips1','no account number? go to register', 0, 149, 4, 0,'en');
INSERT INTO met_language VALUES(36244,'rehomepage','return home', 0, 150, 4, 0,'en');
INSERT INTO met_language VALUES(36245,'rememberImgCode','retransmission verification code', 0, 150, 4, 0,'en');
INSERT INTO met_language VALUES(36246,'relogin','returned', 0, 151, 0, 4,'en');
INSERT INTO met_language VALUES(36247,'getpasswordtips','mailbox / cell phone', 0, 152, 0, 4,'en');
INSERT INTO met_language VALUES(36248,'regclose','registered function has been closed', 0, 153, 4, 0,'en');
INSERT INTO met_language VALUES(36249,'regfail','registered failure', 0, 154, 4, 0,'en');
INSERT INTO met_language VALUES(36250,'codetimeout','verify code has timed out', 0, 155, 4, 0,'en');
INSERT INTO met_language VALUES(36251,'telcheckfail','mobile phone number and SMS verification number is not the same', 0, 156, 0, 4,'en');
INSERT INTO met_language VALUES(36252,'regsuc','registered success!', 0, 157, 0, 4,'en');
INSERT INTO met_language VALUES(36253,'activesuc','activation', 0, 158, 0, 4,'en');
INSERT INTO met_language VALUES(36254,'emailvildtips1','validation information error', 0, 159, 0, 4,'en');
INSERT INTO met_language VALUES(36255,'emailvildtips2','verify that the information error or has timed out', 0, 160, 0, 4,'en');
INSERT INTO met_language VALUES(36256,'telreg','phone number has been registered', 0, 161, 0, 4,'en');
INSERT INTO met_language VALUES(36257,'Sendfrequent','send too often, please try again later', 0, 162, 4, 0,'en');
INSERT INTO met_language VALUES(36258,'emailsuc','message sent successfully!', 0, 163, 0, 4,'en');
INSERT INTO met_language VALUES(36259,'emailfail','mail sent failed, please confirm whether the mailbox is correct or contact the site administrator to resolve.', 0, 164, 0, 4,'en');
INSERT INTO met_language VALUES(36260,'modifysuc','modified', 0, 165, 0, 4,'en');
INSERT INTO met_language VALUES(36261,'binding','bound', 0, 166, 4, 0,'en');
INSERT INTO met_language VALUES(36262,'notbound','not bound', 0, 167, 4, 0,'en');
INSERT INTO met_language VALUES(36263,'accnotmodify','account cannot be modified', 0, 168, 0, 4,'en');
INSERT INTO met_language VALUES(36264,'emailsuclink','message sent successfully! Please click on the verification link in the email to complete the operation!', 0, 169, 0, 4,'en');
INSERT INTO met_language VALUES(36265,'bindingok','bound success', 0, 170, 4, 0,'en');
INSERT INTO met_language VALUES(36266,'opfail','operation failure', 0, 171, 4, 0,'en');
INSERT INTO met_language VALUES(36267,'modifypasswordsuc','password changes successfully!', 0, 172, 0, 4,'en');
INSERT INTO met_language VALUES(36268,'lodpasswordfail','original password error', 0, 173, 0, 4,'en');
INSERT INTO met_language VALUES(36269,'membererror1','user name or password error', 0, 174, 4, 0,'en');
INSERT INTO met_language VALUES(36270,'membererror2','please open session!', 0, 175, 0, 4,'en');
INSERT INTO met_language VALUES(36271,'membererror3','licensing failure', 0, 176, 0, 4,'en');
INSERT INTO met_language VALUES(36272,'membererror4','unknown error', 0, 177, 0, 4,'en');
INSERT INTO met_language VALUES(36273,'emailsucpass','password to retrieve the mail has been sent to your mailbox, click the link in the message to reset the password.', 0, 178, 0, 4,'en');
INSERT INTO met_language VALUES(36274,'emailvildtips3','please enter the correct email address or phone number', 0, 179, 0, 4,'en');
INSERT INTO met_language VALUES(36275,'membererror5','send failed! Error code:', 0, 180, 4, 0,'en');


INSERT INTO met_language VALUES(36281,'noempty','This is required and cannot be empty', 0, 181, 4, 0,'en');
INSERT INTO met_language VALUES(36282,'usernamecheck','The username must be more than 2 and less than 30 characters long', 0, 182, 4, 0,'en');
INSERT INTO met_language VALUES(36283,'passwordcheck','The password must be more than 3 and less than 30 characters long', 0, 183, 4, 0,'en');
INSERT INTO met_language VALUES(36284,'passwordsame','The password and its confirm are not the same', 0, 184, 4, 0,'en');
INSERT INTO met_language VALUES(36285,'emailcheck','The input is not a valid email address', 0, 184, 4, 0,'en');
INSERT INTO met_language VALUES(36292,'memberhead','Head portrait', 0, 184, 4, 0,'tc');

INSERT INTO `met_user_group` VALUES(4, 'Member', 1, 'en');
INSERT INTO `met_user_group` VALUES(5, 'Agents', 2, 'en');