INSERT INTO met_lang VALUES('4','English','1','2','en','en.gif','','0','0','html','','en');
INSERT INTO met_config VALUES('205','metconfig_cv_time','120','0','0','en');
INSERT INTO met_config VALUES('206','metconfig_cv_word','','0','0','en');
INSERT INTO met_config VALUES('207','metconfig_cv_type','1','0','0','en');
INSERT INTO met_config VALUES('208','metconfig_cv_image','0','0','0','en');
INSERT INTO met_config VALUES('209','metconfig_cv_emtype','1','0','0','en');
INSERT INTO met_config VALUES('210','metconfig_cv_to','','0','0','en');
INSERT INTO met_config VALUES('211','metconfig_wap','1','0','0','en');
INSERT INTO met_config VALUES('212','metconfig_waplink','1','0','0','en');
INSERT INTO met_config VALUES('213','metconfig_wap_ok','0','0','0','en');
INSERT INTO met_config VALUES('214','metconfig_wap_tpa','1','0','0','en');
INSERT INTO met_config VALUES('215','metconfig_wap_tpb','0','0','0','en');
INSERT INTO met_config VALUES('216','metconfig_wap_url','','0','0','en');
INSERT INTO met_config VALUES('217','metconfig_wap_logo','../upload/201207/1342516579.png','0','0','en');
INSERT INTO met_config VALUES('218','metconfig_wap_img','../upload/201207/1342516476.jpg','0','0','en');
INSERT INTO met_config VALUES('219','wap_news_list','5','0','0','en');
INSERT INTO met_config VALUES('220','wap_product_list','5','0','0','en');
INSERT INTO met_config VALUES('221','wap_download_list','5','0','0','en');
INSERT INTO met_config VALUES('222','wap_img_list','5','0','0','en');
INSERT INTO met_config VALUES('223','wap_job_list','5','0','0','en');
INSERT INTO met_config VALUES('224','wap_product_imgx','200','0','0','en');
INSERT INTO met_config VALUES('225','wap_product_imgy','200','0','0','en');
INSERT INTO met_config VALUES('226','wap_img_imgx','240','0','0','en');
INSERT INTO met_config VALUES('227','wap_img_imgy','200','0','0','en');
INSERT INTO met_config VALUES('228','wap_title','123123','0','0','en');
INSERT INTO met_config VALUES('229','wap_description','MetInfo enterprise website management system ','0','0','en');
INSERT INTO met_config VALUES('230','wap_footertext','gerger','0','0','en');
INSERT INTO met_config VALUES('231','metconfig_weburl','','0','0','en');
INSERT INTO met_config VALUES('232','metconfig_webname','Website Name','0','0','en');
INSERT INTO met_config VALUES('233','metconfig_logo','../upload/201207/1342516579.png','0','0','en');
INSERT INTO met_config VALUES('234','metconfig_skin_user','metv5s','0','0','en');
INSERT INTO met_config VALUES('235','metconfig_big_wate','0','0','0','en');
INSERT INTO met_config VALUES('236','metconfig_thumb_wate','0','0','0','en');
INSERT INTO met_config VALUES('237','metconfig_wate_class','1','0','0','en');
INSERT INTO met_config VALUES('238','metconfig_wate_img','','0','0','en');
INSERT INTO met_config VALUES('239','metconfig_wate_bigimg','','0','0','en');
INSERT INTO met_config VALUES('240','metconfig_thumb_kind','2','0','0','en');
INSERT INTO met_config VALUES('241','metconfig_text_wate','www.MetInfo.cn','0','0','en');
INSERT INTO met_config VALUES('242','metconfig_text_size','10','0','0','en');
INSERT INTO met_config VALUES('243','metconfig_text_bigsize','15','0','0','en');
INSERT INTO met_config VALUES('244','metconfig_text_fonts','../include/fonts/arial.ttf','0','0','en');
INSERT INTO met_config VALUES('245','metconfig_text_color','#808080','0','0','en');
INSERT INTO met_config VALUES('246','metconfig_text_angle','0','0','0','en');
INSERT INTO met_config VALUES('247','metconfig_watermark','0','0','0','en');
INSERT INTO met_config VALUES('248','metconfig_img_style','1','0','0','en');
INSERT INTO met_config VALUES('249','metconfig_img_x','150','0','0','en');
INSERT INTO met_config VALUES('250','metconfig_img_y','150','0','0','en');
INSERT INTO met_config VALUES('251','metconfig_newsimg_x','200','0','0','en');
INSERT INTO met_config VALUES('252','metconfig_newsimg_y','200','0','0','en');
INSERT INTO met_config VALUES('253','metconfig_productimg_x','160','0','0','en');
INSERT INTO met_config VALUES('254','metconfig_productimg_y','130','0','0','en');
INSERT INTO met_config VALUES('255','metconfig_imgs_x','216','0','0','en');
INSERT INTO met_config VALUES('256','metconfig_imgs_y','100','0','0','en');
INSERT INTO met_config VALUES('257','metconfig_keywords','Website Keywords','0','0','en');
INSERT INTO met_config VALUES('258','metconfig_description','MetInfo enterprise content manager system','0','0','en');
INSERT INTO met_config VALUES('259','metconfig_title_type','3','0','0','en');
INSERT INTO met_config VALUES('260','metconfig_tools_ok','0','0','0','en');
INSERT INTO met_config VALUES('261','metconfig_tools_code','<div class="jiathis_style"><span class="jiathis_txt">分享到：</span><a class="jiathis_button_icons_1"></a><a class="jiathis_button_icons_2"></a><a class="jiathis_button_icons_3"></a><a class="jiathis_button_icons_4"></a><a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jtico jtico_jiathis" target="_blank"></a></div><script type="text/javascript" src="http://v3.jiathis.com/code/jia.js?uid=1346378669840136" charset="utf-8"></script>','0','0','en');
INSERT INTO met_config VALUES('262','metconfig_alt','MetInfo enterprise content manager system | MetInfo CMS','0','0','en');
INSERT INTO met_config VALUES('263','metconfig_atitle','MetInfo CMS','0','0','en');
INSERT INTO met_config VALUES('264','metconfig_linkname','MetInfo CMS','0','0','en');
INSERT INTO met_config VALUES('265','metconfig_online_type','3','0','0','en');
INSERT INTO met_config VALUES('266','metconfig_footaddress','','0','0','en');
INSERT INTO met_config VALUES('267','metconfig_foottel','','0','0','en');
INSERT INTO met_config VALUES('268','metconfig_footother','','0','0','en');
INSERT INTO met_config VALUES('269','metconfig_foottext','','0','0','en');
INSERT INTO met_config VALUES('270','metconfig_product_list','10','0','0','en');
INSERT INTO met_config VALUES('271','metconfig_news_list','8','0','0','en');
INSERT INTO met_config VALUES('272','metconfig_download_list','10','0','0','en');
INSERT INTO met_config VALUES('273','metconfig_img_list','12','0','0','en');
INSERT INTO met_config VALUES('274','metconfig_job_list','10','0','0','en');
INSERT INTO met_config VALUES('275','metconfig_message_list','10','0','0','en');
INSERT INTO met_config VALUES('276','metconfig_search_list','10','0','0','en');
INSERT INTO met_config VALUES('277','metconfig_fd_fromname','MetInfo Co.,Ltd','0','0','en');
INSERT INTO met_config VALUES('278','metconfig_fd_smtp','61.152.188.131','0','0','en');
INSERT INTO met_config VALUES('279','metconfig_fd_usename','test@mail.metinfo.cn','0','0','en');
INSERT INTO met_config VALUES('280','metconfig_fd_password','123456','0','0','en');
INSERT INTO met_config VALUES('281','metconfig_skin_css','metinfo.css','0','0','en');
INSERT INTO met_config VALUES('282','metconfig_autothumb_ok','1','0','0','en');
INSERT INTO met_config VALUES('283','metconfig_member_use','1','0','0','en');
INSERT INTO met_config VALUES('284','metconfig_member_login','3','0','0','en');
INSERT INTO met_config VALUES('285','metconfig_newsdays','3','0','0','en');
INSERT INTO met_config VALUES('286','metconfig_hot','100','0','0','en');
INSERT INTO met_config VALUES('287','metconfig_listtime','Y/m/d','0','0','en');
INSERT INTO met_config VALUES('288','metconfig_contenttime','Y-m-d H:i:s','0','0','en');
INSERT INTO met_config VALUES('289','metconfig_memberemail','Welcome to register the member of MetInfo(www.metinfo.cn), after activated you can enjoy more professional service!','0','0','en');
INSERT INTO met_config VALUES('290','metconfig_membercontrol','Welcome to register the member of【MetInfo】www.metinfo.cn, after activated you can enjoy more professional service!','0','0','en');
INSERT INTO met_config VALUES('291','metconfig_pseudo','0','0','0','en');
INSERT INTO met_config VALUES('292','metconfig_online_skin','3','0','0','en');
INSERT INTO met_config VALUES('293','metconfig_online_color','1','0','0','en');
INSERT INTO met_config VALUES('294','metconfig_qq_type','4','0','0','en');
INSERT INTO met_config VALUES('295','metconfig_msn_type','1','0','0','en');
INSERT INTO met_config VALUES('296','metconfig_taobao_type','2','0','0','en');
INSERT INTO met_config VALUES('297','metconfig_alibaba_type','102','0','0','en');
INSERT INTO met_config VALUES('298','metconfig_skype_type','13','0','0','en');
INSERT INTO met_config VALUES('299','metconfig_addlinkopen','1','0','0','en');
INSERT INTO met_config VALUES('300','metconfig_pageskin','8','0','0','en');
INSERT INTO met_config VALUES('301','metconfig_indexskin','index','0','0','en');
INSERT INTO met_config VALUES('302','metconfig_urlblank','0','0','0','en');
INSERT INTO met_config VALUES('303','metconfig_pnorder','0','0','0','en');
INSERT INTO met_config VALUES('304','metconfig_hitsok','1','0','0','en');
INSERT INTO met_config VALUES('305','metconfig_product_page','0','0','0','en');
INSERT INTO met_config VALUES('306','metconfig_img_page','0','0','0','en');
INSERT INTO met_config VALUES('307','metconfig_product_detail','1','0','0','en');
INSERT INTO met_config VALUES('308','metconfig_img_detail','5','0','0','en');
INSERT INTO met_config VALUES('309','metconfig_productdetail_x','400','0','0','en');
INSERT INTO met_config VALUES('310','metconfig_productdetail_y','400','0','0','en');
INSERT INTO met_config VALUES('311','metconfig_imgdetail_x','610','0','0','en');
INSERT INTO met_config VALUES('312','metconfig_imgdetail_y','287','0','0','en');
INSERT INTO met_config VALUES('313','metconfig_onlineright_top','118','0','0','en');
INSERT INTO met_config VALUES('314','metconfig_onlineright_right','0','0','0','en');
INSERT INTO met_config VALUES('315','metconfig_onlineleft_top','118','0','0','en');
INSERT INTO met_config VALUES('316','metconfig_onlineleft_left','0','0','0','en');
INSERT INTO met_config VALUES('317','metconfig_onlinenameok','','0','0','en');
INSERT INTO met_config VALUES('318','metconfig_file_format','rar|zip|doc|pdf|jpg|jpeg|xls|png|gif|mp3|ico|swf','0','0','en');
INSERT INTO met_config VALUES('319','metconfig_file_maxsize','5','0','0','en');
INSERT INTO met_config VALUES('320','metconfig_memberlogin_code','1','0','0','en');
INSERT INTO met_config VALUES('321','metconfig_login_code','0','0','0','en');
INSERT INTO met_config VALUES('322','metconfig_webhtm','0','0','0','en');
INSERT INTO met_config VALUES('323','metconfig_htmtype','html','0','0','en');
INSERT INTO met_config VALUES('324','metconfig_htmpagename','2','0','0','en');
INSERT INTO met_config VALUES('325','metconfig_listhtmltype','1','0','0','en');
INSERT INTO met_config VALUES('326','metconfig_htmlistname','1','0','0','en');
INSERT INTO met_config VALUES('327','metconfig_htmway','0','0','0','en');
INSERT INTO met_config VALUES('328','index_news_no','3','0','0','en');
INSERT INTO met_config VALUES('329','index_product_no','10','0','0','en');
INSERT INTO met_config VALUES('330','index_download_no','10','0','0','en');
INSERT INTO met_config VALUES('331','index_img_no','10','0','0','en');
INSERT INTO met_config VALUES('332','index_job_no','10','0','0','en');
INSERT INTO met_config VALUES('333','index_link_ok','1','0','0','en');
INSERT INTO met_config VALUES('334','index_link_img','10','0','0','en');
INSERT INTO met_config VALUES('335','index_link_text','20','0','0','en');
INSERT INTO met_config VALUES('336','metconfig_pageclick','','0','0','en');
INSERT INTO met_config VALUES('337','metconfig_pagetime','','0','0','en');
INSERT INTO met_config VALUES('338','metconfig_pageprint','','0','0','en');
INSERT INTO met_config VALUES('339','metconfig_pageclose','','0','0','en');
INSERT INTO met_config VALUES('340','metconfig_deleteimg','0','0','0','en');
INSERT INTO met_config VALUES('341','metconfig_columnshow','0','0','0','en');
INSERT INTO met_config VALUES('342','metconfig_onlinetel','','0','0','en');
INSERT INTO met_config VALUES('343','metconfig_kzqie','0','0','0','en');
INSERT INTO met_config VALUES('344','metconfig_seo','<p><a href="http://www.metinfo.cn/" target="_blank">MetInfo CMS</a> | <a href="http://www.metinfo.cn/idc" target="_blank">Foreign Host</a> | <a href="http://ok.metinfo.cn/" target="_blank">Domain Registration</a></p>','0','0','en');
INSERT INTO met_config VALUES('345','metconfig_footright','MSN:0000@000.com Email:sales@metinfo.cn','0','0','en');
INSERT INTO met_config VALUES('346','metconfig_footstat','<script src="http://s6.cnzz.com/stat.php?id=1670348&web_id=1670348&show=pic" language="JavaScript"></script>','0','0','en');
INSERT INTO met_config VALUES('528','metconfig_cv_back','0','0','0','en');
INSERT INTO met_config VALUES('529','metconfig_cv_title','','0','0','en');
INSERT INTO met_config VALUES('530','metconfig_cv_content','','0','0','en');
INSERT INTO met_config VALUES('531','metconfig_cv_email','49','0','0','en');
INSERT INTO met_config VALUES('532','index_hadd_ok','1','0','0','en');
INSERT INTO met_config VALUES('536','metconfig_hometitle','','0','0','en');
INSERT INTO met_config VALUES('538','metconfig_img_rename','1','0','0','cn');
INSERT INTO met_admin_array VALUES('4','Member','','0','','0','0','1','1','en','');
INSERT INTO met_admin_array VALUES('5','Agents','','0','','0','0','2','1','en','');